SELECT
  A.*
FROM Tb_Base_Revenda_Ourocap_OTC291_Tratada_TMKT A
  /* CHECAGEM SE TOODS OS CONTATOS TIVERAM O OTC TRATADO */
LEFT OUTER JOIN ( 
  SELECT
    COUNT(1) as CPFS_FALTANDO_NO_OTC
  FROM 	Tb_Base_Revenda_Ourocap_Filtrada_TMTK ENV
  LEFT JOIN Tb_Base_Revenda_Ourocap_OTC291_Tratada_TMKT RET ON ENV.CPF_CNPJ = RET.CPF_CNPJ
  WHERE RET.CPF_CNPJ IS NULL
) B ON 1 = 1
WHERE A.CODIGO_RNA = '000'
  AND A.ALTA_RENDA = 0