SELECT DISTINCT
  B.CPF,
  'TCBB' AS COD_PARCEIRO,
  '' AS CNPJ,
  'Brasilcap' AS PARCEIRO_ORGANIZACAO,
  'Brazil' AS PARCEIRO_LOCALIZACAO,
  A.ID_CLIENTE_PARCEIRO AS COD_CLIENTE_MC,
  C.NOME AS NOME_COMPLETO,
  'PF' AS TIPO_PESSOA,
  CONVERT(VARCHAR, CONVERT(DATE, B.Dt_Nascimento, 103), 112) AS DATA_NASCIMENTO,
  C.SEXO,
  'Brasilcap' AS CLIENTE_ORGANIZACAO,
  CONCAT(B.CPF, 'TCBB') AS CLIENTE_CHAVE_MIGRACAO,
  CONCAT(B.CPF, 'TCBB') AS CLIENTE_CHAGE_GERAL_INTERNA,
  'Person' AS CLIENTE_TIPO_INTERNO
FROM
  Tb_Base_Ex_Cliente_OTC291_Filtrada_TMKT A 
  INNER JOIN
    Tb_Base_Ex_Cliente_OTC291_Tratada_TMKT B 
    ON A.CPF = B.CPF
 INNER JOIN 
    Tb_Base_Ex_Cliente_ComOTC_Filtrada_TMKT C
    ON A.CPF = C.CPF_CNPJ