SELECT DISTINCT
  /* Telefone 1 */
  CASE
    WHEN NULLIF(TEL_01, '') IS NULL THEN NULL
    WHEN LEN(Tel_01) > 9 OR ( LEN(Tel_01) = 8 AND Tel_01 LIKE '9%' ) THEN NULL
    ELSE Ddd_Tel_01
  END AS DDD1,
  CASE
    WHEN NULLIF(TEL_01, '') IS NULL THEN NULL
    WHEN LEN(Tel_01) > 9 OR ( LEN(Tel_01) = 8 AND Tel_01 LIKE '9%' ) THEN NULL
    ELSE Tel_01
  END AS TELEFONE1,
  CASE
    WHEN NULLIF(TEL_01, '') IS NULL THEN NULL
    WHEN LEN(Tel_01) > 9 OR ( LEN(Tel_01) = 8 AND Tel_01 LIKE '9%' ) THEN NULL
    ELSE Tipo_Tel_01
  END AS TIPO1,
  /* Telefone 2 */
  CASE
    WHEN NULLIF(TEL_02, '') IS NULL THEN NULL
    WHEN LEN(Tel_02) > 9 OR ( LEN(Tel_02) = 8 AND Tel_02 LIKE '9%' ) THEN NULL
    ELSE Ddd_Tel_02
  END AS DDD2,
  CASE
    WHEN NULLIF(TEL_02, '') IS NULL THEN NULL
    WHEN LEN(Tel_02) > 9 OR ( LEN(Tel_02) = 8 AND Tel_02 LIKE '9%' ) THEN NULL
    ELSE Tel_02
  END AS TELEFONE2,
  CASE
    WHEN NULLIF(TEL_02, '') IS NULL THEN NULL
    WHEN LEN(Tel_02) > 9 OR ( LEN(Tel_02) = 8 AND Tel_02 LIKE '9%' ) THEN NULL
    ELSE Tipo_Tel_02
  END AS TIPO2,
  /* Telefone 3 */
  CASE
    WHEN NULLIF(TEL_03, '') IS NULL THEN NULL
    WHEN LEN(Tel_03) > 9 OR ( LEN(Tel_03) = 8 AND Tel_03 LIKE '9%' ) THEN NULL
    ELSE Ddd_Tel_03
  END AS DDD3,
  CASE
    WHEN NULLIF(TEL_03, '') IS NULL THEN NULL
    WHEN LEN(Tel_03) > 9 OR ( LEN(Tel_03) = 8 AND Tel_03 LIKE '9%' ) THEN NULL
    ELSE Tel_03
  END AS TELEFONE3,
  CASE
    WHEN NULLIF(TEL_03, '') IS NULL THEN NULL
    WHEN LEN(Tel_03) > 9 OR ( LEN(Tel_03) = 8 AND Tel_03 LIKE '9%' ) THEN NULL
    ELSE Tipo_Tel_03
  END AS TIPO3,
  /* Telefone 4 */
  CASE
    WHEN NULLIF(TEL_04, '') IS NULL THEN NULL
    WHEN LEN(Tel_04) > 9 OR ( LEN(Tel_04) = 8 AND Tel_04 LIKE '9%' ) THEN NULL
    ELSE Ddd_Tel_04
  END AS DDD4,
  CASE
    WHEN NULLIF(TEL_04, '') IS NULL THEN NULL
    WHEN LEN(Tel_04) > 9 OR ( LEN(Tel_04) = 8 AND Tel_04 LIKE '9%' ) THEN NULL
    ELSE Tel_04
  END AS TELEFONE4,
  CASE
    WHEN NULLIF(TEL_04, '') IS NULL THEN NULL
    WHEN LEN(Tel_04) > 9 OR ( LEN(Tel_04) = 8 AND Tel_04 LIKE '9%' ) THEN NULL
    ELSE Tipo_Tel_04
  END AS TIPO4,
  /* Telefone 5 */
  CASE
    WHEN NULLIF(TEL_05, '') IS NULL THEN NULL
    WHEN LEN(Tel_05) > 9 OR ( LEN(Tel_05) = 8 AND Tel_05 LIKE '9%' ) THEN NULL
    ELSE Ddd_Tel_05
  END AS DDD5,
  CASE
    WHEN NULLIF(TEL_05, '') IS NULL THEN NULL
    WHEN LEN(Tel_05) > 9 OR ( LEN(Tel_05) = 8 AND Tel_05 LIKE '9%' ) THEN NULL
    ELSE Tel_05
  END AS TELEFONE5,
  CASE
    WHEN NULLIF(TEL_05, '') IS NULL THEN NULL
    WHEN LEN(Tel_05) > 9 OR ( LEN(Tel_05) = 8 AND Tel_05 LIKE '9%' ) THEN NULL
    ELSE Tipo_Tel_05
  END AS TIPO5,
  /* Telefone 6 */
  TEL_PRINCIPAL AS PREFERENCIAL,
  IDADE,
  CONVERT(VARCHAR(10), DT_NASCIMENTO, 103) AS DATA_NASCIMENTO,
  NOME AS NOME_CLIENTE,
  CEP,
  UF,
  TIPO_PESSOA AS TIPO_DE_PESSOA,
  CPF_CNPJ,
  SEXO,
  PUBLICO_ALVO AS CLASSIFICACAO,
  TIPO_CAMPANHA,
  CONVERT(VARCHAR(10), DT_CRIACAO_MAILING, 103) AS DATA_CRIACAO,
  CONVERT(VARCHAR(10), DT_INICIO_MAILING, 103) AS DATA_UTILIZACAO,
  CONVERT(VARCHAR(10), DT_FIM_MAILING, 103) AS DATA_TERMINO,
  ID_CAMPANHA AS IDCAMPANHA,
  ID_CONTATO AS IDCONTATOS,
  ID_CLIENTE_PARCEIRO AS IDCP
FROM
  TB_BASE_REVENDA_OUROCAP_OTC291_FILTRADA_TMKT
  WHERE
  ID_CAMPANHA = '7016g000000FjOqAAK'
  AND
  Id_Membro_Campanha IS NOT NULL