SELECT
	A.*
FROM (
	SELECT DISTINCT
		B.HC_CPF_CNPJ__C AS CPF_CNPJ,
		C.NAME AS NOME,
		CASE
			WHEN B.HC_EMAIL_PRINCIPAL__C = 'Brasilcap' THEN HC_EMAIL_BRASILCAP__C
			WHEN B.HC_EMAIL_PRINCIPAL__C = 'Comercial' THEN HC_EMAIL_COMERCIAL__C
			WHEN B.HC_EMAIL_PRINCIPAL__C = 'Pessoal' THEN HC_EMAIL_PESSOAL__C
			WHEN B.HC_EMAIL_BRASILCAP__C IS NOT NULL THEN HC_EMAIL_BRASILCAP__C
			WHEN B.HC_EMAIL_COMERCIAL__C IS NOT NULL THEN HC_EMAIL_COMERCIAL__C
			WHEN B.HC_EMAIL_PESSOAL__C IS NOT NULL THEN HC_EMAIL_PESSOAL__C
			ELSE NULL
		END AS EMAIL,
		CASE
			WHEN B.HC_EMAIL_PRINCIPAL__C IN ('Brasilcap', 'Comercial', 'Pessoal') THEN 1
			WHEN B.HC_EMAIL_BRASILCAP__C IS NOT NULL THEN 1
			WHEN B.HC_EMAIL_COMERCIAL__C IS NOT NULL THEN 1
			WHEN B.HC_EMAIL_PESSOAL__C IS NOT NULL THEN 1
			ELSE 0
		END AS EMAIL_VALIDO,
		CASE
			WHEN B.HC_STATUS_CELULAR_1__C = 'VÁLIDO' THEN HC_CELULAR_1__C
			WHEN B.HC_STATUS_CELULAR_2__C = 'VÁLIDO' THEN HC_CELULAR_2__C
			WHEN B.HC_STATUS_CELULAR_3__C = 'VÁLIDO' THEN HC_CELULAR_3__C
			ELSE NULL
		END AS CELULAR,
		CASE
			WHEN B.HC_STATUS_CELULAR_1__C = 'VÁLIDO' THEN 1
			WHEN B.HC_STATUS_CELULAR_2__C = 'VÁLIDO' THEN 1
			WHEN B.HC_STATUS_CELULAR_3__C = 'VÁLIDO' THEN 1
			ELSE 0
		END AS CELULAR_VALIDO,
		B.HC_TIPO_DE_PESSOA__C AS TIPO_PESSOA,
		B.HC_TELEFONE_PRINCIPAL__C AS TEL_PRINCIPAL,
		A.HC_PRODUTO__C AS ID_PRODUTO,
		A.ID AS ID_CAMPANHA, 
		B.ID AS ID_CLIENTE_PARCEIRO,
		C.ID AS ID_CONTATO,
		D.HC_VALOR_DA_PARCELA__C AS VALOR_PARCELA_PRODUTO,
		D.HC_NUMERO_DO_TITULO__C as NUMERO_DO_TITULO,
		D.Id as Id_Titulo,
		D.HC_SERIE__C as SERIE_DO_TITULO,
		D.HC_PLANO__C as PLANO_DO_TITULO,
		D.HC_CONTRATACAO__C AS DATA_CONTRATACAO,
    B.HC_NAO_DESEJA_RECEBER_EMAIL__C AS NAO_DESEJA_RECEBER_EMAIL,
    B.HC_NAO_DESEJA_RECEBER_SMS__C AS NAO_DESEJA_RECEBER_SMS,
		D.CREATEDDATE,
		ROW_NUMBER() OVER(ORDER BY B.ID ASC) AS ROWNO
	FROM CAMPAIGN_SALESFORCE A
	INNER JOIN HC_RELACAO_CLIENTE_PARCEIRO__C_SALESFORCE B ON A.HC_PARCEIRO__C = B.HC_PARCEIRO__C
	INNER JOIN CONTACT_SALESFORCE C ON C.HC_CPF_CNPJ__C = B.HC_CPF_CNPJ__C
	INNER JOIN HC_TITULO__C_SALESFORCE D ON D.HC_CLIENTE_X_PARCEIRO__C = B.ID
	WHERE
		(B.HC_TIPO_DE_PESSOA__C = A.HC_TIPO_DE_CLIENTE__C OR A.HC_TIPO_DE_CLIENTE__C = 'PF E PJ')
	/* MOMENTO DE EXECUÇÃO DA CAMPANHA */
    AND CONVERT(VARCHAR(10), A.HC_DATA_DE_EXECUCAO__C, 101) = CONVERT(VARCHAR(10), GETDATE(), 101)
    AND DATEPART(HH, A.HC_DATA_DE_EXECUCAO__C) = DATEPART(HH, GETDATE())
	AND A.ISACTIVE = 1
	/* ID DA CAMPANHA PAI (HEADER) DE BOAS VINDAS OUROCAP */
	AND A.PARENTID = '7016g000000NVrXAAW'
	/* AND A.HC_CAMPANHA_EXECUTADA_NO_MKT__C = 0 */
	AND D.HC_SITUACAO__C = 'ATIVO'
	/* PARCEIRO TCBB PARA OUROCAP */
	AND D.HC_ORIGEM__C = 'CAP'
	AND D.HC_CODIGO_DO_PARCEIRO_NA_ORIGEM__C = 'TCBB'
	AND B.HC_NAO_DESEJA_RECEBER_TODOS_MEIOS__C = 0
	AND D.CREATEDDATE BETWEEN A.HC_DATA_INICIAL_DE_COMPRA__C AND A.HC_DATA_FINAL_DE_COMPRA__C
	AND (
		/* CUSTOM BETWEEN */
		(A.HC_VALOR_MINIMO_DE_PARCELA__C IS NULL OR D.HC_VALOR_DA_PARCELA__C > A.HC_VALOR_MINIMO_DE_PARCELA__C)
		AND (A.HC_VALOR_MAXIMO_DA_PARCELA__C IS NULL OR D.HC_VALOR_DA_PARCELA__C < A.HC_VALOR_MAXIMO_DA_PARCELA__C)
	)
	/* AND (
		OR B.HC_STATUS_CELULAR_1__C = 'ATIVO'
		OR B.HC_STATUS_CELULAR_2__C = 'ATIVO'
		OR B.HC_STATUS_CELULAR_3__C = 'ATIVO'
		OR B.HC_STATUS_TEL_OUTRO__C = 'ATIVO'
		OR B.HC_STATUS_TEL_COMERCIAL__C = 'ATIVO'
		OR B.HC_STATUS_TEL_RESIDENCIAL__C = 'ATIVO'
	) */
) A
INNER JOIN
  CAMPAIGN_SALESFORCE CAMP 
  ON A.ID_CAMPANHA = CAMP.ID
WHERE
	CAMP.HC_QUANTIDADE_DE_CONTATOS_NO_MAILING__C IS NULL
	OR A.ROWNO <= CAMP.HC_QUANTIDADE_DE_CONTATOS_NO_MAILING__C