SELECT
  B.CPF as CPF_CNPJ,
  CMP.NAME AS CAMPANHA,
  /* PAR.HC_CODIGO_DO_PARCEIRO_CAP__C AS PARCEIRO, */
  /* CONVERT(INTEGER, REL.HC_IDADE__C) AS  IDADE, */
  DATEDIFF(YY,
  CAST(B.DATA_NASCIMENTO AS DATE),
  GETDATE()) AS  IDADE,
  /* B.COMPRA_UTIMOS_30_DIAS AS COMPROU_ULTIMOS_30_DIAS, */
  B.CONSELHEIRO,
  /* B.CLIENTE_PEP, */
  B.CLIENTE,
  /* B.DESEJA_CONTATO_TELEFONICO AS NAO_DESEJA_RECEBER_LIGACOES, */
  /* B.POSSUI_TELEFONE_ATIVO, */
  /* B.POSSUI_CONTA_CORRENTE, */
  B.CONTA_CORRENTE AS POSSUI_CONTA_CORRENTE,
  /* B.POSSUI_TITULO_ATIVO, */
  B.QUARENTENA,
  /* B.NAO_IMPORTUNE, */
  /* B.CEP_VALIDO, */
  CASE
    WHEN (B.IDADE_VALIDA IS NULL OR B.IDADE_VALIDA = 0) THEN 'IDADE INVALIDA'
    WHEN (B.CONSELHEIRO IS NULL OR B.CONSELHEIRO = 1) THEN 'CONSELHEIRO'
    WHEN (B.CLIENTE IS NULL OR B.CLIENTE = 1) THEN 'CLIENTE'
    WHEN (B.CONTA_CORRENTE IS NULL OR B.CONTA_CORRENTE = 0) THEN 'NÃO POSSUI CONTA CORRENTE'
    WHEN (B.QUARENTENA IS NULL OR B.QUARENTENA = 1) THEN 'QUARENTENA'
    WHEN (B.NAO_IMPORTUNE IS NULL OR B.NAO_IMPORTUNE = 1) THEN 'NÃO IMPORTUNE'
    /* WHEN (B.CEP_VALIDO IS NULL OR B.CEP_VALIDO = 0) THEN 'CEP INVALIDO' */
  END AS RESULTADO
  /* B.NOME_VALIDA */
FROM
  TB_BASE_PROSPECT_SEMOTC_TRATADA_TEO B
LEFT JOIN CAMPAIGN_SALESFORCE CMP ON B.ID_CAMPANHA = CMP.ID
/* LEFT JOIN HC_PARCEIRO__C_SALESFORCE PAR ON B.PARCEIRO = PAR.ID */
/* LEFT JOIN HC_RELACAO_CLIENTE_PARCEIRO__C_SALESFORCE REL ON B.ID_CLIENTE_PARCEIRO = REL.ID */
WHERE
  B.CPF IS NOT NULL
  AND (
  (B.IDADE_VALIDA IS NULL OR B.IDADE_VALIDA = 0)
  OR (B.CONSELHEIRO IS NULL OR B.CONSELHEIRO = 1)
  OR (B.CLIENTE IS NULL OR B.CLIENTE = 1)
  /* OR (B.CLIENTE_PEP IS NULL OR B.CLIENTE_PEP = 1) */
  /* OR (B.DESEJA_CONTATO_TELEFONICO IS NULL OR B.DESEJA_CONTATO_TELEFONICO = 1) */
  /* OR (B.POSSUI_TELEFONE_ATIVO IS NULL OR B.POSSUI_TELEFONE_ATIVO = 0) */
  /* OR (B.POSSUI_CONTA_CORRENTE IS NULL OR B.POSSUI_CONTA_CORRENTE = 0) */
  OR (B.CONTA_CORRENTE IS NULL OR B.CONTA_CORRENTE = 0)
  OR (B.QUARENTENA IS NULL OR B.QUARENTENA = 1)
  OR (B.NAO_IMPORTUNE IS NULL OR B.NAO_IMPORTUNE = 1)
  /* OR (B.CEP_VALIDO IS NULL OR B.CEP_VALIDO = 0) */
  /* OR B.ULTIMO_RESGATE = 1 */
  /* OR B.SITUACAO_RESGATE = 1 */
  /* OR (B.NOME_VALIDA IS NULL OR B.NOME_VALIDA = 0) */
  )