SELECT
    A.CPF_CNPJ AS ID,
	1 AS QUARENTENA
FROM
	Revenda_Ourocap_PublicoInicial A
INNER JOIN TB_BASE_QUARENTENA Q ON A.CPF_CNPJ = Q.CPF_CNPJ
WHERE DATEDIFF(MM, Q.DATA_PARTICIPACAO_CAMPANHA, GETDATE()) <= A.MESES_QUARENTENA_EXCLUSAO