SELECT
    A.CPF_CNPJ AS ID,
	1 AS QUARENTENA
FROM
	TB_BASE_REVENDA_OUROCAP_COMOTC_TMKT A
INNER JOIN TB_BASE_QUARENTENA Q ON A.CPF_CNPJ = Q.CPF_CNPJ
WHERE DATEDIFF(MM, Q.DATA_PARTICIPACAO_CAMPANHA, GETDATE()) <= A.MESES_QUARENTENA_EXCLUSAO

/* 

SELECT
    A.CPF_CNPJ AS ID,
	CASE WHEN Q.CPF_CNPJ IS NOT NULL THEN 1 ELSE 0 END AS QUARENTENA
FROM
	TB_BASE_REVENDA_OUROCAP_COMOTC_TMKT A
LEFT JOIN TB_BASE_QUARENTENA Q ON A.CPF_CNPJ = Q.CPF_CNPJ
AND Q.DATA_PARTICIPACAO_CAMPANHA > DATEADD(DD, -90, GETDATE())

*/