SELECT
	BASE.*
FROM (
	SELECT DISTINCT
		B.HC_CPF_CNPJ__C AS CPF_CNPJ,
		REPLACE( REPLACE( REPLACE( REPLACE( REPLACE( REPLACE( REPLACE (REPLACE (REPLACE (REPLACE (REPLACE (REPLACE (REPLACE (REPLACE (REPLACE (REPLACE (REPLACE (REPLACE (REPLACE (REPLACE (REPLACE (REPLACE (REPLACE (REPLACE (REPLACE (REPLACE (REPLACE (REPLACE (REPLACE (REPLACE (C.NAME, 'Á', 'A'),'É', 'E'),'Í', 'I'),'Ó', 'O'),'Ú', 'U'),'Á', 'A'),'É', 'E'),'Í', 'I'),'Ó', 'O'),'Ú', 'U'),'À', 'A'),'À', 'A'),'Ã', 'A'),'Õ', 'O'),'Ã', 'A'),  'Õ', 'O'),'Â', 'A'),'Ê', 'E'),'Ô', 'O'),'Â', 'A'),'Ê', 'E'),'Ô', 'O'),'Ç', 'C'),'Ç', 'C') , '-', '') , '+', '') , '|', '') , '$', '') , '%', '') , '&', '') AS NOME,
		B.HC_IDADE__C AS IDADE,
		B.HC_DATA_DE_NASCIMENTO__C AS DT_NASCIMENTO,
		B.HC_GENERO_DO_CLIENTE__C AS SEXO,
		B.HC_PARCEIRO__C AS PARCEIRO,
		CASE 
			WHEN UPPER(B.HC_ENDERECO_PRINCIPAL__C) = 'RESIDENCIAL' THEN HC_UF_RES__C
			WHEN UPPER(B.HC_ENDERECO_PRINCIPAL__C) = 'COMERCIAL' THEN HC_UF_COM__C
			WHEN UPPER(B.HC_ENDERECO_PRINCIPAL__C) = 'CORRESPONDÊNCIA' THEN HC_UF_COR__C
		END AS UF,
		CASE 
			WHEN UPPER(B.HC_ENDERECO_PRINCIPAL__C) = 'RESIDENCIAL' THEN HC_CEP_RES__C
			WHEN UPPER(B.HC_ENDERECO_PRINCIPAL__C) = 'COMERCIAL' THEN HC_CEP_COM__C
			WHEN UPPER(B.HC_ENDERECO_PRINCIPAL__C) = 'CORRESPONDÊNCIA' THEN HC_CEP_COR__C
		END AS CEP,
		B.HC_TIPO_DE_PESSOA__C AS TIPO_PESSOA,
		LEFT(REPLACE(REPLACE(REPLACE(REPLACE(B.HC_TELEFONE_RESIDENCIAL__C, '(', ''), ')', ''), ' ', ''), '-', ''), 2) AS DDD_TEL_01,
		SUBSTRING(REPLACE(REPLACE(REPLACE(REPLACE(B.HC_TELEFONE_RESIDENCIAL__C, '(', ''), ')', ''), ' ', ''), '-', ''), 3, 9) AS TEL_01,
		'FIXO' AS TIPO_TEL_01,
		LEFT(REPLACE(REPLACE(REPLACE(REPLACE(B.HC_TELEFONE_COMERCIAL__C, '(', ''), ')', ''), ' ', ''), '-', ''), 2) AS DDD_TEL_02,
		SUBSTRING(REPLACE(REPLACE(REPLACE(REPLACE(B.HC_TELEFONE_COMERCIAL__C, '(', ''), ')', ''), ' ', ''), '-', ''), 3, 9) AS TEL_02,
		'FIXO' AS TIPO_TEL_02,
		LEFT(REPLACE(REPLACE(REPLACE(REPLACE(B.HC_TELEFONE_OUTRO__C, '(', ''), ')', ''), ' ', ''), '-', ''), 2) AS DDD_TEL_03,
		SUBSTRING(REPLACE(REPLACE(REPLACE(REPLACE(B.HC_TELEFONE_OUTRO__C, '(', ''), ')', ''), ' ', ''), '-', ''), 3, 9) AS TEL_03,
		'FIXO' AS TIPO_TEL_03,
		LEFT(REPLACE(REPLACE(REPLACE(REPLACE(B.HC_CELULAR_1__C, '(', ''), ')', ''), ' ', ''), '-', ''), 2) AS DDD_TEL_04,
		SUBSTRING(REPLACE(REPLACE(REPLACE(REPLACE(B.HC_CELULAR_1__C, '(', ''), ')', ''), ' ', ''), '-', ''), 3, 9) AS TEL_04,
		'MÓVEL' AS TIPO_TEL_04,
		LEFT(REPLACE(REPLACE(REPLACE(REPLACE(B.HC_CELULAR_2__C, '(', ''), ')', ''), ' ', ''), '-', ''), 2) AS DDD_TEL_05,
		SUBSTRING(REPLACE(REPLACE(REPLACE(REPLACE(B.HC_CELULAR_2__C, '(', ''), ')', ''), ' ', ''), '-', ''), 3, 9) AS TEL_05,
		'MÓVEL' AS TIPO_TEL_05,
		LEFT(REPLACE(REPLACE(REPLACE(REPLACE(B.HC_CELULAR_3__C, '(', ''), ')', ''), ' ', ''), '-', ''), 2) AS DDD_TEL_06,
		SUBSTRING(REPLACE(REPLACE(REPLACE(REPLACE(B.HC_CELULAR_3__C, '(', ''), ')', ''), ' ', ''), '-', ''), 3, 9) AS TEL_06,
		'MÓVEL' AS TIPO_TEL_06,
		B.HC_TELEFONE_PRINCIPAL__C AS TEL_PRINCIPAL,
		B.HC_CLASSIFICACAO__C AS PUBLICO_ALVO,
		A.[TYPE] AS TIPO_CAMPANHA,
		A.STARTDATE AS DT_INICIO_MAILING,
		A.ENDDATE AS DT_FIM_MAILING,
		A.HC_VALIDA_ALTA_RENDA__C AS CAMPANHA_VALIDA_ENCARTEIRAMENTO,
		A.HC_VALIDA_NAO_IMPORTUNE__C AS CAMPANHA_NAO_IMPORTUNE,
		A.HC_VALIDA_RNA__C AS CAMPANHA_VALIDA_RNA,
		A.HC_PRODUTO__C AS ID_PRODUTO,
		A.HC_PRECO_DO_PRODUTO__C AS ID_PRODUTO_VALOR,
		B.HC_CPF_CNPJ__C AS ID,
		A.ID AS ID_CAMPANHA, 
		B.ID AS ID_CLIENTE_PARCEIRO,
		C.ID AS ID_CONTATO,
		B.HC_CLIENTE__C AS ID_CLIENTE,
		B.HC_CPF_CNPJ_CODIGO_DO_PARCEIRO__C AS CPF_CNPJ_CODIGO_DO_PARCEIRO,
		D.HC_DATA_DO_ULTIMO_RESGATE__C AS DT_ULTIMO_RESGATE,
		D.HC_ORIGEM_DA_VENDA__C AS CANAL_ULTIMO_RESGATE,
		D.HC_SITUACAO__C AS TIPO_RESGATE,
		D.HC_VALOR_DA_PARCELA__C AS VALOR_PARCELA_PRODUTO,
		A.HC_EXCLUSAO_DE_COMPRA_RECENTE__C AS MESES_COMPRA_EXCLUSAO,
		A.HC_QUARENTENA__C AS MESES_QUARENTENA_EXCLUSAO,
		D.HC_TIPO_DE_PAGAMENTO__C AS TIPO_PAGAMENTO,
		DATEADD(DD, -DAY(DATEADD(M, 2, GetDate())), DATEADD(M, 2, GetDate())) AS DATA_PROXIMA_EXECUCAO,
		ROW_NUMBER() OVER(ORDER BY B.ID ASC) AS ROWNO
	FROM (
		SELECT
			  A.ID AS CAMPAIGN_ID,
			  B.ID AS RELACAO_CLIENTE_PARCEIRO_ID,
			  C.ID AS CONTACT_ID,
			  D.ID AS TITULO_ID,
			  ROW_NUMBER() OVER(PARTITION BY B.ID ORDER BY B.ID ASC) AS NUMBER_OF_CPF_REPETITION
			FROM CAMPAIGN_SALESFORCE A
			INNER JOIN HC_RELACAO_CLIENTE_PARCEIRO__C_SALESFORCE B ON A.HC_PARCEIRO__C = B.HC_PARCEIRO__C
			INNER JOIN Contact_Salesforce C ON C.HC_CPF_CNPJ__c = B.HC_CPF_CNPJ__c
			INNER JOIN HC_TITULO__C_SALESFORCE D ON D.HC_CLIENTE_X_PARCEIRO__C = B.ID
			WHERE
				UPPER(A.[TYPE]) = 'AUTOMÁTICO'
			AND A.Id = '7016g000002O08dAAC'
			AND A.HC_VALIDA_RNA__C = 1
			AND B.HC_Id_Parceiro_Cap__c = 'TCBB'
			AND A.ISACTIVE = 1
			AND CONVERT(VARCHAR(10), D.HC_Fim_previsto__c, 120) BETWEEN CONVERT(VARCHAR(10), A.HC_DATA_INICIAL_DO_PERIODO_DE_RESGATE__C, 120) AND CONVERT(VARCHAR(10), A.HC_DATA_FIM_DO_PERIODO_DE_RESGATE__C, 120) 
			AND D.HC_SITUACAO__C LIKE '%Fim de plano%'
			AND D.HC_TIPO_DE_PAGAMENTO__C IN ('PU', 'PP')
			AND (B.HC_TIPO_DE_PESSOA__C = A.HC_TIPO_DE_CLIENTE__C OR A.HC_TIPO_DE_CLIENTE__C = 'PF E PJ')
			AND B.HC_Classificacao__c != 'Falecido'
			AND B.HC_Idade__c BETWEEN 18 AND 70
	  ) FILTERED
	
	INNER JOIN CAMPAIGN_SALESFORCE A ON A.ID = FILTERED.CAMPAIGN_ID
	INNER JOIN HC_RELACAO_CLIENTE_PARCEIRO__C_SALESFORCE B ON B.ID = FILTERED.RELACAO_CLIENTE_PARCEIRO_ID
	INNER JOIN CONTACT_SALESFORCE C ON C.ID = FILTERED.CONTACT_ID
	INNER JOIN HC_TITULO__C_SALESFORCE D ON D.ID = FILTERED.TITULO_ID
	WHERE FILTERED.NUMBER_OF_CPF_REPETITION = 1
) BASE