select
 EX.DDD1,
 EX.TELEFONE1,
 EX.TIPO1,
 EX.DDD2,
 EX.TELEFONE2,
 EX.TIPO2,
 EX.DDD3,
 EX.TELEFONE3,
 EX.TIPO3,
 EX.DDD4,
 EX.TELEFONE4,
 EX.TIPO4,
 EX.DDD5,
 EX.TELEFONE5,
 EX.TIPO5,
 EX.PREFERENCIAL,
 EX.IDADE,
 EX.DATA_NASCIMENTO,
 EX.NOME_CLIENTE,
 EX.CEP,
 EX.UF,
 EX.TIPO_DE_PESSOA,
 EX.CPF_CNPJ,
 EX.SEXO,
 EX.CLASSIFICAÇAO,
 EX.TIPO_CAMPANHA,
 EX.IDCAMPANHA,
 REL.ID AS IDCP,
 CON.ID AS IDCONTATOS,
 EX.DATA_CRIAÇÃO,
 EX.DATA_UTILIZAÇÃO,
 EX.DATA_TERMINO
from [Tb_Base_Prospect_Online_Extracao_ComOTC_NeoBpo_Pub1_copy] EX
LEFT JOIN (
  select
    EX.CPF_CNPJ as CPF,
    CON.ID
  FROM Tb_Base_Prospect_Online_Extracao_ComOTC_NeoBpo_Pub1_copy EX
  INNER JOIN [CONTACT_SALESFORCE] CON ON CON.HC_CPF_CNPJ_Tipo_de_Relacionamento__c = CONCAT(EX.CPF_CNPJ, 'CLIENTE')
) CON ON EX.CPF_CNPJ = CON.CPF
LEFT JOIN [HC_Relacao_Cliente_Parceiro__c_Salesforce] REL ON CONCAT(EX.CPF_CNPJ, '52') = REL.HC_CPF_CNPJ_Codigo_Parceiro_Unico__c