SELECT
  BASE.*
FROM (
  SELECT
    RCP.HC_CPF_CNPJ__c as CPF,
    SELECTED.CAMPAIGNID AS ID_CAMPANHA,
    SELECTED.CLIENTEPARCEIROID AS ID_CLIENTE_PARCEIRO,
    SELECTED.CONTACTID AS ID_CONTATO,
    SELECTED.TITULOID AS ID_TITULO,
    SELECTED.PAGAMENTOID AS ID_PAGAMENTO,
    RCP.HC_Nome_Parceiro__c as Parceiro,
    HC_TIPO_DE_PESSOA__C as TIPO_DE_PESSOA,
    CASE
      WHEN RCP.HC_EMAIL_PRINCIPAL__C = 'Brasilcap' THEN HC_EMAIL_BRASILCAP__C
      WHEN RCP.HC_EMAIL_PRINCIPAL__C = 'Comercial' THEN HC_EMAIL_COMERCIAL__C
      WHEN RCP.HC_EMAIL_PRINCIPAL__C = 'Pessoal' THEN HC_EMAIL_PESSOAL__C
      WHEN RCP.HC_EMAIL_BRASILCAP__C IS NOT NULL THEN HC_EMAIL_BRASILCAP__C
      WHEN RCP.HC_EMAIL_COMERCIAL__C IS NOT NULL THEN HC_EMAIL_COMERCIAL__C
      WHEN RCP.HC_EMAIL_PESSOAL__C IS NOT NULL THEN HC_EMAIL_PESSOAL__C
      ELSE NULL
    END AS EMAIL,
    CASE
      WHEN RCP.HC_EMAIL_PRINCIPAL__C IN ('Brasilcap', 'Comercial', 'Pessoal') THEN 1
      WHEN RCP.HC_EMAIL_BRASILCAP__C IS NOT NULL THEN 1
      WHEN RCP.HC_EMAIL_COMERCIAL__C IS NOT NULL THEN 1
      WHEN RCP.HC_EMAIL_PESSOAL__C IS NOT NULL THEN 1
      ELSE 0
    END AS EMAIL_VALIDO,
    CASE
      WHEN RCP.HC_TELEFONE_PRINCIPAL__C = 'Celular 1' THEN RCP.HC_CELULAR_1__C
      WHEN RCP.HC_TELEFONE_PRINCIPAL__C = 'Celular 2' THEN RCP.HC_CELULAR_2__C
      WHEN RCP.HC_TELEFONE_PRINCIPAL__C = 'Celular 3' THEN RCP.HC_CELULAR_3__C
      WHEN RCP.HC_TELEFONE_PRINCIPAL__C = 'Celular 3_3' THEN RCP.HC_CELULAR_3_3__C
      WHEN RCP.HC_TELEFONE_PRINCIPAL__C = 'Celular 4' THEN RCP.HC_CELULAR_4__C
      WHEN RCP.HC_STATUS_CELULAR_1__C IS NOT NULL THEN RCP.HC_CELULAR_1__C
      WHEN RCP.HC_STATUS_CELULAR_2__C IS NOT NULL THEN RCP.HC_CELULAR_2__C
      WHEN RCP.HC_STATUS_CELULAR_3__C IS NOT NULL THEN RCP.HC_CELULAR_3__C
      WHEN RCP.HC_STATUS_CELULAR_3_3__C IS NOT NULL THEN RCP.HC_CELULAR_3_3__C
      WHEN RCP.HC_STATUS_CELULAR_4__C IS NOT NULL THEN RCP.HC_CELULAR_4__C
      ELSE NULL
    END AS CELULAR,
    CASE
      WHEN RCP.HC_STATUS_CELULAR_1__C = 'VÁLIDO' THEN 1
      WHEN RCP.HC_STATUS_CELULAR_2__C = 'VÁLIDO' THEN 1
      WHEN RCP.HC_STATUS_CELULAR_3__C = 'VÁLIDO' THEN 1
      WHEN RCP.HC_STATUS_CELULAR_3_3__C = 'VÁLIDO' THEN 1
      WHEN RCP.HC_STATUS_CELULAR_4__C = 'VÁLIDO' THEN 1
      ELSE 0
    END AS CELULAR_VALIDO,
    GETDATE() + 1 AS DATA_EXECUCAO,
    PAG.HC_Valor_Liquido__c AS Valor_Liquido,
    /* PAG.HC_Data_do_pagamento__c,
    PAG.HC_Data_Envio_Registro__c, */
    'PT-BR' AS LOCALE,
    case
      WHEN RCP.HC_chaveParceiro__c = '52' AND RCP.HC_Tipo_de_Pessoa__c = 'PF' then 'PF OUROCAP'
      WHEN RCP.HC_chaveParceiro__c = '52' AND RCP.HC_Tipo_de_Pessoa__c = 'PJ' then 'PJ OUROCAP'
      ELSE 'CAP FIADOR'
    END AS CAMPAIGN_GROUP,
    /* evitar repetição de CPFs por campanha */
		ROW_NUMBER() OVER(PARTITION BY CMP.ID ORDER BY RCP.HC_CPF_CNPJ__C ASC) AS ROWNO
  FROM (
    SELECT
      A.ID as CAMPAIGNID,
      B.ID AS CLIENTEPARCEIROID,
      C.ID AS CONTACTID,
      D.ID AS TITULOID,
      PAG.ID AS PAGAMENTOID,
      row_number() over (PARTITION BY B.ID, D.ID ORDER BY B.ID) AS NUMBER_OF_CPF_REPETITION
    FROM CAMPAIGN_SALESFORCE A
    INNER JOIN HC_RELACAO_CLIENTE_PARCEIRO__C_SALESFORCE B ON 1 = 1
    INNER JOIN CONTACT_SALESFORCE C ON C.HC_CPF_CNPJ__C = B.HC_CPF_CNPJ__C
    INNER JOIN HC_TITULO__C_SALESFORCE D ON D.HC_CLIENTE_X_PARCEIRO__C = B.ID
    INNER JOIN [HC_PAGAMENTO__C_SALESFORCE] PAG ON D.ID = PAG.HC_TITULO__C
    LEFT JOIN [HISTORICO_QUEDAS] HQ ON HQ.ID_PAGAMENTO = PAG.ID
    WHERE 
      A.ISACTIVE = 1
      AND A.PARENTID = '7016g000000NkagAAC'
        /* Não repetição de comunicação para (pagamento) queda já comunicada */
      AND HQ.ID_PAGAMENTO IS NULL
        /* Data de Execução
      AND CONVERT(VARCHAR(10), A.HC_DATA_DE_EXECUCAO__C, 101) = CONVERT(VARCHAR(10), GETDATE(), 101)
      AND DATEPART(HH, A.HC_DATA_DE_EXECUCAO__C) = DATEPART(HH, GETDATE())
        Tipo de cliente controlado pelo registro da campanha no service */
      AND (B.HC_TIPO_DE_PESSOA__C = A.HC_TIPO_DE_CLIENTE__C OR (A.HC_TIPO_DE_CLIENTE__C = 'PF E PJ' ))
        /* Tipos de pagamento */
      AND (PAG.HC_STATUS_DO_PAGAMENTO__C = 'QUEDA' OR PAG.HC_STATUS_DO_PAGAMENTO__C = 'QUEDA DE PRÉVIA')
        /* PARCEIROS VALIDOS */
      AND (
        B.HC_PARCEIRO__C = A.HC_PARCEIRO__C
        OR (
          A.HC_PARCEIRO__C IS NULL
          AND B.HC_ID_PARCEIRO_CAP__C IN ( 
              'VFREI', 'VILAN', 'ACOST', 'ALLEN', 'AMPL', 'ATIVA', 'CCB', 'INTEG', 'JACY', 'KMUL', 'LB ', 'LOCAL', 'MAFRA', 'MCFIL', 
              'METOD', 'METW', 'MILAN', 'MKCOR', 'NSI', 'TOTUM', 'PRIMA', 'REINO', 'SEGES', 'CONC', 'ELEG', 'GARDI',
              'TRAMP', 'ANAP', 'BARAU', 'JACAR', 'MARKF', 'MARTI', 'MGC', 'MONTP', 'NETI', 'TDA', 'PBCOR', 'PLAN', 'QUEIR', 'R E R', 'ROSI', 
              'SAN', 'SAURA', 'SEGNA', 'CONE', 'GAST', 'GOLF', 'HRD', 'UNIGE', 'VALLI', 'VLVE', 'VPSCG', 'WALT', 'ACOS', 'AFIRM', 'AYUMI', 'BCK', 
              'BGS', 'CIPA', 'JSEG', 'MAC', 'NFEAB', 'NTCOR', 'TKS', 'O2COR', 'PLANE', 'SOUTH', 'DNA', 'DOSC', 'EXPER', 'FEDCO', 'G100', 'GRANL', 'WCSI', '5 S',
              'AGZ', 'AMAD', 'APSA', 'BLINK', 'BORE', 'BRINS', 'CARME', 'CENER', 'IMOBI', 'MITRA', 'MONIT', 'MPAG', 'NARUD', 'THOMA', 'PROTE', 'PROVE', 'RPOTY', 
              'RRCOR', 'SFCON', 'SIEL', 'SIGMA', 'CODE', 'DACEL', 'GEBR', 'GOBAT', 'GOLDE', 'VARIA', 'VRCOR', 'WJF', '100AL', 'ACDP', 'ACORE', 'CAMBI', 'CANAD', 
              'CCENT', 'CENTR', 'INOVE', 'JOR', 'MANDE', 'MBAC', 'ORBIX', 'PLANJ', 'RENOM', 'ROADS', 'RVERD', 'SCAP', 'SICAR', 'CONF', 'DRESD', 'EGD', 'EXATA', 
              'FIANS', 'GLOBA', 'TRIUN', 'VPSD', 'YOUSG', 'AJSOU', 'ANJOS', 'BCAP', 'BUSIN', 'CALEG', 'CAMIL', 'CDAV', 'JBI', 'JRF', 'MAX', 'MAXC', 'MONRA', 'TCBC', 
              'POLLO', 'REIS', 'SANTA', 'SUCCE', 'CONQU', 'GOLDP', 'UNIC', 'VIEIR', 'VPS', 'VPSDR', 'BASSO', 'BSB', 'JARS', 'JPF', 'LMAT', 'MAIOR', 'MAREC', 'MAXI', 
              'MAXIM', 'MCLA', 'NELOR', 'NOIVA', 'TJVAL', 'ONIX', 'ORGAB', 'PALAV', 'PCAMP', 'PLUS', 'PMG', 'RIOT', 'RIVER', 'ROCHA', 'SECO', 'SEGUR', 'SID', 'SINAC', 
              'SLTLK', 'TAS', 'CONST', 'FAAR', 'GEMP', 'HAMUR', 'HERMA', '100AG', 'ALIKA', 'ALUG', 'CLASP', 'NPIME', 'TOLED', 'RAOS', 'SAMAR', 'SCHAA', 'SEGF', 'SPASI', 
              'STERS', 'DIRET', 'DLEGE', 'EKO', 'EKOBE', 'FERRE', 'GRCAP', 'HASHI', 'HCAM'
          )
        )
      )
      /* -------- PARAMETROS ESPECIFICOS DA CAMPANHA DE RECOMANDO -------- */
      /* RANGE DATA */
      AND (
        (PAG.HC_Data_Envio_Registro__c >= A.HC_DATA_INICIAL_DO_PERIODO_DE_QUEDA__C OR A.HC_DATA_INICIAL_DO_PERIODO_DE_QUEDA__C IS NULL)
        AND (PAG.HC_Data_Envio_Registro__c <= A.HC_DATA_FIM_DO_PERIODO_DE_QUEDA__C OR A.HC_DATA_FIM_DO_PERIODO_DE_QUEDA__C IS NULL)
      )
      /* RANGE VALOR */
      AND (
        (PAG.HC_VALOR_LIQUIDO__C >= A.HC_VALOR_MINIMO_A_PAGAR__C OR A.HC_VALOR_MINIMO_A_PAGAR__C IS NULL)
        AND (PAG.HC_VALOR_LIQUIDO__C <= A.HC_VALOR_MAXIMO_A_PAGAR__C OR A.HC_VALOR_MAXIMO_A_PAGAR__C IS NULL)
      )
      AND (
        /* Ter e-mail valido */
        (  B.HC_EMAIL_BRASILCAP__C IS NOT NULL OR B.HC_EMAIL_COMERCIAL__C IS NOT NULL OR B.HC_EMAIL_PESSOAL__C IS NOT NULL )
        /* ou celular valido */
        OR ( B.HC_STATUS_CELULAR_1__C = 'VÁLIDO' OR B.HC_STATUS_CELULAR_2__C = 'VÁLIDO' OR B.HC_STATUS_CELULAR_3__C = 'VÁLIDO' 
          OR B.HC_STATUS_CELULAR_3_3__C = 'VÁLIDO' OR B.HC_STATUS_CELULAR_4__C = 'VÁLIDO' )
      )
    ) SELECTED
  INNER JOIN [HC_RELACAO_CLIENTE_PARCEIRO__C_SALESFORCE] RCP ON SELECTED.CLIENTEPARCEIROID = RCP.ID
  INNER JOIN CAMPAIGN_SALESFORCE CMP ON SELECTED.CAMPAIGNID = CMP.ID
  INNER JOIN [HC_TITULO__C_SALESFORCE] TIT ON SELECTED.TITULOID = TIT.ID
  INNER JOIN [HC_Pagamento__c_Salesforce] PAG ON SELECTED.PAGAMENTOID = PAG.ID
  WHERE SELECTED.NUMBER_OF_CPF_REPETITION = 1
) BASE
INNER JOIN
  CAMPAIGN_SALESFORCE CAMP
  ON BASE.ID_CAMPANHA = CAMP.ID
WHERE
	CAMP.HC_QUANTIDADE_DE_CONTATOS_NO_MAILING__C IS NULL
	OR BASE.ROWNO <= (CAMP.HC_QUANTIDADE_DE_CONTATOS_NO_MAILING__C)