SELECT
	A.CPF,
	A.ID_TITULO,
	1 AS NAO_IMPORTUNE
FROM TB_PRE_SORTEIO A
INNER JOIN TB_BASE_NAO_IMPORTUNE N ON ISNULL(RIGHT(a.CELULAR, 11), '00000000000') = LTRIM(RTRIM(N.TELEFONE))
INNER JOIN CAMPAIGN_SALESFORCE CMP ON CMP.ID = A.ID_CAMPANHA
WHERE CELULAR != NULL AND CMP.HC_VALIDA_NAO_IMPORTUNE__C = 1