SELECT DISTINCT 
  CPF_CNPJ,
  COMPRA_UTIMOS_30_DIAS,
  POSSUI_TITULO_ATIVO,
  NAO_IMPORTUNE,
  ID_campanha
FROM Tb_Base_Ex_Cliente_ComOTC_TMKT
WHERE
  /* IDADE_VALIDA = 1 */
  /* AND CONSELHEIRO = 0 */
  /* AND CLIENTE_PEP = 0 */
  /* AND DESEJA_CONTATO_TELEFONICO = 0 */
  /* AND POSSUI_TELEFONE_ATIVO = 1 */
  /* AND POSSUI_CONTA_CORRENTE = 1 */
  COMPRA_UTIMOS_30_DIAS = 1
  or POSSUI_TITULO_ATIVO = 1
  /* AND QUARENTENA = 0 */
  or NAO_IMPORTUNE = 1
  or CONTA_APTA = 0