SELECT
  *
FROM
  TB_BASE_FIM_PLANO_OUROCAP_PU_PP_COMOTC_NEOBPO 
WHERE
  IDADE_VALIDA = 1 
  AND CONSELHEIRO = 0 
  AND CLIENTE_PEP = 0 
  AND DESEJA_CONTATO_TELEFONICO = 0 
  AND COMPRA_RECENTE_OUROCAP = 0 
  AND POSSUI_CONTA_ATIVA = 1
  AND POSSUI_TELEFONE_ATIVO = 1
  AND QUARENTENA = 0
  AND NAO_IMPORTUNE = 0