SELECT
  A.*
FROM Tb_Base_Ex_Cliente_OTC291_Tratada_Algar A
  /* CHECAGEM SE TOODS OS CONTATOS TIVERAM O OTC TRATADO */
LEFT OUTER JOIN ( 
  SELECT
    COUNT(1) as CPFS_FALTANDO_NO_OTC
  FROM Tb_Base_Ex_Cliente_ComOTC_Algar_Filtrada ENV
  LEFT JOIN Tb_Base_Ex_Cliente_OTC291_Tratada_Algar RET ON ENV.CPF_CNPJ = RET.CPF
  WHERE RET.CPF IS NULL
) B ON 1 = 1
WHERE A.CODIGO_RNA = '000'
  AND A.ALTA_RENDA = 0