SELECT DISTINCT
  'TCBB' AS COD_PARCEIRO,
  A.CPF,
  '' AS CNPJ,
  B.CEP
FROM
  TB_BASE_PROSPECT_OTC291_FILTRADA_TEO A 
  INNER JOIN
    TB_BASE_PROSPECT_COMOTC_TRATADA_TEO B 
    ON A.CPF = RIGHT(REPLICATE ('0' , 15)+CONVERT(VARCHAR, B.CPF), 11)
    INNER JOIN HC_Relacao_Cliente_Parceiro__c_Salesforce C ON A.CPF = C.CPF_CNPJ_Cliente__c