SELECT
  B.CPF AS CPF_CNPJ,
  CMP.NAME AS CAMPANHA,
  B.COMPRA_UTIMOS_30_DIAS AS COMPROU_ULTIMOS_30_DIAS,
  B.POSSUI_TITULO_ATIVO,
  B.QUARENTENA,
  CASE
    WHEN B.COMPRA_UTIMOS_30_DIAS IS NULL OR B.COMPRA_UTIMOS_30_DIAS = 1 THEN 'NÃO COMPROU NOS ULTIMOS 30 DIAS'
    WHEN B.POSSUI_TITULO_ATIVO IS NULL OR B.POSSUI_TITULO_ATIVO = 0 THEN 'NÃO POSSUI TITULO ATIVO'
    WHEN B.QUARENTENA IS NULL OR B.QUARENTENA = 1 THEN 'EM QUARENTENA' 
  END AS RESULTADO,
  CASE
    WHEN Q.CPF_CNPJ IS NULL THEN NULL
    WHEN B.COMPRA_UTIMOS_30_DIAS IS NULL OR B.COMPRA_UTIMOS_30_DIAS = 1 THEN NULL
    WHEN B.POSSUI_TITULO_ATIVO IS NULL OR B.POSSUI_TITULO_ATIVO = 0 THEN NULL
    WHEN B.NAO_IMPORTUNE IS NULL OR B.NAO_IMPORTUNE = 0 THEN NULL
    WHEN B.QUARENTENA IS NULL OR B.QUARENTENA = 1 THEN CONCAT(
      RIGHT( CONCAT('0', DATEPART(DD, Data_Participacao_Campanha)) , 2),
      '/',
      RIGHT( CONCAT('0', DATEPART(MM, Data_Participacao_Campanha)) , 2),
      '/',
      DATEPART(YYYY, Data_Participacao_Campanha)
    )
  END AS data_quarentena
FROM
  Publico_Inapto_Clientes_NeoBpo_Prospect B
LEFT JOIN CAMPAIGN_SALESFORCE CMP ON B.ID_CAMPANHA = CMP.ID
LEFT JOIN TB_BASE_QUARENTENA Q ON Q.CPF_CNPJ = B.CPF