SELECT 
	B.CPF_CNPJ,
	B.NUMERO_DO_TITULO,
	T.HC_NUMERO_DA_SORTE__C AS NUMERO_DA_SORTE,
	T.HC_VALOR_DA_PARCELA__C AS VALOR_DA_PARCELA__C,
	T.HC_TERMINO_CARENCIA__C AS TERMINO_CARENCIA,
	T.HC_FIM_PREVISTO__C AS INICIO_DA_VIGENCIA
FROM TB_BOAS_VINDAS_POSTALCAP_COMOTC_FILTRADA B
INNER JOIN HC_TITULO__C_SALESFORCE T WITH (NOLOCK) ON B.CPF_CNPJ = T.HC_CPF_CNPJ_Titular__c AND B.NUMERO_DO_TITULO = T.HC_NUMERO_DO_TITULO__C