SELECT
Id_Cliente_Parceiro,
TITULOS_ANTERIORES_INATIVOS,
TITULOS_ANTERIORES_ATIVOS,
Id_Contato,
EMAIL,
NAO_DESEJA_RECEBER_SMS,
CPF_CNPJ,
EMAIL_VALIDO,
Flag_WhatsApp,
Nome,
NAO_DESEJA_RECEBER_EMAIL,
locale,
Id_Campanha,
CreatedDate,
CELULAR_VALIDO,
'55' + REPLACE(REPLACE(REPLACE(REPLACE(CELULAR, '(', ''), ')', ''), ' ', ''), '-', '') AS CELULAR
FROM AeM_Boas_Vindas_Disparo
WHERE CELULAR IS NOT NULL AND CELULAR NOT LIKE '55%'