
SELECT DISTINCT
GmailD2S2.CPF,
GmailD2S2.NOME,
GmailD2S2.EMAIL,
GmailD2S2.EMAIL_VALIDO,
CASE

  WHEN CHARINDEX(' ', GmailD2S2.NOME) = 0 THEN GmailD2S2.NOME

  ELSE SUBSTRING( GmailD2S2.NOME , 1, CHARINDEX(' ', GmailD2S2.NOME) )

END AS PNOME
FROM Gmail_DIV02_SUB02 GmailD2S2
UNION
SELECT DISTINCT
MicrosodftD2S2.CPF,
MicrosodftD2S2.NOME,
MicrosodftD2S2.EMAIL,
MicrosodftD2S2.EMAIL_VALIDO,
CASE

  WHEN CHARINDEX(' ', MicrosodftD2S2.NOME) = 0 THEN MicrosodftD2S2.NOME

  ELSE SUBSTRING( MicrosodftD2S2.NOME , 1, CHARINDEX(' ', MicrosodftD2S2.NOME) )

END AS PNOME
FROM Microsoft_DIV02_SUB02 MicrosodftD2S2
UNION
SELECT DISTINCT
YahooD2S2.CPF,
YahooD2S2.NOME,
YahooD2S2.EMAIL,
YahooD2S2.EMAIL_VALIDO,
CASE

  WHEN CHARINDEX(' ', YahooD2S2.NOME) = 0 THEN YahooD2S2.NOME

  ELSE SUBSTRING( YahooD2S2.NOME , 1, CHARINDEX(' ', YahooD2S2.NOME) )

END AS PNOME
FROM Yahoo_DIV02_SUB02 YahooD2S2
UNION
SELECT DISTINCT
OutrosD2S2.CPF,
OutrosD2S2.NOME,
OutrosD2S2.EMAIL,
OutrosD2S2.EMAIL_VALIDO,
CASE

  WHEN CHARINDEX(' ', OutrosD2S2.NOME) = 0 THEN OutrosD2S2.NOME

  ELSE SUBSTRING( OutrosD2S2.NOME , 1, CHARINDEX(' ', OutrosD2S2.NOME) )

END AS PNOME
FROM Outros_DIV02_SUB02 OutrosD2S2
