
SELECT DISTINCT
GmailD1S3.CPF,
GmailD1S3.NOME,
GmailD1S3.EMAIL,
GmailD1S3.EMAIL_VALIDO,
CASE

  WHEN CHARINDEX(' ', GmailD1S3.NOME) = 0 THEN GmailD1S3.NOME

  ELSE SUBSTRING( GmailD1S3.NOME , 1, CHARINDEX(' ', GmailD1S3.NOME) )

END AS PNOME
FROM Gmail_DIV01_SUB03 GmailD1S3
UNION
SELECT DISTINCT
MicrosodftD1S3.CPF,
MicrosodftD1S3.NOME,
MicrosodftD1S3.EMAIL,
MicrosodftD1S3.EMAIL_VALIDO,
CASE

  WHEN CHARINDEX(' ', MicrosodftD1S3.NOME) = 0 THEN MicrosodftD1S3.NOME

  ELSE SUBSTRING( MicrosodftD1S3.NOME , 1, CHARINDEX(' ', MicrosodftD1S3.NOME) )

END AS PNOME
FROM Microsoft_DIV01_SUB03 MicrosodftD1S3
UNION
SELECT DISTINCT
YahooD1S3.CPF,
YahooD1S3.NOME,
YahooD1S3.EMAIL,
YahooD1S3.EMAIL_VALIDO,
CASE

  WHEN CHARINDEX(' ', YahooD1S3.NOME) = 0 THEN YahooD1S3.NOME

  ELSE SUBSTRING( YahooD1S3.NOME , 1, CHARINDEX(' ', YahooD1S3.NOME) )

END AS PNOME
FROM Yahoo_DIV01_SUB03 YahooD1S3
UNION
SELECT DISTINCT
OutrosD1S3.CPF,
OutrosD1S3.NOME,
OutrosD1S3.EMAIL,
OutrosD1S3.EMAIL_VALIDO,
CASE

  WHEN CHARINDEX(' ', OutrosD1S3.NOME) = 0 THEN OutrosD1S3.NOME

  ELSE SUBSTRING( OutrosD1S3.NOME , 1, CHARINDEX(' ', OutrosD1S3.NOME) )

END AS PNOME
FROM Outros_DIV01_SUB03 OutrosD1S3
