SELECT
  CPF_CNPJ,
  MAX(CAMPANHA) AS CAMPANHA,
  MAX(DATA_CAMPANHA) AS DATA_PARTICIPACAO_CAMPANHA
FROM (
  SELECT
    CPF AS CPF_CNPJ,
    'PROSPECT' AS CAMPANHA,
    DATA_CAMPANHA
  FROM
    TB_CAMPANHAS_PROSPECT_HISTORICO
  WHERE DATA_CAMPANHA BETWEEN DATEADD(HH, DATEDIFF(HH, 0, GETDATE()) - 1, 0)
    AND DATEADD(HH, DATEDIFF(HH, 0, GETDATE()), 0)

    UNION ALL

  SELECT
    CPF AS CPF_CNPJ,
    'CLIENTE' AS CAMPANHA,
    DATA_CAMPANHA
  FROM
    TB_CAMPANHAS_CLIENTE_HISTORICO
  WHERE DATA_CAMPANHA BETWEEN DATEADD(HH, DATEDIFF(HH, 0, GETDATE()) - 1, 0)
    AND DATEADD(HH, DATEDIFF(HH, 0, GETDATE()), 0)

    UNION ALL

  SELECT
    CPF AS CPF_CNPJ,
    'EX-CLIENTE' AS CAMPANHA,
    DATA_CAMPANHA
  FROM
    TB_CAMPANHAS_EXCLIENTE_HISTORICO
  WHERE DATA_CAMPANHA BETWEEN DATEADD(HH, DATEDIFF(HH, 0, GETDATE()) - 1, 0)
    AND DATEADD(HH, DATEDIFF(HH, 0, GETDATE()), 0)
) S
GROUP BY S.CPF_CNPJ