SELECT
  D.HC_SITUACAO__C AS HC_SITUACAO__C,
  b.HC_CPF_CNPJ__C,
  HC_IDADE__C,
  b.HC_PARCEIRO__C,
  b.ID as ID_CLIENTE_PARCEIRO,
  a.id as ID_CAMPANHA,
  c.id as ID_CONTATO,
  D.ID AS ID_TITULO,
  b.HC_CLIENTE__C as ID_CLIENTE,
  HC_ORIGEM_DA_VENDA__C,
  HC_EXCLUSAO_DE_COMPRA_RECENTE__C,
  HC_QUARENTENA__C,
  HC_FAMILIA_DO_PRODUTO__C,
  E.ID as ID_PRODUTO,
  HC_BANCO_1__C,
  HC_AGENCIA_1__c,
  HC_NUMERO_DA_CONTA_1__c,
  HC_BANCO_2__C,
  HC_AGENCIA_2__c,
  HC_NUMERO_DA_CONTA_2__c,
  HC_VALOR_DA_PARCELA__C,
  HC_VALOR_MINIMO_DE_PARCELA__C,
  HC_VALOR_MAXIMO_DA_PARCELA__C,
  HC_DATA_DO_ULTIMO_RESGATE__C,
  HC_DATA_INICIAL_DO_PERIODO_DE_RESGATE__C,
  HC_DATA_FIM_DO_PERIODO_DE_RESGATE__C,
  HC_NAO_DESEJA_RECEBER_LIGACOES__C,
  HC_ID_PARCEIRO_CAP__C,
  HC_CONSELHEIRO__C,
  HC_PEP__C,
  HC_CONTRATACAO__C,
	REPLACE(REPLACE(REPLACE(REPLACE(B.HC_TELEFONE_RESIDENCIAL__C, '(', ''), ')', ''), ' ', ''), '-', '') AS TEL_01,
	REPLACE(REPLACE(REPLACE(REPLACE(B.HC_TELEFONE_COMERCIAL__C, '(', ''), ')', ''), ' ', ''), '-', '') AS TEL_02,
	REPLACE(REPLACE(REPLACE(REPLACE(B.HC_TELEFONE_OUTRO__C, '(', ''), ')', ''), ' ', ''), '-', '') AS TEL_03,
	REPLACE(REPLACE(REPLACE(REPLACE(B.HC_CELULAR_1__C, '(', ''), ')', ''), ' ', ''), '-', '') AS TEL_04,
	REPLACE(REPLACE(REPLACE(REPLACE(B.HC_CELULAR_2__C, '(', ''), ')', ''), ' ', ''), '-', '') AS TEL_05,
	REPLACE(REPLACE(REPLACE(REPLACE(B.HC_CELULAR_3__C, '(', ''), ')', ''), ' ', ''), '-', '') AS TEL_06,
	B.HC_TIPO_DE_PESSOA__C AS HC_TIPO_DE_PESSOA__C
FROM CAMPAIGN_SALESFORCE A
INNER JOIN HC_RELACAO_CLIENTE_PARCEIRO__C_SALESFORCE B ON A.HC_PARCEIRO__C = B.HC_PARCEIRO__C
                                                        AND A.HC_TIPO_DE_CLIENTE__C = B.HC_TIPO_DE_PESSOA__C
INNER JOIN CONTACT_SALESFORCE C ON C.HC_CPF_CNPJ__C = B.HC_CPF_CNPJ__C
INNER JOIN HC_TITULO__C_SALESFORCE D ON D.HC_CLIENTE_X_PARCEIRO__C = B.ID
LEFT JOIN HC_PRODUTO__C_SALESFORCE E ON D.HC_PRODUTORELACIONADO__C = E.ID
WHERE
    UPPER(A.[TYPE]) = 'AUTOMÁTICO'
AND UPPER(B.HC_CLASSIFICACAO__C) = 'CLIENTE'
AND B.HC_TIPO_DE_PESSOA__C = 'PF'
AND UPPER(A.HC_FORNECEDOR__C) = 'NEOBPO'
AND UPPER(A.HC_FORMATO__C) = 'ONLINE'
AND A.HC_VALIDA_RNA__C = 1
AND A.PARENTID = '7016g000002Nz5pAAC'
AND A.ISACTIVE = 1
AND A.HC_CAMPANHA_EXECUTADA_NO_MKT__C = 0

and HC_DATA_DO_ULTIMO_RESGATE__C between HC_DATA_INICIAL_DO_PERIODO_DE_RESGATE__C and HC_DATA_FIM_DO_PERIODO_DE_RESGATE__C
and HC_SITUACAO__C = 'FINALIZADO - RESGATE PAGO'