SELECT
  CPF,
  MAX(ID_CAMPANHA) AS ID_CAMPANHA,
  GETDATE() AS DATA_CAMPANHA,
  'RECOMANDO' AS CANAL
FROM (
  SELECT
    HC_CPF_CNPJ__c  AS CPF,
    IdCampaign AS ID_CAMPANHA
  FROM RECOMANDO_G3_DEMAIS_CAPs_v2

  UNION ALL

  SELECT
    HC_CPF_CNPJ__c  AS CPF,
    IdCampaign AS ID_CAMPANHA
  FROM RECOMANDO_G2_TCBB_PJ_v2

  UNION ALL

  SELECT
    HC_CPF_CNPJ__c AS CPF,
    IdCampaign AS ID_CAMPANHA
  FROM RECOMANDO_G1_TCBB_PF_v2
) Q
GROUP BY Q.CPF