
SELECT DISTINCT
GmailD3S1.CPF,
GmailD3S1.NOME,
GmailD3S1.EMAIL,
GmailD3S1.EMAIL_VALIDO,
CASE

  WHEN CHARINDEX(' ', GmailD3S1.NOME) = 0 THEN GmailD3S1.NOME

  ELSE SUBSTRING( GmailD3S1.NOME , 1, CHARINDEX(' ', GmailD3S1.NOME) )

END AS PNOME
FROM Gmail_DIV03_SUB01 GmailD3S1
UNION
SELECT DISTINCT
MicrosodftD3S1.CPF,
MicrosodftD3S1.NOME,
MicrosodftD3S1.EMAIL,
MicrosodftD3S1.EMAIL_VALIDO,
CASE

  WHEN CHARINDEX(' ', MicrosodftD3S1.NOME) = 0 THEN MicrosodftD3S1.NOME

  ELSE SUBSTRING( MicrosodftD3S1.NOME , 1, CHARINDEX(' ', MicrosodftD3S1.NOME) )

END AS PNOME
FROM Microsoft_DIV03_SUB01 MicrosodftD3S1
UNION
SELECT DISTINCT
YahooD3S1.CPF,
YahooD3S1.NOME,
YahooD3S1.EMAIL,
YahooD3S1.EMAIL_VALIDO,
CASE

  WHEN CHARINDEX(' ', YahooD3S1.NOME) = 0 THEN YahooD3S1.NOME

  ELSE SUBSTRING( YahooD3S1.NOME , 1, CHARINDEX(' ', YahooD3S1.NOME) )

END AS PNOME
FROM Yahoo_DIV03_SUB01 YahooD3S1
UNION
SELECT DISTINCT
OutrosD3S1.CPF,
OutrosD3S1.NOME,
OutrosD3S1.EMAIL,
OutrosD3S1.EMAIL_VALIDO,
CASE

  WHEN CHARINDEX(' ', OutrosD3S1.NOME) = 0 THEN OutrosD3S1.NOME

  ELSE SUBSTRING( OutrosD3S1.NOME , 1, CHARINDEX(' ', OutrosD3S1.NOME) )

END AS PNOME
FROM Outros_DIV03_SUB01 OutrosD3S1
