SELECT TOP 50000
*
FROM
  TB_BASE_CLIENTE_COMOTC_NEOBPO 
WHERE
  IDADE_VALIDA = 1 
  AND CONSELHEIRO = 0 
  AND CLIENTE_PEP = 0 
  AND DESEJA_CONTATO_TELEFONICO = 0 
  AND POSSUI_TELEFONE_ATIVO = 1 
  AND POSSUI_CONTA_CORRENTE = 1 
  AND COMPRA_UTIMOS_30_DIAS = 0 
  AND POSSUI_TITULO_ATIVO = 1 
  AND QUARENTENA = 0