
SELECT DISTINCT
GmailD1S4.CPF,
GmailD1S4.NOME,
GmailD1S4.EMAIL,
GmailD1S4.EMAIL_VALIDO,
CASE

  WHEN CHARINDEX(' ', GmailD1S4.NOME) = 0 THEN GmailD1S4.NOME

  ELSE SUBSTRING( GmailD1S4.NOME , 1, CHARINDEX(' ', GmailD1S4.NOME) )

END AS PNOME
FROM Gmail_DIV01_SUB04 GmailD1S4
UNION
SELECT DISTINCT
MicrosodftD1S4.CPF,
MicrosodftD1S4.NOME,
MicrosodftD1S4.EMAIL,
MicrosodftD1S4.EMAIL_VALIDO,
CASE

  WHEN CHARINDEX(' ', MicrosodftD1S4.NOME) = 0 THEN MicrosodftD1S4.NOME

  ELSE SUBSTRING( MicrosodftD1S4.NOME , 1, CHARINDEX(' ', MicrosodftD1S4.NOME) )

END AS PNOME
FROM Microsoft_DIV01_SUB04 MicrosodftD1S4
UNION
SELECT DISTINCT
YahooD1S4.CPF,
YahooD1S4.NOME,
YahooD1S4.EMAIL,
YahooD1S4.EMAIL_VALIDO,
CASE

  WHEN CHARINDEX(' ', YahooD1S4.NOME) = 0 THEN YahooD1S4.NOME

  ELSE SUBSTRING( YahooD1S4.NOME , 1, CHARINDEX(' ', YahooD1S4.NOME) )

END AS PNOME
FROM Yahoo_DIV01_SUB04 YahooD1S4
UNION
SELECT DISTINCT
OutrosD1S4.CPF,
OutrosD1S4.NOME,
OutrosD1S4.EMAIL,
OutrosD1S4.EMAIL_VALIDO,
CASE

  WHEN CHARINDEX(' ', OutrosD1S4.NOME) = 0 THEN OutrosD1S4.NOME

  ELSE SUBSTRING( OutrosD1S4.NOME , 1, CHARINDEX(' ', OutrosD1S4.NOME) )

END AS PNOME
FROM Outros_DIV01_SUB04 OutrosD1S4
