SELECT
	A.CPF_CNPJ AS ID,
	1 AS NAO_IMPORTUNE
FROM TB_BOAS_VINDAS_POSTALCAP_COMOTC_NEOBPO A
INNER JOIN TB_BASE_NAO_IMPORTUNE N ON ISNULL(CONCAT(A.DDD_TEL_01, A.TEL_01), '00000000000') = LTRIM(RTRIM(N.TELEFONE))
UNION
SELECT
	A.CPF_CNPJ AS ID,
	1 AS NAO_IMPORTUNE
FROM TB_BOAS_VINDAS_POSTALCAP_COMOTC_NEOBPO A
INNER JOIN TB_BASE_NAO_IMPORTUNE N ON ISNULL(CONCAT(A.DDD_TEL_02, A.TEL_02), '00000000000') = LTRIM(RTRIM(N.TELEFONE))
UNION
SELECT
	A.CPF_CNPJ AS ID,
	1 AS NAO_IMPORTUNE
FROM TB_BOAS_VINDAS_POSTALCAP_COMOTC_NEOBPO A
INNER JOIN TB_BASE_NAO_IMPORTUNE N ON ISNULL(CONCAT(A.DDD_TEL_03, A.TEL_03), '00000000000') = LTRIM(RTRIM(N.TELEFONE))
UNION
SELECT
	A.CPF_CNPJ AS ID,
	1 AS NAO_IMPORTUNE
FROM TB_BOAS_VINDAS_POSTALCAP_COMOTC_NEOBPO A
INNER JOIN TB_BASE_NAO_IMPORTUNE N ON ISNULL(CONCAT(A.DDD_TEL_04, A.TEL_04), '00000000000') = LTRIM(RTRIM(N.TELEFONE))
UNION
SELECT
	A.CPF_CNPJ AS ID,
	1 AS NAO_IMPORTUNE
FROM TB_BOAS_VINDAS_POSTALCAP_COMOTC_NEOBPO A
INNER JOIN TB_BASE_NAO_IMPORTUNE N ON ISNULL(CONCAT(A.DDD_TEL_05, A.TEL_05), '00000000000') = LTRIM(RTRIM(N.TELEFONE))
UNION
SELECT
	A.CPF_CNPJ AS ID,
	1 AS NAO_IMPORTUNE
FROM TB_BOAS_VINDAS_POSTALCAP_COMOTC_NEOBPO A
INNER JOIN TB_BASE_NAO_IMPORTUNE N ON ISNULL(CONCAT(A.DDD_TEL_06, A.TEL_06), '00000000000') = LTRIM(RTRIM(N.TELEFONE))
