SELECT DISTINCT
		B.HC_CPF_CNPJ__C AS CPF_CNPJ,
		C.NAME AS NOME,
		CASE
			WHEN B.HC_EMAIL_PRINCIPAL__C = 'Brasilcap' THEN HC_EMAIL_BRASILCAP__C
			WHEN B.HC_EMAIL_PRINCIPAL__C = 'Comercial' THEN HC_EMAIL_COMERCIAL__C
			WHEN B.HC_EMAIL_PRINCIPAL__C = 'Pessoal' THEN HC_EMAIL_PESSOAL__C
			WHEN B.HC_EMAIL_BRASILCAP__C IS NOT NULL THEN HC_EMAIL_BRASILCAP__C
			WHEN B.HC_EMAIL_COMERCIAL__C IS NOT NULL THEN HC_EMAIL_COMERCIAL__C
			WHEN B.HC_EMAIL_PESSOAL__C IS NOT NULL THEN HC_EMAIL_PESSOAL__C
			ELSE NULL
		END AS EMAIL,
		CASE
			WHEN B.HC_EMAIL_PRINCIPAL__C IN ('Brasilcap', 'Comercial', 'Pessoal') THEN 1
			WHEN B.HC_EMAIL_BRASILCAP__C IS NOT NULL THEN 1
			WHEN B.HC_EMAIL_COMERCIAL__C IS NOT NULL THEN 1
			WHEN B.HC_EMAIL_PESSOAL__C IS NOT NULL THEN 1
			ELSE 0
		END AS EMAIL_VALIDO,
		B.HC_TIPO_DE_PESSOA__C AS TIPO_PESSOA,
		B.HC_TELEFONE_PRINCIPAL__C AS TEL_PRINCIPAL,
		A.HC_PRODUTO__C AS ID_PRODUTO,
		A.ID AS ID_CAMPANHA, 
		B.ID AS ID_CLIENTE_PARCEIRO,
		C.ID AS ID_CONTATO,
		D.HC_VALOR_DA_PARCELA__C AS VALOR_PARCELA_PRODUTO,
		D.HC_NUMERO_DO_TITULO__C as NUMERO_DO_TITULO,
		D.Id as Id_Titulo,
		D.HC_SERIE__C as SERIE_DO_TITULO,
		D.HC_PLANO__C as PLANO_DO_TITULO,
		D.HC_CONTRATACAO__C AS DATA_CONTRATACAO,
        B.HC_NAO_DESEJA_RECEBER_EMAIL__C AS NAO_DESEJA_RECEBER_EMAIL,
		D.HC_Inicio__c AS DATA_INICIO_VIGENCIA,
		ROW_NUMBER() OVER(ORDER BY B.ID ASC) AS ROWNO
	FROM CAMPAIGN_SALESFORCE A
	INNER JOIN HC_RELACAO_CLIENTE_PARCEIRO__C_SALESFORCE B ON A.HC_PARCEIRO__C = B.HC_PARCEIRO__C
	INNER JOIN CONTACT_SALESFORCE C ON C.HC_CPF_CNPJ__C = B.HC_CPF_CNPJ__C
	INNER JOIN HC_TITULO__C_SALESFORCE D ON D.HC_CLIENTE_X_PARCEIRO__C = B.ID
	WHERE
		(B.HC_TIPO_DE_PESSOA__C = A.HC_TIPO_DE_CLIENTE__C OR A.HC_TIPO_DE_CLIENTE__C = 'PF E PJ')
	AND A.ISACTIVE = 1
	/* ID DA CAMPANHA DE BOAS VINDAS OUROCAP */
	AND A.ID = '7016g000000NhtVAAS'
	AND D.HC_SITUACAO__C = 'ATIVO'
	/* PARCEIRO TCBB PARA OUROCAP */
	AND (D.HC_CODIGO_DO_PARCEIRO_NA_ORIGEM__C = 'TCBB' OR D.HC_CODIGO_DO_PARCEIRO_NA_ORIGEM__C = '1')
	AND B.HC_NAO_DESEJA_RECEBER_TODOS_MEIOS__C = 0
    AND CONVERT(VARCHAR, DATEADD(MONTH, 3, D.HC_Inicio__c), 101) =  CONVERT(VARCHAR, GETDATE(), 101)
	AND (
		/* CUSTOM BETWEEN */
		(A.HC_VALOR_MINIMO_DE_PARCELA__C IS NULL OR D.HC_VALOR_DA_PARCELA__C > A.HC_VALOR_MINIMO_DE_PARCELA__C)
		AND (A.HC_VALOR_MAXIMO_DA_PARCELA__C IS NULL OR D.HC_VALOR_DA_PARCELA__C < A.HC_VALOR_MAXIMO_DA_PARCELA__C)
	)