SELECT *
FROM
  Tb_Base_Prop_Ourocap_N_Pag

WHERE
    IDADE_VALIDA = 1
AND CONSELHEIRO = 0
AND CLIENTE_PEP = 0
AND DESEJA_CONTATO_TELEFONICO = 0
AND POSSUI_TELEFONE_ATIVO = 1
AND POSSUI_CONTA_CORRENTE = 1
AND QUARENTENA = 0
AND INATIVIDADE = 0 
AND NAO_IMPORTUNE = 0