
SELECT DISTINCT
GmailD4S1.CPF,
GmailD4S1.NOME,
GmailD4S1.EMAIL,
GmailD4S1.EMAIL_VALIDO,
CASE

  WHEN CHARINDEX(' ', GmailD4S1.NOME) = 0 THEN GmailD4S1.NOME

  ELSE SUBSTRING( GmailD4S1.NOME , 1, CHARINDEX(' ', GmailD4S1.NOME) )

END AS PNOME
FROM Gmail_DIV04_SUB01 GmailD4S1
UNION
SELECT DISTINCT
MicrosodftD4S1.CPF,
MicrosodftD4S1.NOME,
MicrosodftD4S1.EMAIL,
MicrosodftD4S1.EMAIL_VALIDO,
CASE

  WHEN CHARINDEX(' ', MicrosodftD4S1.NOME) = 0 THEN MicrosodftD4S1.NOME

  ELSE SUBSTRING( MicrosodftD4S1.NOME , 1, CHARINDEX(' ', MicrosodftD4S1.NOME) )

END AS PNOME
FROM Microsoft_DIV04_SUB01 MicrosodftD4S1
UNION
SELECT DISTINCT
YahooD4S1.CPF,
YahooD4S1.NOME,
YahooD4S1.EMAIL,
YahooD4S1.EMAIL_VALIDO,
CASE

  WHEN CHARINDEX(' ', YahooD4S1.NOME) = 0 THEN YahooD4S1.NOME

  ELSE SUBSTRING( YahooD4S1.NOME , 1, CHARINDEX(' ', YahooD4S1.NOME) )

END AS PNOME
FROM Yahoo_DIV04_SUB01 YahooD4S1
UNION
SELECT DISTINCT
OutrosD4S1.CPF,
OutrosD4S1.NOME,
OutrosD4S1.EMAIL,
OutrosD4S1.EMAIL_VALIDO,
CASE

  WHEN CHARINDEX(' ', OutrosD4S1.NOME) = 0 THEN OutrosD4S1.NOME

  ELSE SUBSTRING( OutrosD4S1.NOME , 1, CHARINDEX(' ', OutrosD4S1.NOME) )

END AS PNOME
FROM Outros_DIV04_SUB01 OutrosD4S1
