SELECT DISTINCT
  'TCBB' AS COD_PARCEIRO,
  CPF,
   '' AS CNPJ,
  DDD_01 AS DDD,
  TEL_01 AS TELEFONE
FROM
  TB_BASE_PROSPECT_SEMOTC_FILTRADA_TEO
WHERE
    LEN(TEL_01) >= 8
AND LEN(DDD_01) = 2
UNION ALL
SELECT DISTINCT
  'TCBB' AS COD_PARCEIRO,
  CPF,
   '' AS CNPJ,
  DDD_02 AS DDD,
  TEL_02 AS TELEFONE
FROM
  TB_BASE_PROSPECT_SEMOTC_FILTRADA_TEO
WHERE
    LEN(TEL_02) >= 8
AND LEN(DDD_02) = 2
UNION ALL
SELECT DISTINCT
  'TCBB' AS COD_PARCEIRO,
  CPF,
   '' AS CNPJ,
  DDD_03 AS DDD,
  TEL_03 AS TELEFONE
FROM
  TB_BASE_PROSPECT_SEMOTC_FILTRADA_TEO
WHERE
    LEN(TEL_03) >= 8
AND LEN(DDD_03) = 2
UNION ALL
SELECT DISTINCT
  'TCBB' AS COD_PARCEIRO,
  CPF,
   '' AS CNPJ,
  DDD_04 AS DDD,
  TEL_04 AS TELEFONE
FROM
  TB_BASE_PROSPECT_SEMOTC_FILTRADA_TEO
WHERE
    LEN(TEL_04) >= 8
AND LEN(DDD_04) = 2
UNION ALL
SELECT DISTINCT
  'TCBB' AS COD_PARCEIRO,
  CPF,
   '' AS CNPJ,
  DDD_05 AS DDD,
  TEL_05 AS TELEFONE
FROM
  TB_BASE_PROSPECT_SEMOTC_FILTRADA_TEO
WHERE
    LEN(TEL_05) >= 8
AND LEN(DDD_05) = 2