
SELECT DISTINCT
GmailD2S1.CPF,
GmailD2S1.NOME,
GmailD2S1.EMAIL,
GmailD2S1.EMAIL_VALIDO,
CASE

  WHEN CHARINDEX(' ', GmailD2S1.NOME) = 0 THEN GmailD2S1.NOME

  ELSE SUBSTRING( GmailD2S1.NOME , 1, CHARINDEX(' ', GmailD2S1.NOME) )

END AS PNOME
FROM Gmail_DIV02_SUB01 GmailD2S1
UNION
SELECT DISTINCT
MicrosodftD2S1.CPF,
MicrosodftD2S1.NOME,
MicrosodftD2S1.EMAIL,
MicrosodftD2S1.EMAIL_VALIDO,
CASE

  WHEN CHARINDEX(' ', MicrosodftD2S1.NOME) = 0 THEN MicrosodftD2S1.NOME

  ELSE SUBSTRING( MicrosodftD2S1.NOME , 1, CHARINDEX(' ', MicrosodftD2S1.NOME) )

END AS PNOME
FROM Microsoft_DIV02_SUB01 MicrosodftD2S1
UNION
SELECT DISTINCT
YahooD2S1.CPF,
YahooD2S1.NOME,
YahooD2S1.EMAIL,
YahooD2S1.EMAIL_VALIDO,
CASE

  WHEN CHARINDEX(' ', YahooD2S1.NOME) = 0 THEN YahooD2S1.NOME

  ELSE SUBSTRING( YahooD2S1.NOME , 1, CHARINDEX(' ', YahooD2S1.NOME) )

END AS PNOME
FROM Yahoo_DIV02_SUB01 YahooD2S1
UNION
SELECT DISTINCT
OutrosD2S1.CPF,
OutrosD2S1.NOME,
OutrosD2S1.EMAIL,
OutrosD2S1.EMAIL_VALIDO,
CASE

  WHEN CHARINDEX(' ', OutrosD2S1.NOME) = 0 THEN OutrosD2S1.NOME

  ELSE SUBSTRING( OutrosD2S1.NOME , 1, CHARINDEX(' ', OutrosD2S1.NOME) )

END AS PNOME
FROM Outros_DIV02_SUB01 OutrosD2S1
