SELECT
  SUBSTRING(RETORNO, 1, 3) AS CODIGO_PARCEIRO,
  SUBSTRING(RETORNO, 4, 9) AS ID_CLIENTE,
  SUBSTRING(RETORNO, 13, 9) AS CODIGO_MCI,
  SUBSTRING(RETORNO, 22, 1) AS TIPO_PESSOA,
  SUBSTRING(RETORNO, 23, 15) AS CODIGO_CIC,
  SUBSTRING(RETORNO, 38, 8) AS DT_NASCIMENTO,
  UPPER(SUBSTRING(RETORNO, 46, 60)) AS NOME,
  SUBSTRING(RETORNO, 107, 2) AS UF_RESIDENCIAL,
  SUBSTRING(RETORNO, 109, 4) AS DDD1,
  SUBSTRING(RETORNO, 113, 10) AS TELEFONE1,
  SUBSTRING(RETORNO, 123, 4) AS DDD2,
  SUBSTRING(RETORNO, 127, 10) AS TELEFONE2,
  SUBSTRING(RETORNO, 137, 4) AS DDD3,
  SUBSTRING(RETORNO, 141, 10) AS TELEFONE3,
  SUBSTRING(RETORNO, 151, 5) AS CODIGO_PLANO,
  SUBSTRING(RETORNO, 156, 2) AS ORIGEM_SOLICITACAO,
  SUBSTRING(RETORNO, 158, 73) AS FILLER,
  SUBSTRING(RETORNO, 231, 3) AS CODIGO_RNA,
  SUBSTRING(RETORNO, 234, 15) AS VALOR_RENDIMENTOS,
  SUBSTRING(RETORNO, 249, 4) AS TIPO_CARTEIRA,
  SUBSTRING(RETORNO, 253, 5) AS NIVEL_RELACIONAMENTO,
  SUBSTRING(RETORNO, 258, 26) AS DATA_INFORMACAO,
  SUBSTRING(RETORNO, 284, 17) AS FILLER2,
  RIGHT(REPLICATE ('0' , 15)+CONVERT(VARCHAR, B.CPF), 11) AS CPF,
  Left(B.NOME, CharIndex(' ', B.NOME)) AS PRIMEIRO_NOME,
  Reverse(Left(Reverse(B.Nome), CharIndex(' ', Reverse(B.Nome)))) AS SOBRENOME,
  CASE WHEN LEN(B.TEL_01) = 9 THEN '(' + SUBSTRING(B.DDD_01, 1, 3) + ') ' + 
           SUBSTRING(B.TEL_01, 1, 5) + '-' + 
           SUBSTRING(B.TEL_01, 6, 4)
      ELSE '(' + SUBSTRING(B.DDD_01, 1, 3) + ') ' + 
           SUBSTRING(B.TEL_01, 1, 4) + '-' + 
           SUBSTRING(B.TEL_01, 5, 4) END AS TEL_RESIDENCIAL,
  CASE WHEN LEN(B.TEL_02) = 9 THEN '(' + SUBSTRING(B.DDD_02, 1, 3) + ') ' + 
           SUBSTRING(B.TEL_02, 1, 5) + '-' + 
           SUBSTRING(B.TEL_02, 6, 4)
      ELSE '(' + SUBSTRING(B.DDD_02, 1, 3) + ') ' + 
           SUBSTRING(B.TEL_02, 1, 4) + '-' + 
           SUBSTRING(B.TEL_02, 5, 4) END AS TEL_COMERCIAL,
  CASE WHEN LEN(B.TEL_03) = 9 THEN '(' + SUBSTRING(B.DDD_03, 1, 3) + ') ' + 
           SUBSTRING(B.TEL_03, 1, 5) + '-' + 
           SUBSTRING(B.TEL_03, 6, 4)
      ELSE '(' + SUBSTRING(B.DDD_03, 1, 3) + ') ' + 
           SUBSTRING(B.TEL_03, 1, 4) + '-' + 
           SUBSTRING(B.TEL_03, 5, 4) END AS CELULAR1,
  CASE WHEN LEN(B.TEL_04) = 9 THEN '(' + SUBSTRING(B.DDD_04, 1, 3) + ') ' + 
           SUBSTRING(B.TEL_04, 1, 5) + '-' + 
           SUBSTRING(B.TEL_04, 6, 4)
      ELSE '(' + SUBSTRING(B.DDD_04, 1, 3) + ') ' + 
           SUBSTRING(B.TEL_04, 1, 4) + '-' + 
           SUBSTRING(B.TEL_04, 5, 4) END AS CELULAR2,
  SUBSTRING(RETORNO, 38, 8) AS DT_NASCIMENTO_SF,
  B.QUARENTENA,
  B.SEXO,
  CONCAT(RIGHT(REPLICATE ('0' , 15)+CONVERT(VARCHAR, B.CPF), 11),'Cliente') AS CPF_TIPO_RELACIONAMENTO,
  CONCAT(RIGHT(REPLICATE ('0' , 15)+CONVERT(VARCHAR, B.CPF), 11),'52') AS CPF_CODIGO_PARCEIRO,
  B.ID_CAMPANHA,
  /*CONCAT(CONVERT(INT, SUBSTRING(RETORNO, 234, 13)),'.',RIGHT(SUBSTRING(RETORNO, 234, 15), 2)) AS FAIXA_RENDA_MENSAL,*/
  CASE WHEN B.VALIDA_ENCARTEIRAMENTO = 1 AND CONVERT(INT,SUBSTRING(RETORNO, 249, 4)) IN (31,32,33,34,35,40,41,42,43,44,45,46,47,48,49,54,10,50,57) THEN 0 ELSE 1 END AS ENCARTEIRAMENTO_VALIDO
  FROM
    TB_BASE_PROSPECT_OTC291_TEO A /*TB_BASE_OTC291 A */ 
INNER JOIN TB_BASE_PROSPECT_COMOTC_TRATADA_TEO B ON SUBSTRING(RETORNO, 23, 15) = RIGHT(REPLICATE ('0' , 15)+CONVERT(VARCHAR, B.CPF), 15)