SELECT
	A.*
FROM (
	SELECT DISTINCT
		B.HC_CPF_CNPJ__C AS CPF_CNPJ,
		C.NAME AS NOME,
		B.HC_IDADE__C AS IDADE,
		B.HC_PARCEIRO__C AS PARCEIRO,
		CASE 
			WHEN UPPER(B.HC_ENDERECO_PRINCIPAL__C) = 'RESIDENCIAL' THEN HC_ENDERECO_RESIDENCIAL__C
			WHEN UPPER(B.HC_ENDERECO_PRINCIPAL__C) = 'COMERCIAL' THEN HC_ENDERECO_COMERCIAL__C
			WHEN UPPER(B.HC_ENDERECO_PRINCIPAL__C) = 'CORRESPONDÊNCIA' THEN HC_ENDERECO_CORRESPONDENCIA__C
		END AS ENDERECO,
		CASE 
			WHEN UPPER(B.HC_ENDERECO_PRINCIPAL__C) = 'RESIDENCIAL' THEN HC_UF_RES__C
			WHEN UPPER(B.HC_ENDERECO_PRINCIPAL__C) = 'COMERCIAL' THEN HC_UF_COM__C
			WHEN UPPER(B.HC_ENDERECO_PRINCIPAL__C) = 'CORRESPONDÊNCIA' THEN HC_UF_COR__C
		END AS UF,
		CASE 
			WHEN UPPER(B.HC_ENDERECO_PRINCIPAL__C) = 'RESIDENCIAL' THEN HC_CEP_RES__C
			WHEN UPPER(B.HC_ENDERECO_PRINCIPAL__C) = 'COMERCIAL' THEN HC_CEP_COM__C
			WHEN UPPER(B.HC_ENDERECO_PRINCIPAL__C) = 'CORRESPONDÊNCIA' THEN HC_CEP_COR__C
		END AS CEP,
		CASE
			WHEN B.HC_EMAIL_PRINCIPAL__C = 'Brasilcap' THEN HC_EMAIL_BRASILCAP__C
			WHEN B.HC_EMAIL_PRINCIPAL__C = 'Comercial' THEN HC_EMAIL_COMERCIAL__C
			WHEN B.HC_EMAIL_PRINCIPAL__C = 'Pessoal' THEN HC_EMAIL_PESSOAL__C
			WHEN B.HC_EMAIL_BRASILCAP__C IS NOT NULL THEN HC_EMAIL_BRASILCAP__C
			WHEN B.HC_EMAIL_COMERCIAL__C IS NOT NULL THEN HC_EMAIL_COMERCIAL__C
			WHEN B.HC_EMAIL_PESSOAL__C IS NOT NULL THEN HC_EMAIL_PESSOAL__C
			ELSE NULL
		END AS EMAIL,
		CASE
			WHEN B.HC_EMAIL_PRINCIPAL__C IN ('Brasilcap', 'Comercial', 'Pessoal') THEN 1
			WHEN B.HC_EMAIL_BRASILCAP__C IS NOT NULL THEN 1
			WHEN B.HC_EMAIL_COMERCIAL__C IS NOT NULL THEN 1
			WHEN B.HC_EMAIL_PESSOAL__C IS NOT NULL THEN 1
			ELSE 0
		END AS EMAIL_VALIDO,
		CASE
			WHEN B.HC_STATUS_CELULAR_1__C = 'VÁLIDO' THEN HC_CELULAR_1__C
			WHEN B.HC_STATUS_CELULAR_2__C = 'VÁLIDO' THEN HC_CELULAR_2__C
			WHEN B.HC_STATUS_CELULAR_3__C = 'VÁLIDO' THEN HC_CELULAR_3__C
			ELSE NULL
		END AS CELULAR,
		CASE
			WHEN B.HC_STATUS_CELULAR_1__C = 'VÁLIDO' THEN 1
			WHEN B.HC_STATUS_CELULAR_2__C = 'VÁLIDO' THEN 1
			WHEN B.HC_STATUS_CELULAR_3__C = 'VÁLIDO' THEN 1
			ELSE 0
		END AS CELULAR_VALIDO,
		B.HC_TIPO_DE_PESSOA__C AS TIPO_PESSOA,
		LEFT(REPLACE(REPLACE(REPLACE(REPLACE(B.HC_TELEFONE_RESIDENCIAL__C, '(', ''), ')', ''), ' ', ''), '-', ''), 2) AS DDD_TEL_01,
		SUBSTRING(REPLACE(REPLACE(REPLACE(REPLACE(B.HC_TELEFONE_RESIDENCIAL__C, '(', ''), ')', ''), ' ', ''), '-', ''), 3, 9) AS TEL_01,
		'FIXO' AS TIPO_TEL_01,
		LEFT(REPLACE(REPLACE(REPLACE(REPLACE(B.HC_TELEFONE_COMERCIAL__C, '(', ''), ')', ''), ' ', ''), '-', ''), 2) AS DDD_TEL_02,
		SUBSTRING(REPLACE(REPLACE(REPLACE(REPLACE(B.HC_TELEFONE_COMERCIAL__C, '(', ''), ')', ''), ' ', ''), '-', ''), 3, 9) AS TEL_02,
		'FIXO' AS TIPO_TEL_02,
		LEFT(REPLACE(REPLACE(REPLACE(REPLACE(B.HC_TELEFONE_OUTRO__C, '(', ''), ')', ''), ' ', ''), '-', ''), 2) AS DDD_TEL_03,
		SUBSTRING(REPLACE(REPLACE(REPLACE(REPLACE(B.HC_TELEFONE_OUTRO__C, '(', ''), ')', ''), ' ', ''), '-', ''), 3, 9) AS TEL_03,
		'FIXO' AS TIPO_TEL_03,
			LEFT(REPLACE(REPLACE(REPLACE(REPLACE(B.HC_CELULAR_1__C, '(', ''), ')', ''), ' ', ''), '-', ''), 2) AS DDD_TEL_04,
		SUBSTRING(REPLACE(REPLACE(REPLACE(REPLACE(B.HC_CELULAR_1__C, '(', ''), ')', ''), ' ', ''), '-', ''), 3, 9) AS TEL_04,
		'MÓVEL' AS TIPO_TEL_04,
		LEFT(REPLACE(REPLACE(REPLACE(REPLACE(B.HC_CELULAR_2__C, '(', ''), ')', ''), ' ', ''), '-', ''), 2) AS DDD_TEL_05,
		SUBSTRING(REPLACE(REPLACE(REPLACE(REPLACE(B.HC_CELULAR_2__C, '(', ''), ')', ''), ' ', ''), '-', ''), 3, 9) AS TEL_05,
		'MÓVEL' AS TIPO_TEL_05,
		LEFT(REPLACE(REPLACE(REPLACE(REPLACE(B.HC_CELULAR_3__C, '(', ''), ')', ''), ' ', ''), '-', ''), 2) AS DDD_TEL_06,
		SUBSTRING(REPLACE(REPLACE(REPLACE(REPLACE(B.HC_CELULAR_3__C, '(', ''), ')', ''), ' ', ''), '-', ''), 3, 9) AS TEL_06,
		'MÓVEL' AS TIPO_TEL_06,
		B.HC_TELEFONE_PRINCIPAL__C AS TEL_PRINCIPAL,
		B.HC_CLASSIFICACAO__C AS PUBLICO_ALVO,
		A.STARTDATE AS DT_INICIO_MAILING,
		A.ENDDATE AS DT_FIM_MAILING,
		A.HC_PRODUTO__C AS ID_PRODUTO,
		A.HC_PRECO_DO_PRODUTO__C AS ID_PRODUTO_VALOR,
		B.HC_CPF_CNPJ__C AS ID,
		A.ID AS ID_CAMPANHA, 
		B.ID AS ID_CLIENTE_PARCEIRO,
		C.ID AS ID_CONTATO,
		B.HC_CLIENTE__C AS ID_CLIENTE,
		D.HC_DATA_DO_ULTIMO_RESGATE__C AS DT_ULTIMO_RESGATE,
		D.HC_VALOR_DA_PARCELA__C AS VALOR_PARCELA_PRODUTO,
		A.HC_EXCLUSAO_DE_COMPRA_RECENTE__C AS MESES_COMPRA_EXCLUSAO,
		A.HC_QUARENTENA__C AS MESES_QUARENTENA_EXCLUSAO,
		D.HC_NUMERO_DO_TITULO__C as NUMERO_DO_TITULO,
		D.HC_SERIE__C as SERIE_DO_TITULO,
		D.HC_PLANO__C as PLANO_DO_TITULO,
		D.HC_CONTRATACAO__C AS DATA_CONTRATACAO,
		CASE WHEN DATEPART(WEEKDAY, GetDate()) = 5 THEN DATEADD(DAY, 3, DATEADD(HH, 3, A.HC_DATA_DE_EXECUCAO__C)) ELSE DATEADD(DAY, A.HC_PROXIMA_EXECUCAO__C, DATEADD(HH, 3, A.HC_DATA_DE_EXECUCAO__C)) END AS DATA_PROXIMA_EXECUCAO,
		ROW_NUMBER() OVER(ORDER BY B.ID ASC) AS ROWNO
	FROM CAMPAIGN_SALESFORCE A
	INNER JOIN HC_RELACAO_CLIENTE_PARCEIRO__C_SALESFORCE B ON A.HC_PARCEIRO__C = B.HC_PARCEIRO__C
	INNER JOIN CONTACT_SALESFORCE C ON C.HC_CPF_CNPJ__C = B.HC_CPF_CNPJ__C
	INNER JOIN HC_TITULO__C_SALESFORCE D ON D.HC_CLIENTE_X_PARCEIRO__C = B.ID
	WHERE
		(B.HC_TIPO_DE_PESSOA__C = A.HC_TIPO_DE_CLIENTE__C OR A.HC_TIPO_DE_CLIENTE__C = 'PF E PJ')
	/* AND CONVERT(VARCHAR, A.HC_DATA_DE_EXECUCAO__C, 112) = CONVERT(VARCHAR, GETDATE(), 112) */
	AND A.ISACTIVE = 1
	/* ID DA CAMPANHA PAI (HEADER) DE BOAS VINDAS OUROCAP */
	AND A.PARENTID = '7016g000000NVrXAAW'
	/* AND A.HC_CAMPANHA_EXECUTADA_NO_MKT__C = 0 */
	AND D.HC_SITUACAO__C = 'ATIVO'
	/* PARCEIRO TCBB PARA OUROCAP */
	AND D.HC_ORIGEM__C = 'CAP'
	AND D.HC_CODIGO_DO_PARCEIRO_NA_ORIGEM__C = 'TCBB'
	AND D.HC_CONTRATACAO__C BETWEEN A.HC_DATA_INICIAL_DE_COMPRA__C AND A.HC_DATA_FINAL_DE_COMPRA__C
	AND (
		/* CUSTOM BETWEEN */
		(A.HC_VALOR_MINIMO_DE_PARCELA__C IS NULL OR D.HC_VALOR_DA_PARCELA__C > A.HC_VALOR_MINIMO_DE_PARCELA__C)
		AND (A.HC_VALOR_MAXIMO_DA_PARCELA__C IS NULL OR D.HC_VALOR_DA_PARCELA__C < A.HC_VALOR_MAXIMO_DA_PARCELA__C)
	)
) A
INNER JOIN
  CAMPAIGN_SALESFORCE CAMP 
  ON A.ID_CAMPANHA = CAMP.ID
WHERE
	CAMP.HC_QUANTIDADE_DE_CONTATOS_NO_MAILING__C IS NULL
	OR A.ROWNO <= CAMP.HC_QUANTIDADE_DE_CONTATOS_NO_MAILING__C