SELECT DISTINCT
  B.CPF,
  'TCBB' AS COD_PARCEIRO,
  '' AS CNPJ,
  'Brasilcap' AS PARCEIRO_ORGANIZACAO,
  'Brazil' AS PARCEIRO_LOCALIZACAO,
  A.ID_CLIENTE_PARCEIRO AS COD_CLIENTE_MC,
  B.NOME AS NOME_COMPLETO,
  'PF' AS TIPO_PESSOA,
  CONVERT(VARCHAR, CONVERT(DATE, B.DATA_NASCIMENTO, 103), 112) AS DATA_NASCIMENTO,
  B.SEXO,
  'Brasilcap' AS CLIENTE_ORGANIZACAO,
  CONCAT(B.CPF, 'TCBB') AS CLIENTE_CHAVE_MIGRACAO,
  CONCAT(B.CPF, 'TCBB') AS CLIENTE_CHAGE_GERAL_INTERNA,
  'Person' AS CLIENTE_TIPO_INTERNO,
  '99999999999' AS INICIO_TRAILLER 
FROM
  TB_BASE_PROSPECT_OTC291_FILTRADA_NEOBPO A 
  INNER JOIN
    TB_BASE_PROSPECT_COMOTC_TRATADA_NEOBPO B 
    ON A.CPF = B.CPF