SELECT
	A.CPF AS ID,
	1 AS NAO_IMPORTUNE
FROM Renovacao_Online_Tratada_TMKT A
INNER JOIN TB_BASE_NAO_IMPORTUNE N ON ISNULL(CONCAT(A.DDD_01, A.TEL_01), '00000000000') = LTRIM(RTRIM(N.TELEFONE))
UNION
SELECT
	A.CPF AS ID,
	1 AS NAO_IMPORTUNE
FROM Renovacao_Online_Tratada_TMKT A
INNER JOIN TB_BASE_NAO_IMPORTUNE N ON ISNULL(CONCAT(A.DDD_02, A.TEL_02), '00000000000') = LTRIM(RTRIM(N.TELEFONE))
UNION
SELECT
	A.CPF AS ID,
	1 AS NAO_IMPORTUNE
FROM Renovacao_Online_Tratada_TMKT A
INNER JOIN TB_BASE_NAO_IMPORTUNE N ON ISNULL(CONCAT(A.DDD_03, A.TEL_03), '00000000000') = LTRIM(RTRIM(N.TELEFONE))
UNION
SELECT
	A.CPF AS ID,
	1 AS NAO_IMPORTUNE
FROM Renovacao_Online_Tratada_TMKT A
INNER JOIN TB_BASE_NAO_IMPORTUNE N ON ISNULL(CONCAT(A.DDD_04, A.TEL_04), '00000000000') = LTRIM(RTRIM(N.TELEFONE))
UNION
SELECT
	A.CPF AS ID,
	1 AS NAO_IMPORTUNE
FROM Renovacao_Online_Tratada_TMKT A
INNER JOIN TB_BASE_NAO_IMPORTUNE N ON ISNULL(CONCAT(A.DDD_05, A.TEL_05), '00000000000') = LTRIM(RTRIM(N.TELEFONE))