SELECT 
  ID_PROPOSTA,
  CPF_CNPJ,
  ID_CONTATO,
  ID_CLIENTE_PARCEIRO,
  CELULAR_VALIDO,
  NAO_DESEJA_RECEBER_SMS,
  CELULAR,
  TITULOS_ANTERIORES_ATIVOS,
  TITULOS_ANTERIORES_INATIVOS,
  CREATEDDATE,
  NOME
FROM TB_BOAS_VINDAS_PESQUISA_SMS
WHERE
CELULAR IS NOT NULL