select 
    distinct CPF_CNPJ,
	NOME,
    CONCAT('55',DDD_TEL, TEL) AS TELEFONE,
    CONCAT('55',DDD_TEL, TEL) AS TELEFONE_PADRONIZADO,
    ID_CLIENTE_PARCEIRO,
	ID_CONTATO,
	ID_CLIENTE,
	ID_CAMPANHA,
	ID_DEMANDA,
	Dt_Ult_Execucao,
	DATA_PROXIMA_EXECUCAO
from PublicoAlvoDuploSim
where 
    LEN(CONCAT(DDD_TEL, TEL)) = 11
    OR LEN(CONCAT(DDD_TEL1, TEL1)) = 11
    OR LEN(CONCAT(DDD_TEL2, TEL2)) = 11
  