SELECT
    distinct B.HC_CPF_CNPJ__C AS CPF_CNPJ,
	ACEITE.NOMECOMPLETO AS NOME,
	LEFT(REPLACE(REPLACE(REPLACE(REPLACE(ACEITE.TELEFONE, '(', ''), ')', ''), ' ', ''), '-', ''), 2) AS DDD_TEL,
	SUBSTRING(REPLACE(REPLACE(REPLACE(REPLACE(ACEITE.TELEFONE, '(', ''), ')', ''), ' ', ''), '-', ''), 3, 9) AS TEL,
	B.ID AS ID_CLIENTE_PARCEIRO,
	B.HC_Cliente__c AS ID_CLIENTE,
	A.ID AS ID_CAMPANHA,
	C.ID AS ID_CONTATO,
	getdate() AS Dt_Ult_Execucao
FROM HC_RELACAO_CLIENTE_PARCEIRO__C_SALESFORCE B
INNER JOIN CAMPAIGN_SALESFORCE A 
    ON 1 = 1
INNER JOIN Tb_Base_Duplo_Sim_Nao_Aceitaram ACEITE 
    ON concat(REPLICATE('0', 11 -LEN(ACEITE.CPF)),RTrim(ACEITE.CPF)) = B.HC_CPF_CNPJ__C
INNER JOIN CONTACT_SALESFORCE C 
    ON concat(REPLICATE('0', 11 -LEN(ACEITE.CPF)),RTrim(ACEITE.CPF)) = concat(REPLICATE('0', 11 -LEN(C.HC_CPF_CNPJ__c)),RTrim(C.HC_CPF_CNPJ__c))

WHERE
	A.ID = '7016g000002O07HAAS'
	AND A.ISACTIVE = 1
	AND B.HC_Classificacao__c != 'Falecido'
	AND B.HC_Nao_deseja_receber_Todos_Meios__c = 0
	AND B.HC_Nao_deseja_receber_SMS__c = 0
	AND ACEITE.FLG_ENVIO <> 1
    AND B.HC_Id_Parceiro_Cap__c = 'TCBB'