SELECT
	A.CPF_CNPJ AS ID,
	CASE WHEN (A.CAMPANHA_NAO_IMPORTUNE = 1 AND N2.TELEFONE IS NOT NULL) THEN 1 ELSE 0 END AS NAO_IMPORTUNE
FROM Tb_Base_Prop_Ourocap_N_Pag A
LEFT JOIN TB_BASE_NAO_IMPORTUNE N2 ON ISNULL(CONCAT(A.DDD_TEL_02, A.TEL_02), '00000000000') = LTRIM(RTRIM(N2.TELEFONE))