SELECT
  OTC291.CPF_CNPJ,
  OTC291.Id_Campanha AS CAMPANHA,
  CONVERT(INTEGER, OTC291.IDADE) AS  IDADE,
  OTC291.CONSELHEIRO,
  OTC291.CLIENTE_PEP,
  OTC291.DESEJA_CONTATO_TELEFONICO AS NAO_DESEJA_RECEBER_LIGACOES,
  OTC291.POSSUI_TELEFONE_ATIVO,
  OTC291.POSSUI_CONTA_ATIVA,
  OTC291.COMPRA_RECENTE_OUROCAP,
  OTC291.NAO_IMPORTUNE,
  OTC291.CODIGO_RNA,
  OTC291.ALTA_RENDA,
  CASE
    WHEN OTC291.CODIGO_RNA IS NULL OR OTC291.CODIGO_RNA != '000' THEN 'EXCLUIDO RNA'
    WHEN OTC291.ALTA_RENDA IS NULL OR OTC291.ALTA_RENDA != 0 THEN 'ALTA RENDA'
  END AS RESULTADO
FROM Revenda_Ourocap_OTC291_Filtrada OTC291
WHERE 
  OTC291.Ind_MembroCampanha = 0