SELECT
  B.CPF_CNPJ,
  CMP.NAME AS CAMPANHA,
  B.COMPRA_UTIMOS_30_DIAS AS COMPROU_ULTIMOS_30_DIAS,
  /* B.DESEJA_CONTATO_TELEFONICO AS NAO_DESEJA_RECEBER_LIGACOES, */
  /* B.POSSUI_TELEFONE_ATIVO, */
  /* B.POSSUI_CONTA_CORRENTE, */
  B.POSSUI_TITULO_ATIVO,
  /* B.QUARENTENA, */
  B.NAO_IMPORTUNE,
  CASE
    /* WHEN B.IDADE_VALIDA IS NULL OR B.IDADE_VALIDA = 0 THEN 'IDADE INVALIDA' */
    /* WHEN B.CONSELHEIRO IS NULL OR B.CONSELHEIRO = 1 THEN 'CONSELHEIRO' */
    /* WHEN B.CLIENTE_PEP IS NULL OR B.CLIENTE_PEP = 1 THEN 'PEP' */
    /* WHEN B.DESEJA_CONTATO_TELEFONICO IS NULL OR B.DESEJA_CONTATO_TELEFONICO = 1 THEN 'NÃO DESEJA CONTATO TELEFONICO' */
    /* WHEN B.POSSUI_TELEFONE_ATIVO IS NULL OR B.POSSUI_TELEFONE_ATIVO = 0 THEN 'NÃO POSSUI TELEFONE ATIVO' */
    /* WHEN B.POSSUI_CONTA_CORRENTE IS NULL OR B.POSSUI_CONTA_CORRENTE = 0 THEN 'NÃO POSSUI CONTA CORRENTE' */
    WHEN B.COMPRA_UTIMOS_30_DIAS IS NULL OR B.COMPRA_UTIMOS_30_DIAS = 1 THEN 'NÃO COMPROU NOS ULTIMOS 30 DIAS'
    WHEN B.POSSUI_TITULO_ATIVO IS NULL OR B.POSSUI_TITULO_ATIVO = 0 THEN 'NÃO POSSUI TITULO ATIVO'
    WHEN B.NAO_IMPORTUNE IS NULL OR B.NAO_IMPORTUNE = 1 THEN 'NÃO IMPORTUNE'
    /* WHEN B.QUARENTENA IS NULL OR B.QUARENTENA = 1 THEN 'EM QUARENTENA' */
  END AS RESULTADO
  /* CASE
    WHEN Q.CPF_CNPJ IS NULL THEN NULL
    WHEN B.COMPRA_UTIMOS_30_DIAS IS NULL OR B.COMPRA_UTIMOS_30_DIAS = 1 THEN NULL
    WHEN B.POSSUI_TITULO_ATIVO IS NULL OR B.POSSUI_TITULO_ATIVO = 0 THEN NULL
    WHEN B.NAO_IMPORTUNE IS NULL OR B.NAO_IMPORTUNE = 0 THEN NULL
    WHEN B.QUARENTENA IS NULL OR B.QUARENTENA = 1 THEN CONCAT(
      RIGHT( CONCAT('0', DATEPART(DD, Data_Participacao_Campanha)) , 2),
      '/',
      RIGHT( CONCAT('0', DATEPART(MM, Data_Participacao_Campanha)) , 2),
      '/',
      DATEPART(YYYY, Data_Participacao_Campanha)
    )
  END AS data_quarentena */
FROM
  Publico_Inapto_Clientes_Renovacao_TMKT_ONLINE B
LEFT JOIN CAMPAIGN_SALESFORCE CMP ON B.ID_CAMPANHA = CMP.ID
LEFT JOIN TB_BASE_QUARENTENA Q ON Q.CPF_CNPJ = B.CPF_CNPJ