SELECT /* top 4200 */
  A.*,
  C.ID_CONTATO AS CONTACTID
FROM Renovacao_OTC291_Tratada_TMKT_ONLINE A
/* CHECAGEM SE TOODS OS CONTATOS TIVERAM O OTC TRATADO */
LEFT OUTER JOIN ( 
  SELECT
    COUNT(1) as CPFS_FALTANDO_NO_OTC
  FROM Tb_Base_Cliente_Filtrada_Renovacao_TMKT_ONLINE ENV
  LEFT JOIN Renovacao_OTC291_Tratada_TMKT_ONLINE RET ON ENV.CPF_CNPJ = RET.CPF
  WHERE RET.CPF IS NULL 
) B ON 1 = 1
INNER JOIN Tb_Base_Cliente_Filtrada_Renovacao_TMKT_ONLINE  C ON C.CPF_CNPJ = A.CPF
WHERE 
/* SIGNIFICA QUE TODOS OS CONTATOS JÁ ESTÃO NO OTC291 */
  B.CPFS_FALTANDO_NO_OTC = 0
  /* VALIDAÇÕES POR CONTATO DO OTC */
  AND A.CODIGO_RNA = '000'
  AND A.ALTA_RENDA = 0
  /* AND A.Nivel_Relacionamento  IN ('2112',  '2202', '2602', '02112',  '02202', '02602') */