SELECT
     ID_CONTATO,
     ID_CAMPANHA,	
     ID_CLIENTE_PARCEIRO,	
     ID_PROPOSTA,
     NOME,
     CPF_CNPJ,	
     HC_SITUACAO__C,	
     NAO_IMPORTUNE,	
     CELULAR,	
     DATA_AGENDAMENTO,			
     DATA_AGENDAMENTO_FORMATADA,
     DATA_PROXIMA_EXECUCAO
FROM AVISO_PAGAMENTO_PUBLICO_INICIAL A
WHERE NAO_IMPORTUNE = 0