
SELECT DISTINCT
GmailD5S2.CPF,
GmailD5S2.NOME,
GmailD5S2.EMAIL,
GmailD5S2.EMAIL_VALIDO,
CASE

  WHEN CHARINDEX(' ', GmailD5S2.NOME) = 0 THEN GmailD5S2.NOME

  ELSE SUBSTRING( GmailD5S2.NOME , 1, CHARINDEX(' ', GmailD5S2.NOME) )

END AS PNOME
FROM Gmail_DIV05_SUB02 GmailD5S2
UNION
SELECT DISTINCT
MicrosodftD5S2.CPF,
MicrosodftD5S2.NOME,
MicrosodftD5S2.EMAIL,
MicrosodftD5S2.EMAIL_VALIDO,
CASE

  WHEN CHARINDEX(' ', MicrosodftD5S2.NOME) = 0 THEN MicrosodftD5S2.NOME

  ELSE SUBSTRING( MicrosodftD5S2.NOME , 1, CHARINDEX(' ', MicrosodftD5S2.NOME) )

END AS PNOME
FROM Microsoft_DIV05_SUB02 MicrosodftD5S2
UNION
SELECT DISTINCT
YahooD5S2.CPF,
YahooD5S2.NOME,
YahooD5S2.EMAIL,
YahooD5S2.EMAIL_VALIDO,
CASE

  WHEN CHARINDEX(' ', YahooD5S2.NOME) = 0 THEN YahooD5S2.NOME

  ELSE SUBSTRING( YahooD5S2.NOME , 1, CHARINDEX(' ', YahooD5S2.NOME) )

END AS PNOME
FROM Yahoo_DIV05_SUB02 YahooD5S2
UNION
SELECT DISTINCT
OutrosD5S2.CPF,
OutrosD5S2.NOME,
OutrosD5S2.EMAIL,
OutrosD5S2.EMAIL_VALIDO,
CASE

  WHEN CHARINDEX(' ', OutrosD5S2.NOME) = 0 THEN OutrosD5S2.NOME

  ELSE SUBSTRING( OutrosD5S2.NOME , 1, CHARINDEX(' ', OutrosD5S2.NOME) )

END AS PNOME
FROM Outros_DIV05_SUB02 OutrosD5S2
