SELECT 
	Id_Contato,
	MAX(CPF_CNPJ) AS CPF_CNPJ,
	MAX(Nome) AS Nome,
	MAX(Id_Campanha) AS Id_Campanha,
	MAX(Id_Cliente_Parceiro) AS Id_Cliente_Parceiro,
	MAX(CONVERT(INTEGER, NAO_DESEJA_RECEBER_EMAIL)) AS NAO_DESEJA_RECEBER_EMAIL,
	MAX(CONVERT(INTEGER, NAO_DESEJA_RECEBER_SMS)) AS NAO_DESEJA_RECEBER_SMS,
	MAX(EMAIL) AS EMAIL,
	MAX(CONVERT(INTEGER, EMAIL_VALIDO)) AS EMAIL_VALIDO,
	MAX(CELULAR) AS CELULAR,
	MAX(CONVERT(INTEGER, CELULAR_VALIDO)) AS CELULAR_VALIDO,
	MAX(TITULOS_ANTERIORES_ATIVOS) AS TITULOS_ANTERIORES_ATIVOS,
	MAX(TITULOS_ANTERIORES_INATIVOS) AS TITULOS_ANTERIORES_INATIVOS,
	MAX(CREATEDDATE) AS CREATEDDATE,
	MAX(CONVERT(INTEGER, FLAG_WHATSAPP)) AS FLAG_WHATSAPP
FROM AeM_Tb_Boas_Vindas_Ourocap_Prospostas
WHERE NAO_IMPORTUNE = 0
GROUP BY ID_CONTATO