SELECT DISTINCT
  'TCBB' AS COD_PARCEIRO,
  B.CPF,
  '' AS CNPJ,
  '' AS BANCO,
  B.AGENCIA,
  '' AS DIGITO_VERIFICADOR_AGENCIA,
  B.CONTA AS CONTA_CORRENTE,
  '' AS DIGITO_VERIFICADOR_CONTA,
  '' AS AGENCIA_CONTA_DIGITO_VERIFICADOR,
  'CC' AS TIPO_CONTA,
  '' AS INICIO_TRAILLER 
FROM
  TB_BASE_PROSPECT_OTC291_FILTRADA_NEOBPO A 
  INNER JOIN
    TB_BASE_PROSPECT_COMOTC_TRATADA_NEOBPO B 
    ON A.CPF = B.CPF