SELECT
  A.CODIGO_PARCEIRO,
  A.ID_CLIENTE,
  A.CODIGO_MCI,
  A.TIPO_PESSOA,
  A.CODIGO_CIC,
  A.DT_NASCIMENTO,
  A.NOME,
  A.SEXO,
  A.UF_RESIDENCIAL,
  A.DDD1,
  A.TELEFONE1,
  A.DDD2,
  A.TELEFONE2,
  A.DDD3,
  A.TELEFONE3,
  A.CODIGO_PLANO,
  A.ORIGEM_SOLICITACAO,
  A.FILLER,
  A.CODIGO_RNA,
  A.VALOR_RENDIMENTOS,
  A.TIPO_CARTEIRA,
  A.NIVEL_RELACIONAMENTO,
  A.DATA_INFORMACAO,
  A.FILLER2,
  A.CPF,
  UPPER(SUBSTRING(B.NOME, 1, CHARINDEX(' ', B.NOME) - 1)) AS PRIMEIRO_NOME,
  UPPER(SUBSTRING(B.NOME, CHARINDEX(' ', B.NOME) + 1, LEN(B.NOME))) AS SOBRENOME,
  A.DT_NASCIMENTO_SF,
  CONCAT(A.CPF,'Cliente') AS CPF_TIPO_RELACIONAMENTO,
  B.CPF_CNPJ_CODIGO_DO_PARCEIRO,
  B.ID_CLIENTE_PARCEIRO,
  B.ID_CONTATO,
  B.ID_CAMPANHA,
  A.FAIXA_RENDA_MENSAL,
  A.Alta_Renda,
  B.DATA_PROXIMA_EXECUCAO
FROM
  Prop_Ourocap_N_Pag_OTC291_Tratada A
INNER JOIN Tb_Base_Prop_Ourocap_N_Pag_Filtrada_TESTE B ON A.CPF = B.CPF_CNPJ
WHERE HC_Origem_da_Venda__c  not IN ('TIVIT - Vendas Diretas',
                                'TIVIT - Venda Nova',
                                'TIVIT - Revenda',
                                'TIVIT - Revenda',
                                'TIVIT - Venda Nova',
                                'TIVIT - Revenda',
                                'BrasilCap - Venda Nova',
                                'Brasilcap - Tivit Variável',
                                'BRASILCAP - VENDAS DIRETAS')