SELECT DISTINCT
  A.*
FROM
  (
    SELECT
      *,
      ROW_NUMBER() OVER(PARTITION BY CODIGO_CIC ORDER BY GETDATE() DESC) AS ROWNO 
    FROM
      TB_BASE_PROSPECT_OTC291_FILTRADA_TEO
  ) A
WHERE
  ROWNO = 1
AND A.Id_Cliente_Parceiro IS NULL