
	SELECT DISTINCT
		CP.HC_CPF_CNPJ__C AS CPF,
		C.NAME AS NOME,
		CASE
			WHEN CP.HC_EMAIL_PRINCIPAL__C = 'Brasilcap' THEN HC_EMAIL_BRASILCAP__C
			WHEN CP.HC_EMAIL_PRINCIPAL__C = 'Comercial' THEN HC_EMAIL_COMERCIAL__C
			WHEN CP.HC_EMAIL_PRINCIPAL__C = 'Pessoal' THEN HC_EMAIL_PESSOAL__C
			WHEN CP.HC_EMAIL_BRASILCAP__C IS NOT NULL THEN HC_EMAIL_BRASILCAP__C
			WHEN CP.HC_EMAIL_COMERCIAL__C IS NOT NULL THEN HC_EMAIL_COMERCIAL__C
			WHEN CP.HC_EMAIL_PESSOAL__C IS NOT NULL THEN HC_EMAIL_PESSOAL__C
			ELSE NULL
		END AS EMAIL,
		CASE
			WHEN CP.HC_EMAIL_PRINCIPAL__C IN ('Brasilcap', 'Comercial', 'Pessoal') THEN 1
			WHEN CP.HC_EMAIL_BRASILCAP__C IS NOT NULL THEN 1
			WHEN CP.HC_EMAIL_COMERCIAL__C IS NOT NULL THEN 1
			WHEN CP.HC_EMAIL_PESSOAL__C IS NOT NULL THEN 1
			ELSE 0
		END AS EMAIL_VALIDO
		
FROM Base_CSV CSV 
	INNER JOIN CONTACT_SALESFORCE C ON CSV.CPF = C.HC_CPF_CNPJ__C
	INNER JOIN HC_RELACAO_CLIENTE_PARCEIRO__C_SALESFORCE CP  ON C.HC_CPF_CNPJ__C = CP.HC_CPF_CNPJ__C

	
