SELECT   
  ACC.MOBILEMESSAGETRACKINGID AS MOBILEMESSAGETRACKINGID,
  S.CREATEDATETIME AS DT_ENVIO,
  S.ACTIONDATETIME AS DT_ENTREGA,
  S.DELIVERED AS ENTREGUE,
  S.UNDELIVERED AS BOUNCE,
  IIF(S.OPTOUT IS NULL,0,1) AS OPTOUT
FROM SMS_INFOS_REPORT_CUMULATIVO ACC
INNER JOIN _SMSMESSAGETRACKING S ON CONVERT(VARCHAR, S.MOBILEMESSAGETRACKINGID) = ACC.MOBILEMESSAGETRACKINGID