SELECT DISTINCT
  'TCBB' AS COD_PARCEIRO,
  B.CPF_CNPJ AS CPF,
  '' AS CNPJ,
  B.CEP
FROM
  Tb_Base_Ex_Cliente_OTC291_Filtrada_TMKT A 
  INNER JOIN
    Tb_Base_Ex_Cliente_ComOTC_Filtrada_TMKT B 
    ON A.CPF = B.CPF_CNPJ