SELECT
    A.TEL_02,
    A.Id_Campanha,
    A.Nome,
    A.Sexo,
    A.Primeiro_Nome,
    A.DDD_03,
    A.Telefone2,
    A.TEL_01,
    A.Ddd3,
    A.Codigo_RNA,
    A.Ddd2,
    A.CEP,
    A.Codigo_Parceiro,
    A.Sobrenome,
    A.TEL_05,
    A.Origem_Solicitacao,
    A.Ddd1,
    A.Dt_Nascimento,
    A.Tipo_Pessoa,
    A.CPF_CNPJ_Codigo_do_Parceiro,
    A.DDD_05,
    A.Filler2,
    A.Tipo_Carteira,
    A.CPF,
    A.DDD_01,
    A.Id_Cliente_Parceiro,
    A.Codigo_Plano,
    A.Data_Informacao,
    A.Filler,
    A.Nivel_Relacionamento,
    A.Telefone3,
    A.Valor_Rendimentos,
    A.Id_Cliente,
    A.Telefone1,
    A.Codigo_MCI,
    A.DDD_02,
    A.CPF_Tipo_Relacionamento,
    A.TEL_03,
    A.UF_Residencial,
    A.TEL_04,
    A.Codigo_CIC,
    A.DDD_04,
    R.Name as Nome_Produto,
    P.Name as Nome_Produto_Valor
FROM
Tb_Base_Ex_Cliente_OTC291_Tratada_Algar	 A
INNER JOIN Tb_Base_Ex_Cliente_ComOTC_Algar B ON A.CPF = B.ID
INNER JOIN HC_Relacao_Cliente_Parceiro__c_Salesforce C ON A.Id_Cliente_Parceiro = C.ID
INNER JOIN HC_Produto__c_Salesforce R ON B.Id_Produto = R.ID
INNER JOIN HC_Preco_do_Produto__c_Salesforce P ON B.Id_Produto_Valor = P.ID