SELECT CPF,
  COD_PARCEIRO,
  CNPJ,
  PARCEIRO_ORGANIZACAO,
  PARCEIRO_LOCALIZACAO,
  COD_CLIENTE_MC,
  NOME_COMPLETO,
  TIPO_PESSOA,
  DATA_NASCIMENTO,
  SEXO,
  CLIENTE_ORGANIZACAO,
  CLIENTE_CHAVE_MIGRACAO,
  CLIENTE_CHAGE_GERAL_INTERNA,
  CLIENTE_TIPO_INTERNO,
  DIA_PROV
FROM (SELECT DISTINCT
  A.CPF,
  'TCBB' AS COD_PARCEIRO,
  '' AS CNPJ,
  'Brasilcap' AS PARCEIRO_ORGANIZACAO,
  'Brazil' AS PARCEIRO_LOCALIZACAO,
  REL.ID AS COD_CLIENTE_MC,
  B.NOME AS NOME_COMPLETO,
  'PF' AS TIPO_PESSOA,
  CONVERT(VARCHAR, CAST(B.Dt_Nascimento AS DATE), 112) AS DATA_NASCIMENTO,
  B.SEXO,
  'Brasilcap' AS CLIENTE_ORGANIZACAO,
  CONCAT(A.CPF, 'TCBB') AS CLIENTE_CHAVE_MIGRACAO,
  CONCAT(A.CPF, 'TCBB') AS CLIENTE_CHAGE_GERAL_INTERNA,
  'Person' AS CLIENTE_TIPO_INTERNO,
  A.Dia_Prov,
  row_number() over (partition by A.CPF order by REL.ID desc) AS ROW_ID
FROM
  TB_BASE_PROSPECT_OTC291_FILTRADA_TMKT A 
    INNER JOIN Tb_Base_Prospect_OTC291_Tratada_TMKT B ON A.CPF = B.CPF
    INNER JOIN HC_Relacao_Cliente_Parceiro__c_Salesforce REL ON A.CPF = REL.CPF_CNPJ_Cliente__c
    INNER JOIN Contact_Salesforce C on RIGHT(REPLICATE ('0' , 15)+CONVERT(VARCHAR, C.HC_CPF_CNPJ__c), 11) = B.CPF
    INNER JOIN ACCOUNT_SALESFORCE D on C.AccountId = D.ID
    ) BASE
WHERE ROW_ID = 1