SELECT B.CPF,
      CASE WHEN B.VALIDA_NAO_IMPORTUNE = 1 AND N4.TELEFONE IS NOT NULL OR Nao_Importune = 1 THEN 1 ELSE 0 END AS Nao_Importune
FROM 	Tb_Base_Prospect_ComOTC_Online_Tratada_AeC B 
INNER JOIN TB_BASE_NAO_IMPORTUNE N4 ON ISNULL(CONCAT(DDD_04, TEL_04), '00000000000') = LTRIM(RTRIM(N4.TELEFONE))
