SELECT DISTINCT
    UPPER(A.NOME) AS NOME,
	LTRIM(RTRIM(A.CPF)) AS CPF,
	A.AGENCIA,
	A.CONTA,
	A.TIPO_CONTA,
	A.DATA_NASCIMENTO,
	A.SEXO,
	A.CEP,
	A.DDD_01,
	A.TEL_01,
	A.DDD_02,
	A.TEL_02,
	A.DDD_03,
	A.TEL_03,
	A.DDD_04,
	A.TEL_04,
	A.DDD_05,
	A.TEL_05,
    CA.ID AS ID_CAMPANHA,
    CA.HC_PRODUTO__C AS NOME_PRODUTO,
    CA.HC_PRECO_DO_PRODUTO__C AS NOME_PRODUTO_VALOR,
    CA.HC_VALIDA_ALTA_RENDA__C AS VALIDA_ENCARTEIRAMENTO,
    CA.HC_VALIDA_RNA__C AS VALIDA_RNA,
    CASE WHEN DATEDIFF(YY, CONVERT(VARCHAR, CONVERT(DATE, A.DATA_NASCIMENTO, 103), 112), CONVERT(VARCHAR, GETDATE(), 112)) BETWEEN 18 AND 70 THEN 1 ELSE 0 END AS IDADE_VALIDA,
    CASE WHEN (UPPER(A.TIPO_CONTA) = 'CC' OR UPPER(A.TIPO_CONTA) = 'CONTA CORRENTE') THEN 1 ELSE 0 END AS CONTA_CORRENTE,
    CASE WHEN Q.CPF_CNPJ IS NOT NULL THEN 1 ELSE 0 END AS QUARENTENA,
    CASE WHEN CL.HC_CPF_CNPJ__C IS NOT NULL AND CL.HC_CLASSIFICACAO__C != 'Cliente Potencial' THEN 1 ELSE 0 END AS CLIENTE,
    CASE WHEN CL.HC_CPF_CNPJ__C IS NOT NULL AND CL.HC_CONSELHEIRO__C = 1 THEN 1 ELSE 0 END AS CONSELHEIRO,
	CASE WHEN ISNULL(A.CEP, '') = '' OR A.CEP = ' ' THEN 0 ELSE 1 END AS CEP_VALIDO,
    CONCAT(LTRIM(RTRIM(A.CPF)),'Cliente') AS CPF_TIPO_RELACIONAMENTO,
    CONCAT(LTRIM(RTRIM(A.CPF)),'45') AS CPF_CODIGO_PARCEIRO,
    UPPER(SUBSTRING(A.NOME, 1, CHARINDEX(' ', A.NOME) - 1)) AS PRIMEIRO_NOME,
    UPPER(SUBSTRING(A.NOME, CHARINDEX(' ', A.NOME) + 1, LEN(A.NOME))) AS SOBRENOME,
    CASE WHEN CA.HC_VALIDA_NAO_IMPORTUNE__C = 1 AND (N1.TELEFONE IS NOT NULL OR N2.TELEFONE IS NOT NULL OR N3.TELEFONE IS NOT NULL OR N4.TELEFONE IS NOT NULL OR N5.TELEFONE IS NOT NULL) THEN 1 ELSE 0 END AS NAO_IMPORTUNE,
    CONVERT(VARCHAR, CONVERT(DATE, A.DATA_NASCIMENTO, 103), 112) AS DT_NASCIMENTO_SF
FROM TB_BASE_PROSPECT_SEMOTC_TEO A
INNER JOIN CAMPAIGN_SALESFORCE CA ON A.FORNECEDOR = CA.HC_FORNECEDOR__C
LEFT JOIN HC_RELACAO_CLIENTE_PARCEIRO__C_SALESFORCE CL ON LTRIM(RTRIM(A.CPF)) = CL.HC_CPF_CNPJ__C
LEFT JOIN TB_BASE_QUARENTENA Q ON LTRIM(RTRIM(A.CPF)) = Q.CPF_CNPJ
LEFT JOIN TB_BASE_NAO_IMPORTUNE N1 ON ISNULL(CONCAT(DDD_01, TEL_01), '00000000000') = LTRIM(RTRIM(N1.TELEFONE))
LEFT JOIN TB_BASE_NAO_IMPORTUNE N2 ON ISNULL(CONCAT(DDD_02, TEL_02), '00000000000') = LTRIM(RTRIM(N2.TELEFONE))
LEFT JOIN TB_BASE_NAO_IMPORTUNE N3 ON ISNULL(CONCAT(DDD_03, TEL_03), '00000000000') = LTRIM(RTRIM(N3.TELEFONE))
LEFT JOIN TB_BASE_NAO_IMPORTUNE N4 ON ISNULL(CONCAT(DDD_04, TEL_04), '00000000000') = LTRIM(RTRIM(N4.TELEFONE))
LEFT JOIN TB_BASE_NAO_IMPORTUNE N5 ON ISNULL(CONCAT(DDD_05, TEL_05), '00000000000') = LTRIM(RTRIM(N5.TELEFONE))
WHERE
    CA.HC_FORNECEDOR__C = 'Teo'
AND CONVERT(VARCHAR, CA.CREATEDDATE, 112) = CONVERT(VARCHAR, GETDATE(), 112)
AND CA.[TYPE] = 'Prospect'
AND CA.HC_VALIDA_RNA__C = 0