SELECT
  CPF_CNPJ,
  QUARENTENA,
  POSSUI_TITULO_ATIVO,
  NAO_IMPORTUNE,
  ID_campanha
FROM
  Tb_Base_Prop_Ourocap_N_Pag b
WHERE
  NOT(/* IDADE_VALIDA = 1 */
  /* AND CONSELHEIRO = 0 */
  /* AND CLIENTE_PEP = 0 */
  /* AND DESEJA_CONTATO_TELEFONICO = 0 */
  /* AND POSSUI_CONTA_CORRENTE = 1 */
  POSSUI_TELEFONE_ATIVO = 1
AND QUARENTENA = 0
/* AND INATIVIDADE = 0 */
AND NAO_IMPORTUNE = 0)