SELECT DISTINCT
  CPF,
  'TCBB' AS COD_PARCEIRO,
  '' AS CNPJ,
  'Brasilcap' AS PARCEIRO_ORGANIZACAO,
  'Brazil' AS PARCEIRO_LOCALIZACAO,
  ID_CLIENTE_PARCEIRO AS COD_CLIENTE_MC,
  NOME AS NOME_COMPLETO,
  'PF' AS TIPO_PESSOA,
  CONVERT(VARCHAR, CONVERT(DATE, DATA_NASCIMENTO, 103), 112) AS DATA_NASCIMENTO,
  SEXO,
  'Brasilcap' AS CLIENTE_ORGANIZACAO,
  CONCAT(CPF, 'TCBB') AS CLIENTE_CHAVE_MIGRACAO,
  CONCAT(CPF, 'TCBB') AS CLIENTE_CHAGE_GERAL_INTERNA,
  'Person' AS CLIENTE_TIPO_INTERNO
FROM
  TB_BASE_PROSPECT_SEMOTC_FILTRADA_ALGAR