SELECT DISTINCT
    CL.HC_CPF_CNPJ__C AS CPF,
	C.NAME AS NOME,
	HC_IDADE__C AS IDADE,
	HC_DATA_DE_NASCIMENTO__C AS Data_Nascimento,
	HC_GENERO_DO_CLIENTE__C AS SEXO,
	CL.HC_PARCEIRO__C AS PARCEIRO,
	CASE 
		WHEN UPPER(CL.HC_ENDERECO_PRINCIPAL__C) = 'RESIDENCIAL' THEN HC_CEP_RES__C
		WHEN UPPER(CL.HC_ENDERECO_PRINCIPAL__C) = 'COMERCIAL' THEN HC_CEP_COM__C
		WHEN UPPER(CL.HC_ENDERECO_PRINCIPAL__C) = 'CORRESPONDÊNCIA' THEN HC_CEP_COR__C
	END AS CEP,
	CASE 
		WHEN UPPER(CL.HC_ENDERECO_PRINCIPAL__C) = 'RESIDENCIAL' THEN HC_UF_RES__C
		WHEN UPPER(CL.HC_ENDERECO_PRINCIPAL__C) = 'COMERCIAL' THEN HC_UF_COM__C
		WHEN UPPER(CL.HC_ENDERECO_PRINCIPAL__C) = 'CORRESPONDÊNCIA' THEN HC_UF_COR__C
	END AS UF,
	HC_TIPO_DE_PESSOA__C AS TIPO_PESSOA,
	LEFT(REPLACE(REPLACE(REPLACE(REPLACE(HC_TELEFONE_RESIDENCIAL__C, '(', ''), ')', ''), ' ', ''), '-', ''), 2) AS DDD_TEL_01,
	SUBSTRING(REPLACE(REPLACE(REPLACE(REPLACE(HC_TELEFONE_RESIDENCIAL__C, '(', ''), ')', ''), ' ', ''), '-', ''), 3, 9) AS TEL_01,
	'FIXO' AS TIPO_TEL_01,
	LEFT(REPLACE(REPLACE(REPLACE(REPLACE(HC_TELEFONE_COMERCIAL__C, '(', ''), ')', ''), ' ', ''), '-', ''), 2) AS DDD_TEL_02,
	SUBSTRING(REPLACE(REPLACE(REPLACE(REPLACE(HC_TELEFONE_COMERCIAL__C, '(', ''), ')', ''), ' ', ''), '-', ''), 3, 9) AS TEL_02,
	'FIXO' AS TIPO_TEL_02,
	LEFT(REPLACE(REPLACE(REPLACE(REPLACE(HC_TELEFONE_OUTRO__C, '(', ''), ')', ''), ' ', ''), '-', ''), 2) AS DDD_TEL_03,
	SUBSTRING(REPLACE(REPLACE(REPLACE(REPLACE(HC_TELEFONE_OUTRO__C, '(', ''), ')', ''), ' ', ''), '-', ''), 3, 9) AS TEL_03,
	'FIXO' AS TIPO_TEL_03,
    LEFT(REPLACE(REPLACE(REPLACE(REPLACE(HC_CELULAR_1__C, '(', ''), ')', ''), ' ', ''), '-', ''), 2) AS DDD_TEL_04,
	SUBSTRING(REPLACE(REPLACE(REPLACE(REPLACE(HC_CELULAR_1__C, '(', ''), ')', ''), ' ', ''), '-', ''), 3, 9) AS TEL_04,
	'MÓVEL' AS TIPO_TEL_04,
	LEFT(REPLACE(REPLACE(REPLACE(REPLACE(HC_CELULAR_2__C, '(', ''), ')', ''), ' ', ''), '-', ''), 2) AS DDD_TEL_05,
	SUBSTRING(REPLACE(REPLACE(REPLACE(REPLACE(HC_CELULAR_2__C, '(', ''), ')', ''), ' ', ''), '-', ''), 3, 9) AS TEL_05,
	'MÓVEL' AS TIPO_TEL_05,
	LEFT(REPLACE(REPLACE(REPLACE(REPLACE(HC_CELULAR_3__C, '(', ''), ')', ''), ' ', ''), '-', ''), 2) AS DDD_TEL_06,
	SUBSTRING(REPLACE(REPLACE(REPLACE(REPLACE(HC_CELULAR_3__C, '(', ''), ')', ''), ' ', ''), '-', ''), 3, 9) AS TEL_06,
	'MÓVEL' AS TIPO_TEL_06,
	HC_TELEFONE_PRINCIPAL__C AS TEL_PRINCIPAL,
	HC_CLASSIFICACAO__C AS PUBLICO_ALVO,
	CA.[TYPE] AS TIPO_CAMPANHA,
	CA.STARTDATE AS DT_INICIO_MAILING,
	CA.ENDDATE AS DT_FIM_MAILING,
	CA.HC_VALIDA_ALTA_RENDA__C AS CAMPANHA_VALIDA_ENCARTEIRAMENTO,
    CA.HC_VALIDA_NAO_IMPORTUNE__C AS CAMPANHA_NAO_IMPORTUNE,
    CA.HC_VALIDA_RNA__C AS CAMPANHA_VALIDA_RNA,
	CA.HC_PRODUTO__C AS ID_PRODUTO,
    CA.HC_PRECO_DO_PRODUTO__C AS ID_PRODUTO_VALOR,
	CL.HC_CPF_CNPJ__C AS ID,
	CA.ID AS ID_CAMPANHA, 
	CL.ID AS ID_CLIENTE_PARCEIRO,
	C.ID AS ID_CONTATO,
	CL.HC_Cliente__c AS ID_CLIENTE,
	CL.HC_CPF_CNPJ_CODIGO_DO_PARCEIRO__C AS CPF_CNPJ_CODIGO_DO_PARCEIRO,
    CA.HC_PRODUTO__C AS NOME_PRODUTO,
    CA.HC_PRECO_DO_PRODUTO__C AS NOME_PRODUTO_VALOR,
    CA.HC_VALIDA_ALTA_RENDA__C AS VALIDA_ENCARTEIRAMENTO,
    CA.HC_VALIDA_NAO_IMPORTUNE__C AS VALIDA_NAO_IMPORTUNE,
    CA.HC_VALIDA_RNA__C AS VALIDA_RNA,
    CASE WHEN DATEDIFF(YY, HC_DATA_DE_NASCIMENTO__C, GETDATE()) BETWEEN 18 AND 70 THEN 1 ELSE 0 END AS IDADE_VALIDA,
    CASE WHEN ( A.AGENCIA != '' AND A.CONTA != '' AND (UPPER(A.TIPO_CONTA) = 'CC' OR UPPER(A.TIPO_CONTA) = 'CONTA CORRENTE') ) THEN 1 ELSE 0 END AS CONTA_CORRENTE,
    CASE WHEN Q.CPF_CNPJ IS NOT NULL THEN 1 ELSE 0 END AS QUARENTENA,
    CASE WHEN CL.HC_CPF_CNPJ__C IS NOT NULL AND CL.HC_CLASSIFICACAO__C != 'Cliente Potencial' THEN 1 ELSE 0 END AS CLIENTE,
    CASE WHEN CL.HC_CPF_CNPJ__C IS NOT NULL AND CL.HC_CONSELHEIRO__C = 1 THEN 1 ELSE 0 END AS CONSELHEIRO,
	CASE WHEN ISNULL(A.CEP, '') = '' OR A.CEP = ' ' THEN 0 ELSE 1 END AS CEP_VALIDO
FROM TB_BASE_PROSPECT_COMOTC_NEOBPO A
INNER JOIN CAMPAIGN_SALESFORCE CA ON A.FORNECEDOR = CA.HC_FORNECEDOR__C
INNER JOIN HC_RELACAO_CLIENTE_PARCEIRO__C_SALESFORCE CL ON LTRIM(RTRIM(A.CPF)) = CL.HC_CPF_CNPJ__C
INNER JOIN Contact_Salesforce C ON C.HC_CPF_CNPJ__c =   CL.HC_CPF_CNPJ__c
LEFT JOIN TB_BASE_QUARENTENA Q ON LTRIM(RTRIM(A.CPF)) = Q.CPF_CNPJ
WHERE
    CA.HC_FORNECEDOR__C = 'NeoBpo'
/*AND CONVERT(VARCHAR, CA.HC_Data_de_Execucao__c, 112) = CONVERT(VARCHAR, GETDATE(), 112)*/
AND CA.[TYPE] = 'Prospect'
/*AND CA.HC_VALIDA_RNA__C = 1*/