SELECT
    A.CPF_CNPJ AS ID,
	CASE WHEN Q.CPF_CNPJ IS NOT NULL THEN 1 ELSE 0 END AS QUARENTENA
FROM
	Tb_Base_Cliente_TMKT_ONLINE A
LEFT JOIN TB_BASE_QUARENTENA Q ON A.CPF_CNPJ = Q.CPF_CNPJ
AND Q.DATA_PARTICIPACAO_CAMPANHA > DATEADD(DD, -90, GETDATE())