SELECT
  base.id,
  CASE WHEN ACEITE.CPF IS NOT NULL THEN 1 ELSE 0 END AS NAO_ACEITOU
FROM Tb_Base_Duplo_Sim_SemOTC_Tratada BASE
LEFT JOIN Tb_Base_Duplo_Sim_Nao_Aceitaram ACEITE 
ON concat(REPLICATE('0', 11 -LEN(ACEITE.CPF)),RTrim(ACEITE.CPF))  = BASE.CPF_CNPJ
