SELECT
	A.HC_CPF_CNPJ__C AS ID,
    CASE WHEN A.HC_CONSELHEIRO__C = 1 THEN 1 ELSE 0 END AS CONSELHEIRO,
    CASE WHEN A.HC_PEP__C = 1 THEN 1 ELSE 0 END AS CLIENTE_PEP,
    CASE WHEN A.HC_NAO_DESEJA_RECEBER_LIGACOES__C = 1 THEN 1 ELSE 0 END AS DESEJA_CONTATO_TELEFONICO,
    CASE WHEN A.HC_IDADE__C BETWEEN 18 AND 70 THEN 1 ELSE 0 END AS IDADE_VALIDA,
    CASE WHEN a.HC_Nao_deseja_receber_Email__c = 0 THEN 0 ELSE 1 END AS Nao_deseja_receber_Email,
    CASE WHEN a.HC_Nao_deseja_receber_Ligacoes__c = 0 THEN 0 ELSE 1 END AS Nao_deseja_receber_Ligacoes,
    CASE WHEN a.HC_Nao_deseja_receber_SMS__c = 0 THEN 0 ELSE 1 END AS Nao_deseja_receber_SMS,
	CASE WHEN (LEN(CONCAT(B.DDD_TEL_01,B.TEL_01)) = 10 
	            OR LEN(CONCAT(B.DDD_TEL_02,B.TEL_02)) = 10 
	            OR LEN(CONCAT(B.DDD_TEL_03,B.TEL_03)) = 10
                OR LEN(CONCAT(B.DDD_TEL_04,B.TEL_04)) = 11 
                OR LEN(CONCAT(B.DDD_TEL_05,B.TEL_05)) = 11 
                OR LEN(CONCAT(B.DDD_TEL_06,B.TEL_06)) = 11) 
        THEN 1 
        ELSE 0
        END AS POSSUI_TELEFONE_ATIVO
FROM
    HC_RELACAO_CLIENTE_PARCEIRO__C_SALESFORCE A
INNER JOIN Revenda_Ourocap_PublicoInicial B ON A.HC_CPF_CNPJ__C = B.CPF_CNPJ