SELECT 
  BASE.*
FROM (  SELECT
    C.NAME AS NOME,
    B.HC_CPF_CNPJ__C AS CPF_CNPJ,
    B.HC_IDADE__C AS IDADE,
      B.HC_DATA_DE_NASCIMENTO__C AS DT_NASCIMENTO,
    B.HC_GENERO_DO_CLIENTE__C AS SEXO,
    B.HC_PARCEIRO__C AS PARCEIRO,
    B.HC_TIPO_DE_PESSOA__C AS TIPO_PESSOA,
    CASE
      WHEN B.HC_EMAIL_PRINCIPAL__C = 'Brasilcap' THEN HC_EMAIL_BRASILCAP__C
      WHEN B.HC_EMAIL_PRINCIPAL__C = 'Comercial' THEN HC_EMAIL_COMERCIAL__C
      WHEN B.HC_EMAIL_PRINCIPAL__C = 'Pessoal' THEN HC_EMAIL_PESSOAL__C
      WHEN B.HC_EMAIL_BRASILCAP__C IS NOT NULL THEN HC_EMAIL_BRASILCAP__C
      WHEN B.HC_EMAIL_COMERCIAL__C IS NOT NULL THEN HC_EMAIL_COMERCIAL__C
      WHEN B.HC_EMAIL_PESSOAL__C IS NOT NULL THEN HC_EMAIL_PESSOAL__C
      ELSE NULL
    END AS EMAIL,
    CASE
      WHEN B.HC_EMAIL_BRASILCAP__C IS NOT NULL THEN 1
      WHEN B.HC_EMAIL_COMERCIAL__C IS NOT NULL THEN 1
      WHEN B.HC_EMAIL_PESSOAL__C IS NOT NULL THEN 1
      ELSE 0
    END AS EMAIL_VALIDO,
        CASE
      WHEN B.HC_STATUS_CELULAR_1__C = 'VÁLIDO' THEN HC_CELULAR_1__C
      WHEN B.HC_STATUS_CELULAR_2__C = 'VÁLIDO' THEN HC_CELULAR_2__C
      WHEN B.HC_STATUS_CELULAR_3__C = 'VÁLIDO' THEN HC_CELULAR_3__C
      ELSE NULL
    END AS CELULAR,
    CASE
      WHEN B.HC_STATUS_CELULAR_1__C = 'VÁLIDO' THEN 1
      WHEN B.HC_STATUS_CELULAR_2__C = 'VÁLIDO' THEN 1
      WHEN B.HC_STATUS_CELULAR_3__C = 'VÁLIDO' THEN 1
      ELSE 0
    END AS CELULAR_VALIDO,
    LEFT(REPLACE(REPLACE(REPLACE(REPLACE(B.HC_TELEFONE_RESIDENCIAL__C, '(', ''), ')', ''), ' ', ''), '-', ''), 2) AS DDD_TEL_01,
    SUBSTRING(REPLACE(REPLACE(REPLACE(REPLACE(B.HC_TELEFONE_RESIDENCIAL__C, '(', ''), ')', ''), ' ', ''), '-', ''), 3, 9) AS TEL_01,
    'FIXO' AS TIPO_TEL_01,
    LEFT(REPLACE(REPLACE(REPLACE(REPLACE(B.HC_TELEFONE_COMERCIAL__C, '(', ''), ')', ''), ' ', ''), '-', ''), 2) AS DDD_TEL_02,
    SUBSTRING(REPLACE(REPLACE(REPLACE(REPLACE(B.HC_TELEFONE_COMERCIAL__C, '(', ''), ')', ''), ' ', ''), '-', ''), 3, 9) AS TEL_02,
    'FIXO' AS TIPO_TEL_02,
    LEFT(REPLACE(REPLACE(REPLACE(REPLACE(B.HC_TELEFONE_OUTRO__C, '(', ''), ')', ''), ' ', ''), '-', ''), 2) AS DDD_TEL_03,
    SUBSTRING(REPLACE(REPLACE(REPLACE(REPLACE(B.HC_TELEFONE_OUTRO__C, '(', ''), ')', ''), ' ', ''), '-', ''), 3, 9) AS TEL_03,
    'FIXO' AS TIPO_TEL_03,
      LEFT(REPLACE(REPLACE(REPLACE(REPLACE(B.HC_CELULAR_1__C, '(', ''), ')', ''), ' ', ''), '-', ''), 2) AS DDD_TEL_04,
    SUBSTRING(REPLACE(REPLACE(REPLACE(REPLACE(B.HC_CELULAR_1__C, '(', ''), ')', ''), ' ', ''), '-', ''), 3, 9) AS TEL_04,
    'MÓVEL' AS TIPO_TEL_04,
    LEFT(REPLACE(REPLACE(REPLACE(REPLACE(B.HC_CELULAR_2__C, '(', ''), ')', ''), ' ', ''), '-', ''), 2) AS DDD_TEL_05,
    SUBSTRING(REPLACE(REPLACE(REPLACE(REPLACE(B.HC_CELULAR_2__C, '(', ''), ')', ''), ' ', ''), '-', ''), 3, 9) AS TEL_05,
    'MÓVEL' AS TIPO_TEL_05,
    LEFT(REPLACE(REPLACE(REPLACE(REPLACE(B.HC_CELULAR_3__C, '(', ''), ')', ''), ' ', ''), '-', ''), 2) AS DDD_TEL_06,
    SUBSTRING(REPLACE(REPLACE(REPLACE(REPLACE(B.HC_CELULAR_3__C, '(', ''), ')', ''), ' ', ''), '-', ''), 3, 9) AS TEL_06,
    'MÓVEL' AS TIPO_TEL_06,
    B.HC_TELEFONE_PRINCIPAL__C AS TEL_PRINCIPAL,
    B.HC_CLASSIFICACAO__C AS PUBLICO_ALVO,
    A.[TYPE] AS TIPO_CAMPANHA,
    A.STARTDATE AS DT_INICIO_MAILING,
    A.ENDDATE AS DT_FIM_MAILING,
    A.HC_VALIDA_ALTA_RENDA__C AS CAMPANHA_VALIDA_ENCARTEIRAMENTO,
    A.HC_VALIDA_NAO_IMPORTUNE__C AS CAMPANHA_NAO_IMPORTUNE,
    A.HC_VALIDA_RNA__C AS CAMPANHA_VALIDA_RNA,
    A.HC_PRODUTO__C AS ID_PRODUTO,
    A.HC_PRECO_DO_PRODUTO__C AS ID_PRODUTO_VALOR,
    B.HC_CPF_CNPJ__C AS ID,
    A.ID AS ID_CAMPANHA, 
    B.ID AS ID_CLIENTE_PARCEIRO,
    C.ID AS ID_CONTATO,
    B.HC_CLIENTE__C AS ID_CLIENTE,
    B.HC_CPF_CNPJ_CODIGO_DO_PARCEIRO__C AS CPF_CNPJ_CODIGO_DO_PARCEIRO,
    D.HC_Data_Inicio_Sorteio__c AS DT_INICIO_SORTEIO,
    A.HC_Valor_maximo_de_contemplacao__c AS Valor_Max_Contemplacao,
    A.HC_Valor_minimo_de_contemplacao__c AS Valor_Min_Contemplacao,
    format(A.HC_Data_inicial_de_contemplacao__c,'dd/MM/yyyy') AS Dt_Inicio_Contemplacao,
    format(A.HC_Data_fim_de_contemplacao__c, 'dd/MM/yyyy') AS Dt_Fim_Contemplacao,
    format (D.HC_Data_da_Ultima_Contemplacao__c,'dd/MM/yyyy') AS Dt_Ultima_Contemplacao,
    D.HC_Numero_da_Sorte__c AS Numero_Sorteado,
    D.HC_Valor_Premio__c AS Valor_Premio,
    /* evitar repetição de CPFs */
		ROW_NUMBER() OVER(ORDER BY B.ID ASC) AS ROWNO,
    getdate()+HC_Proxima_execucao__c AS DATA_PROXIMA_EXECUCAO,
    D.ID AS Id_titulo
  FROM (
    SELECT
      A.ID AS CAMPAIGN_ID,
      B.ID AS RELACAO_CLIENTE_PARCEIRO_ID,
      C.ID AS CONTACT_ID,
      D.ID AS TITULO_ID,
      ROW_NUMBER() OVER(PARTITION BY B.ID ORDER BY B.ID ASC) AS NUMBER_OF_CPF_REPETITION
    FROM CAMPAIGN_SALESFORCE A
    INNER JOIN HC_RELACAO_CLIENTE_PARCEIRO__C_SALESFORCE B ON 1 = 1
    INNER JOIN HC_TITULO__C_SALESFORCE D ON D.HC_CLIENTE_X_PARCEIRO__C = B.ID 
    INNER JOIN CONTACT_SALESFORCE C ON C.HC_CPF_CNPJ__C = B.HC_CPF_CNPJ__C 
    WHERE 
        A.ID = '7016g000000NVYrAAO'
        /*AND CONVERT(VARCHAR(10), A.HC_DATA_DE_EXECUCAO__C, 101) = CONVERT(VARCHAR(10), GETDATE(), 101)*/
        AND (B.HC_TIPO_DE_PESSOA__C = A.HC_TIPO_DE_CLIENTE__C OR (A.HC_TIPO_DE_CLIENTE__C = 'PF E PJ' ))
        /*AND B.HC_CLASSIFICACAO__C = 'Cliente'*/
        AND B.HC_NOME_PARCEIRO__C = 'BB CORRETORA'
        AND D.HC_Data_da_Ultima_Contemplacao__c between 
                              A.HC_Data_inicial_de_contemplacao__c  AND A.HC_Data_fim_de_contemplacao__c
        AND (D.flg_envio_campanha__c = 0 or D.Data_ultimo_envio_campanha__c < HC_Data_inicial_de_contemplacao__c)
  ) FILTERED
  INNER JOIN CAMPAIGN_SALESFORCE A ON FILTERED.CAMPAIGN_ID = A.ID
  INNER JOIN HC_RELACAO_CLIENTE_PARCEIRO__C_SALESFORCE B ON B.ID = FILTERED.RELACAO_CLIENTE_PARCEIRO_ID
  INNER JOIN HC_TITULO__C_SALESFORCE D ON D.ID = FILTERED.TITULO_ID
  INNER JOIN CONTACT_SALESFORCE C ON C.ID = FILTERED.CONTACT_ID
  WHERE
    NUMBER_OF_CPF_REPETITION = 1
) BASE
INNER JOIN
  CAMPAIGN_SALESFORCE CAMP
  ON BASE.ID_CAMPANHA = CAMP.ID
WHERE
	CAMP.HC_QUANTIDADE_DE_CONTATOS_NO_MAILING__C IS NULL
	OR BASE.ROWNO <= (CAMP.HC_QUANTIDADE_DE_CONTATOS_NO_MAILING__C)