SELECT DISTINCT
  A.CPF,
  'TCBB' AS COD_PARCEIRO,
  '' AS CNPJ,
  'Brasilcap' AS PARCEIRO_ORGANIZACAO,
  'Brazil' AS PARCEIRO_LOCALIZACAO,
  ID_CLIENTE_PARCEIRO AS COD_CLIENTE_MC,
  B.NOME AS NOME_COMPLETO,
  'PF' AS TIPO_PESSOA,
  CONVERT(VARCHAR, CAST(B.Dt_Nascimento AS DATE), 112) AS DATA_NASCIMENTO,
  B.SEXO,
  'Brasilcap' AS CLIENTE_ORGANIZACAO,
  CONCAT(A.CPF, 'TCBB') AS CLIENTE_CHAVE_MIGRACAO,
  CONCAT(A.CPF, 'TCBB') AS CLIENTE_CHAGE_GERAL_INTERNA,
  'Person' AS CLIENTE_TIPO_INTERNO
FROM
  TB_BASE_PROSPECT_OTC291_FILTRADA_ALGAR A 
    INNER JOIN Tb_Base_Prospect_OTC291_Tratada_ALGAR B ON A.CPF = B.CPF