SELECT BASE.CPF_CNPJ,
  BASE.NOME,
  BASE.IDADE,
  BASE.DT_NASCIMENTO,
  BASE.SEXO,
  BASE.TIPO_PESSOA,
  BASE.PARCEIRO,
  BASE.Id_Campanha,
  BASE.Id,
  BASE.Id_Cliente_Parceiro,
  BASE.Id_Contato,
  base.Data_da_Venda,
  BASE.Id_Cliente,
  BASE.HC_Contratacao__c,
  BASE.DT_LIMITE,
  BASE.DIAS_ANTECEDENCIA,
  BASE.Dt_Ult_Execucao,
  BASE.HC_FORMATO__C,
  BASE.HC_FORNECEDOR__C,
  BASE.Origem_Venda,
  BASE.Agendamento,
  BASE.ID_PROPOSTA,
  CASE WHEN BASE.DDD_TEL_06 IS NOT NULL
          AND BASE.TEL_06 IS NOT NULL THEN CONCAT('55',BASE.DDD_TEL_06, BASE.TEL_06)
      WHEN BASE.DDD_TEL_04 IS NOT NULL
          AND BASE.TEL_04 IS NOT NULL THEN CONCAT('55',BASE.DDD_TEL_04, BASE.TEL_04)
      WHEN BASE.DDD_TEL_05 IS NOT NULL
          AND BASE.TEL_05 IS NOT NULL THEN CONCAT('55',BASE.DDD_TEL_05, BASE.TEL_05)
  END AS NUMERO_CELULAR_ATIVO,
  getdate() AS DATA_DISPARO,
  BASE.DATA_PROXIMA_EXECUCAO
FROM Tb_Base_Duplo_Sim_SemOTC_Tratada BASE
WHERE 
  (
    LEN(CONCAT(BASE.DDD_TEL_04, BASE.TEL_04)) = 11
    OR LEN(CONCAT(BASE.DDD_TEL_05, BASE.TEL_05)) = 11
    OR LEN(CONCAT(BASE.DDD_TEL_06, BASE.TEL_06)) = 11
  )
  AND NAO_ACEITOU = 1