SELECT
  B.CPF_CNPJ,
  CMP.NAME AS CAMPANHA,
  PAR.HC_CODIGO_DO_PARCEIRO_CAP__C AS PARCEIRO,
  /* CONVERT(INTEGER, REL.HC_IDADE__C) AS IDADE, */
  /* B.COMPRA_UTIMOS_30_DIAS AS COMPROU_ULTIMOS_30_DIAS, */
  B.CONSELHEIRO,
  B.CLIENTE_PEP,
  B.DESEJA_CONTATO_TELEFONICO AS NAO_DESEJA_RECEBER_LIGACOES,
  B.NAO_DESEJA_RECEBER_TODOS_MEIOS AS NAO_DESEJA_RECEBER_TODOS_MEIOS,
  B.NAO_DESEJA_RECEBER_SMS,
  B.NAO_DESEJA_RECEBER_EMAIL,
  B.EMAIL_VALIDO,
  B.CELULAR_VALIDO,
  B.POSSUI_TELEFONE_ATIVO,
  /* B.POSSUI_CONTA_CORRENTE, */
  /* B.POSSUI_TITULO_ATIVO, */
  B.QUARENTENA,
  CASE
    /* WHEN B.IDADE_VALIDA IS NULL OR B.IDADE_VALIDA = 0 THEN 'IDADE INVALIDA' */
    /* WHEN B.CONSELHEIRO IS NULL OR B.CONSELHEIRO = 1 THEN 'CONSELHEIRO' */
    /* WHEN B.CLIENTE_PEP IS NULL OR B.CLIENTE_PEP = 1 THEN 'PEP' */
    /* WHEN B.DESEJA_CONTATO_TELEFONICO IS NULL OR B.DESEJA_CONTATO_TELEFONICO = 1 THEN 'NÃO DESEJA CONTATO TELEFONICO' */
    /* WHEN B.POSSUI_TELEFONE_ATIVO IS NULL OR B.POSSUI_TELEFONE_ATIVO = 0 THEN 'NÃO POSSUI TELEFONE ATIVO' */
    /* WHEN B.POSSUI_CONTA_CORRENTE IS NULL OR B.POSSUI_CONTA_CORRENTE = 0 THEN 'NÃO POSSUI CONTA CORRENTE' */
    /* WHEN B.COMPRA_UTIMOS_30_DIAS IS NULL OR B.COMPRA_UTIMOS_30_DIAS = 1 THEN 'NÃO COMPROU NOS ULTIMOS 30 DIAS' */
    /* WHEN B.POSSUI_TITULO_ATIVO IS NULL OR B.POSSUI_TITULO_ATIVO = 0 THEN 'NÃO POSSUI TITULO ATIVO' */
    WHEN B.QUARENTENA IS NULL OR B.QUARENTENA = 1 THEN 'EM QUARENTENA'
    WHEN B.NAO_IMPORTUNE IS NULL OR B.NAO_IMPORTUNE = 1 THEN 'NÃO IMPORTUNE'
    WHEN B.NAO_DESEJA_RECEBER_TODOS_MEIOS IS NULL OR B.NAO_DESEJA_RECEBER_TODOS_MEIOS = 1 THEN 'NÃO DESEJA RECEBER TODOS OS MEIOS'
    WHEN ISNULL(B.NAO_DESEJA_RECEBER_EMAIL, 1) = 1 AND ISNULL(B.NAO_DESEJA_RECEBER_SMS, 1) = 1 THEN 'NÃO DESEJA RECEBER SMS E EMAIL'
    WHEN ISNULL(B.EMAIL_VALIDO, 0) = 0 AND ISNULL(B.CELULAR_VALIDO, 0) = 0 THEN 'EMAIL E CELULAR INVÁLIDO'
  END AS RESULTADO
FROM
  TB_BOAS_VINDAS_OUROCAP_COMOTC_NEOBPO B
LEFT JOIN CAMPAIGN_SALESFORCE CMP ON B.ID_CAMPANHA = CMP.ID
LEFT JOIN HC_PARCEIRO__C_SALESFORCE PAR ON B.PARCEIRO = PAR.ID
LEFT JOIN HC_RELACAO_CLIENTE_PARCEIRO__C_SALESFORCE REL ON B.ID_CLIENTE_PARCEIRO = REL.ID
WHERE
  B.CPF_CNPJ IS NOT NULL
  AND (
    /* (B.IDADE_VALIDA IS NULL OR B.IDADE_VALIDA = 0) */
    /* OR (B.CONSELHEIRO IS NULL OR B.CONSELHEIRO = 1) */
    /* OR (B.CLIENTE_PEP IS NULL OR B.CLIENTE_PEP = 1) */
    /* OR (B.DESEJA_CONTATO_TELEFONICO IS NULL OR B.DESEJA_CONTATO_TELEFONICO = 1) */
    /* OR (B.POSSUI_TELEFONE_ATIVO IS NULL OR B.POSSUI_TELEFONE_ATIVO = 0) */
    /* OR (B.POSSUI_CONTA_CORRENTE IS NULL OR B.POSSUI_CONTA_CORRENTE = 0) */
    /* OR (B.COMPRA_UTIMOS_30_DIAS IS NULL OR B.COMPRA_UTIMOS_30_DIAS = 1) */
    /* OR (B.POSSUI_TITULO_ATIVO IS NULL OR B.POSSUI_TITULO_ATIVO = 0) */
    (B.QUARENTENA IS NULL OR B.QUARENTENA = 1)
    OR (B.NAO_IMPORTUNE IS NULL OR B.NAO_IMPORTUNE = 1)
    OR (B.NAO_DESEJA_RECEBER_TODOS_MEIOS IS NULL OR B.NAO_DESEJA_RECEBER_TODOS_MEIOS = 1)
    OR (
      ISNULL(B.NAO_DESEJA_RECEBER_EMAIL, 1) = 1
      AND ISNULL(B.NAO_DESEJA_RECEBER_SMS, 1) = 1
    )
    OR (
      ISNULL(B.EMAIL_VALIDO, 0) = 0
      AND ISNULL(B.CELULAR_VALIDO, 0) = 0
    )
  )