SELECT
  CON.CPF,
  CMEM.ID AS ID_MEMBRO_CAMPANHA
FROM [TB_BASE_PROSPECT_OTC291_FILTRADA_TEO] CON
LEFT JOIN CAMPAIGNMEMBER_SALESFORCE CMEM ON CMEM.CAMPAIGNID = CON.ID_CAMPANHA 
  AND CMEM.CONTACTID = CON.ID_CONTATO
WHERE
  CMEM.ID IS NOT NULL