
SELECT DISTINCT
GmailD5S4.CPF,
GmailD5S4.NOME,
GmailD5S4.EMAIL,
GmailD5S4.EMAIL_VALIDO,
CASE

  WHEN CHARINDEX(' ', GmailD5S4.NOME) = 0 THEN GmailD5S4.NOME

  ELSE SUBSTRING( GmailD5S4.NOME , 1, CHARINDEX(' ', GmailD5S4.NOME) )

END AS PNOME
FROM Gmail_DIV05_SUB04 GmailD5S4
UNION
SELECT DISTINCT
MicrosodftD5S4.CPF,
MicrosodftD5S4.NOME,
MicrosodftD5S4.EMAIL,
MicrosodftD5S4.EMAIL_VALIDO,
CASE

  WHEN CHARINDEX(' ', MicrosodftD5S4.NOME) = 0 THEN MicrosodftD5S4.NOME

  ELSE SUBSTRING( MicrosodftD5S4.NOME , 1, CHARINDEX(' ', MicrosodftD5S4.NOME) )

END AS PNOME
FROM Microsoft_DIV05_SUB04 MicrosodftD5S4
UNION
SELECT DISTINCT
YahooD5S4.CPF,
YahooD5S4.NOME,
YahooD5S4.EMAIL,
YahooD5S4.EMAIL_VALIDO,
CASE

  WHEN CHARINDEX(' ', YahooD5S4.NOME) = 0 THEN YahooD5S4.NOME

  ELSE SUBSTRING( YahooD5S4.NOME , 1, CHARINDEX(' ', YahooD5S4.NOME) )

END AS PNOME
FROM Yahoo_DIV05_SUB04 YahooD5S4
UNION
SELECT DISTINCT
OutrosD5S4.CPF,
OutrosD5S4.NOME,
OutrosD5S4.EMAIL,
OutrosD5S4.EMAIL_VALIDO,
CASE

  WHEN CHARINDEX(' ', OutrosD5S4.NOME) = 0 THEN OutrosD5S4.NOME

  ELSE SUBSTRING( OutrosD5S4.NOME , 1, CHARINDEX(' ', OutrosD5S4.NOME) )

END AS PNOME
FROM Outros_DIV05_SUB04 OutrosD5S4
