SELECT
  CODIGO_PARCEIRO,
  ID_CLIENTE,
  CODIGO_MCI,
  TIPO_PESSOA,
  CODIGO_CIC,
  DT_NASCIMENTO,
  NOME,
  SEXO,
  UF_RESIDENCIAL,
  DDD1 AS DDD_TEL_01,
  TELEFONE1 AS TEL_01,
  TIPO_TEL_01,
  DDD2 AS DDD_TEL_02,
  TELEFONE2 AS TEL_02,
  TIPO_TEL_02,
  DDD3 AS DDD_TEL_03,
  TELEFONE3 AS TEL_03,
  TIPO_TEL_03,
  CODIGO_PLANO,
  ORIGEM_SOLICITACAO,
  FILLER,
  CODIGO_RNA,
  VALOR_RENDIMENTOS,
  TIPO_CARTEIRA,
  NIVEL_RELACIONAMENTO,
  DATA_INFORMACAO,
  FILLER2,
  CPF AS CPF_CNPJ,
  PRIMEIRO_NOME,
  SOBRENOME,
  DT_NASCIMENTO_SF,
  FAIXA_RENDA_MENSAL,
  ALTA_RENDA,
  DDD4 AS DDD_TEL_04,
  TELEFONE4 AS TEL_04,
  TIPO_TEL_04,
  DDD5 AS DDD_TEL_05,
  TELEFONE5 AS TEL_05,
  TIPO_TEL_05,
  DDD6 AS DDD_TEL_06,
  TELEFONE6 AS TEL_06,
  TIPO_TEL_06,
  TIPO_CAMPANHA,
  ID_CAMPANHA,
  ID_CLIENTE_PARCEIRO,
  ID_CONTATO,
  CASE 
	WHEN LEN(TELEFONE4) = 9 AND LEN(DDD4) = 2 AND CXP.HC_STATUS_CELULAR_1__C = 'VÁLIDO' THEN CONCAT('55', DDD4, TELEFONE4)
	WHEN LEN(TELEFONE5) = 9 AND LEN(DDD5) = 2 AND CXP.HC_STATUS_CELULAR_2__C = 'VÁLIDO' THEN CONCAT('55', DDD5, TELEFONE5)
	WHEN LEN(TELEFONE6) = 9 AND LEN(DDD6) = 2 AND CXP.HC_STATUS_CELULAR_3__C = 'VÁLIDO' THEN CONCAT('55', DDD6, TELEFONE6)
    ELSE NULL
  END AS CELULAR_MKT_CLOUD,
  'BR' AS LOCALE
FROM
  TB_BASE_FIM_PLANO_OUROCAP_PU_PP_OTC291_TRATADA_NEOBPO A
  /* CHECAGEM SE TOODS OS CONTATOS TIVERAM O OTC TRATADO */
  LEFT OUTER JOIN
    (
      SELECT
        COUNT(1) AS CPFS_FALTANDO_NO_OTC 
      FROM
        TB_BASE_FIM_PLANO_OUROCAP_PU_PP_COMOTC_NEOBPO_FILTRADA ENV 
        LEFT JOIN
          TB_BASE_FIM_PLANO_OUROCAP_PU_PP_OTC291_TRATADA_NEOBPO RET 
          ON ENV.CPF_CNPJ = RET.CPF 
      WHERE
        RET.CPF IS NULL 
    ) B 
    ON 1 = 1
  LEFT JOIN
    HC_RELACAO_CLIENTE_PARCEIRO__C_SALESFORCE CXP
    ON A.ID_CLIENTE_PARCEIRO = CXP.ID
WHERE
  B.CPFS_FALTANDO_NO_OTC <= 11 /* SIGNIFICA QUE TODOS OS CONTATOS JÁ ESTÃO NO OTC291 */
  /* VALIDAÇÕES POR CONTATO DO OTC */
  /*AND A.CODIGO_RNA = '000' */
  AND A.ALTA_RENDA = 0