
SELECT DISTINCT
GmailD4S4.CPF,
GmailD4S4.NOME,
GmailD4S4.EMAIL,
GmailD4S4.EMAIL_VALIDO,
CASE

  WHEN CHARINDEX(' ', GmailD4S4.NOME) = 0 THEN GmailD4S4.NOME

  ELSE SUBSTRING( GmailD4S4.NOME , 1, CHARINDEX(' ', GmailD4S4.NOME) )

END AS PNOME
FROM Gmail_DIV04_SUB04 GmailD4S4
UNION
SELECT DISTINCT
MicrosodftD4S4.CPF,
MicrosodftD4S4.NOME,
MicrosodftD4S4.EMAIL,
MicrosodftD4S4.EMAIL_VALIDO,
CASE

  WHEN CHARINDEX(' ', MicrosodftD4S4.NOME) = 0 THEN MicrosodftD4S4.NOME

  ELSE SUBSTRING( MicrosodftD4S4.NOME , 1, CHARINDEX(' ', MicrosodftD4S4.NOME) )

END AS PNOME
FROM Microsoft_DIV04_SUB04 MicrosodftD4S4
UNION
SELECT DISTINCT
YahooD4S4.CPF,
YahooD4S4.NOME,
YahooD4S4.EMAIL,
YahooD4S4.EMAIL_VALIDO,
CASE

  WHEN CHARINDEX(' ', YahooD4S4.NOME) = 0 THEN YahooD4S4.NOME

  ELSE SUBSTRING( YahooD4S4.NOME , 1, CHARINDEX(' ', YahooD4S4.NOME) )

END AS PNOME
FROM Yahoo_DIV04_SUB04 YahooD4S4
UNION
SELECT DISTINCT
OutrosD4S4.CPF,
OutrosD4S4.NOME,
OutrosD4S4.EMAIL,
OutrosD4S4.EMAIL_VALIDO,
CASE

  WHEN CHARINDEX(' ', OutrosD4S4.NOME) = 0 THEN OutrosD4S4.NOME

  ELSE SUBSTRING( OutrosD4S4.NOME , 1, CHARINDEX(' ', OutrosD4S4.NOME) )

END AS PNOME
FROM Outros_DIV04_SUB04 OutrosD4S4
