SELECT
    S.MobileMessageTrackingID,
    S.EID,
    S.MID,
    S.Mobile,
    S.MessageID,
    S.KeywordID,
    S.CodeID,
    S.ConversationID,
    S.ConversationStateID,
    S.CampaignID,
    S.Sent,
    S.Delivered,
    S.Undelivered,
    S.Outbound,
    S.Inbound,
    S.CreateDateTime,
    S.ModifiedDateTime,
    S.ActionDateTime,
    REPLACE(REPLACE(S.MessageText, CHAR(13), ' '),  Char(10), ' ') AS MessageText,
    S.IsTest,
    S.MobileMessageRecurrenceID,
    S.ResponseToMobileMessageTrackingID,
    S.IsValid,
    S.InvalidationCode,
    S.SendID,
    S.SendSplitID,
    S.SendSegmentID,
    S.SendJobID,
    S.SendGroupID,
    S.SendPersonID,
    S.SubscriberID,
    S.SubscriberKey,
    S.SMSStandardStatusCodeId,
    S.Description,
    S.Name,
    S.ShortCode,
    S.SharedKeyword,
    S.Ordinal,
    S.FromName,
    S.JBActivityID,
    S.JBDefinitionID,
    C.HC_CPF_CNPJ__c AS CPF
FROM _SMSMESSAGETRACKING S
LEFT JOIN Contact_Salesforce C ON C.Id = S.SubscriberKey
WHERE
    S.CreateDateTime >= '2023-01-01'