select  HC_Banco_1__c, 
        HC_Agencia_1__c, 
        HC_Digito_da_Agencia_1__c, 
        HC_Numero_da_Conta_1__c, 
        HC_Digito_da_Conta_1__c, 
        HC_Banco_2__c, 
        HC_Agencia_2__c,
        HC_Digito_da_Agencia_2__c, 
        HC_Numero_da_Conta_2__c, 
        HC_Digito_da_Conta_2__c,
        HC_Telefone_Comercial__c, 
        HC_Telefone_Outro__c, 
        HC_Telefone_Residencial__c, 
        HC_Status_Tel_Comercial__c, 
        HC_Status_Tel_Outro__c, 
        HC_Celular_1__c, 
        HC_Celular_2__c, 
        HC_Celular_3__c,  
        HC_Email_Brasilcap__c, 
        HC_Email_Pessoal__c, 
        HC_Email_Principal__c, 
        HC_Endereco_Comercial__c, 
        HC_Endereco_Correspondencia__c, 
        HC_Endereco_Outro__c, 
        HC_Endereco_Principal__c, 
        HC_Endereco_Residencial__c, 
        CPF_CNPJ_Cliente__c, 
        HC_Id_Parceiro_Cap__c
from HC_Relacao_Cliente_Parceiro__c_SALESFORCE
inner join ClientesSemContaTelefoneImportar
    ON HC_CPF_CNPJ_Codigo_Parceiro_Unico__c = CHAVE_CLIENTE_SALESFORCE