SELECT 
    B.ID,
    b.CPF_CNPJ,
    CASE WHEN DATEDIFF(DD,MAX(C.HC_CONTRATACAO__C), GETDATE()) <= B.MESES_COMPRA_EXCLUSAO /*AND UPPER(D.HC_FAMILIA_DO_PRODUTO__C) = 'OUROCAP'*/ THEN 1 ELSE 0 END AS COMPRA_RECENTE_OUROCAP
FROM TB_BASE_FIM_PLANO_OUROCAP_PU_PP_COMOTC_NEOBPO B
INNER JOIN HC_TITULO__C_SALESFORCE C ON B.ID_CLIENTE_PARCEIRO = C.HC_CLIENTE_X_PARCEIRO__C
GROUP BY B.ID, b.cpf_cnpj, B.MESES_COMPRA_EXCLUSAO