SELECT DISTINCT
  B.HC_CPF_CNPJ__C AS CPF_CNPJ,
  C.NAME AS NOME,
  B.HC_IDADE__C AS IDADE,
  B.HC_DATA_DE_NASCIMENTO__C AS DT_NASCIMENTO,
  B.HC_GENERO_DO_CLIENTE__C AS SEXO,
  B.HC_TIPO_DE_PESSOA__C AS TIPO_PESSOA,
  LEFT(REPLACE(REPLACE(REPLACE(REPLACE(B.HC_TELEFONE_RESIDENCIAL__C, '(', ''), ')', ''), ' ', ''), '-', ''), 2) AS DDD_TEL_01, 
  SUBSTRING(REPLACE(REPLACE(REPLACE(REPLACE(B.HC_TELEFONE_RESIDENCIAL__C, '(', ''), ')', ''), ' ', ''), '-', ''), 3, 9) AS TEL_01, 
  'FIXO' AS TIPO_TEL_01, 
  LEFT(REPLACE(REPLACE(REPLACE(REPLACE(B.HC_TELEFONE_COMERCIAL__C, '(', ''), ')', ''), ' ', ''), '-', ''), 2) AS DDD_TEL_02, 
  SUBSTRING(REPLACE(REPLACE(REPLACE(REPLACE(B.HC_TELEFONE_COMERCIAL__C, '(', ''), ')', ''), ' ', ''), '-', ''), 3, 9) AS TEL_02, 
  'FIXO' AS TIPO_TEL_02, 
  LEFT(REPLACE(REPLACE(REPLACE(REPLACE(B.HC_TELEFONE_OUTRO__C, '(', ''), ')', ''), ' ', ''), '-', ''), 2) AS DDD_TEL_03, 
  SUBSTRING(REPLACE(REPLACE(REPLACE(REPLACE(B.HC_TELEFONE_OUTRO__C, '(', ''), ')', ''), ' ', ''), '-', ''), 3, 9) AS TEL_03, 
  'FIXO' AS TIPO_TEL_03, 
  LEFT(REPLACE(REPLACE(REPLACE(REPLACE(B.HC_CELULAR_1__C, '(', ''), ')', ''), ' ', ''), '-', ''), 2) AS DDD_TEL_04, 
  SUBSTRING(REPLACE(REPLACE(REPLACE(REPLACE(B.HC_CELULAR_1__C, '(', ''), ')', ''), ' ', ''), '-', ''), 3, 9) AS TEL_04, 
  'MÓVEL' AS TIPO_TEL_04, 
  LEFT(REPLACE(REPLACE(REPLACE(REPLACE(B.HC_CELULAR_2__C, '(', ''), ')', ''), ' ', ''), '-', ''), 2) AS DDD_TEL_05, 
  SUBSTRING(REPLACE(REPLACE(REPLACE(REPLACE(B.HC_CELULAR_2__C, '(', ''), ')', ''), ' ', ''), '-', ''), 3, 9) AS TEL_05, 
  'MÓVEL' AS TIPO_TEL_05, 
  LEFT(REPLACE(REPLACE(REPLACE(REPLACE(B.HC_CELULAR_3__C, '(', ''), ')', ''), ' ', ''), '-', ''), 2) AS DDD_TEL_06, 
  SUBSTRING(REPLACE(REPLACE(REPLACE(REPLACE(B.HC_CELULAR_3__C, '(', ''), ')', ''), ' ', ''), '-', ''), 3, 9) AS TEL_06, 
  'MÓVEL' AS TIPO_TEL_06, 
  B.HC_TELEFONE_PRINCIPAL__C AS TEL_PRINCIPAL,
  B.HC_CLASSIFICACAO__C AS PUBLICO_ALVO, 
  A.[TYPE] AS TIPO_CAMPANHA,
  B.HC_PARCEIRO__C AS PARCEIRO,
  GETDATE() AS DT_CRIACAO_MAILING,
  A.STARTDATE AS DT_INICIO_MAILING, 
  A.ENDDATE AS DT_FIM_MAILING, 
  A.ID AS ID_CAMPANHA, 
  A.HC_PRODUTO__C AS ID_PRODUTO, 
  A.HC_PRECO_DO_PRODUTO__C AS ID_PRODUTO_VALOR, 
  B.HC_CPF_CNPJ__C AS ID, 
  B.ID AS ID_CLIENTE_PARCEIRO,
  B.HC_CPF_CNPJ_CODIGO_DO_PARCEIRO__C AS CPF_CNPJ_CODIGO_DO_PARCEIRO, 
  C.ID AS ID_CONTATO, 
  B.HC_CLIENTE__C AS ID_CLIENTE, 
  CASE 
  	WHEN UPPER(B.HC_ENDERECO_PRINCIPAL__C) = 'RESIDENCIAL' THEN HC_ENDERECO_RESIDENCIAL__C
  	WHEN UPPER(B.HC_ENDERECO_PRINCIPAL__C) = 'COMERCIAL' THEN HC_ENDERECO_COMERCIAL__C
  	WHEN UPPER(B.HC_ENDERECO_PRINCIPAL__C) = 'CORRESPONDÊNCIA' THEN HC_ENDERECO_CORRESPONDENCIA__C
  END AS ENDERECO,
  CASE 
  	WHEN UPPER(B.HC_ENDERECO_PRINCIPAL__C) = 'RESIDENCIAL' THEN HC_UF_RES__C
  	WHEN UPPER(B.HC_ENDERECO_PRINCIPAL__C) = 'COMERCIAL' THEN HC_UF_COM__C
  	WHEN UPPER(B.HC_ENDERECO_PRINCIPAL__C) = 'CORRESPONDÊNCIA' THEN HC_UF_COR__C
  END AS UF,
  CASE 
  	WHEN UPPER(B.HC_ENDERECO_PRINCIPAL__C) = 'RESIDENCIAL' THEN HC_CEP_RES__C
  	WHEN UPPER(B.HC_ENDERECO_PRINCIPAL__C) = 'COMERCIAL' THEN HC_CEP_COM__C
  	WHEN UPPER(B.HC_ENDERECO_PRINCIPAL__C) = 'CORRESPONDÊNCIA' THEN HC_CEP_COR__C
  END AS CEP,
  D.HC_GARANTIA_INICIO__C AS DT_INICIO_GARANTIA,
  D.HC_NUMERO_DO_TITULO__C AS NUMERO_TITULO,
  D.HC_SERIE__C AS SERIE_TITULO,
  D.HC_PLANO__C AS PLANO_TITULO,
    CASE
    WHEN DATEPART(WEEKDAY, GETDATE()) = 5 THEN DATEADD(DAY, 3, DATEADD(HH, 3, A.HC_DATA_DE_EXECUCAO__C)) 
    ELSE DATEADD(DAY, A.HC_PROXIMA_EXECUCAO__C, DATEADD(HH, 3, A.HC_DATA_DE_EXECUCAO__C)) 
    END AS DATA_PROXIMA_EXECUCAO 
FROM
  CAMPAIGN_SALESFORCE A WITH(NOLOCK) 
  INNER JOIN
    HC_RELACAO_CLIENTE_PARCEIRO__C_SALESFORCE B WITH(NOLOCK) 
    ON A.HC_PARCEIRO__C = B.HC_PARCEIRO__C 
    AND A.HC_TIPO_DE_CLIENTE__C = B.HC_TIPO_DE_PESSOA__C 
  INNER JOIN
    CONTACT_SALESFORCE C WITH(NOLOCK) 
    ON C.HC_CPF_CNPJ__C = B.HC_CPF_CNPJ__C 
  INNER JOIN
    HC_TITULO__C_SALESFORCE D WITH(NOLOCK) 
    ON D.HC_CLIENTE_X_PARCEIRO__C = B.ID 
WHERE
  UPPER(A.[TYPE]) = 'AUTOMÁTICO' 
  AND UPPER(A.HC_FORMATO__C) = 'SMS' 
  AND A.ISACTIVE = 1 
  AND CONVERT(VARCHAR, D.HC_GARANTIA_INICIO__C, 23) BETWEEN CONVERT(VARCHAR, D.HC_GARANTIA_INICIO__C, 23) AND CONVERT(VARCHAR, D.HC_GARANTIA_FIM__C, 23)