SELECT  
  B.HC_CPF_CNPJ__C AS CPF_CNPJ,
  C.NAME AS NOME,
  CASE
    WHEN B.HC_EMAIL_PRINCIPAL__C = 'Brasilcap' THEN HC_EMAIL_BRASILCAP__C
    WHEN B.HC_EMAIL_PRINCIPAL__C = 'Comercial' THEN HC_EMAIL_COMERCIAL__C
    WHEN B.HC_EMAIL_PRINCIPAL__C = 'Pessoal' THEN HC_EMAIL_PESSOAL__C
    WHEN B.HC_EMAIL_BRASILCAP__C IS NOT NULL THEN HC_EMAIL_BRASILCAP__C
    WHEN B.HC_EMAIL_COMERCIAL__C IS NOT NULL THEN HC_EMAIL_COMERCIAL__C
    WHEN B.HC_EMAIL_PESSOAL__C IS NOT NULL THEN HC_EMAIL_PESSOAL__C
    ELSE NULL
  END AS EMAIL,
  CASE
    WHEN B.HC_EMAIL_PRINCIPAL__C IN ('Brasilcap', 'Comercial', 'Pessoal') THEN 1
    WHEN B.HC_EMAIL_BRASILCAP__C IS NOT NULL THEN 1
    WHEN B.HC_EMAIL_COMERCIAL__C IS NOT NULL THEN 1
    WHEN B.HC_EMAIL_PESSOAL__C IS NOT NULL THEN 1
    ELSE 0
  END AS EMAIL_VALIDO,
  CASE
    WHEN B.HC_TELEFONE_PRINCIPAL__C = 'CELULAR 1' THEN HC_CELULAR_1__C
    WHEN B.HC_TELEFONE_PRINCIPAL__C = 'CELULAR 2' THEN HC_CELULAR_2__C
    WHEN B.HC_TELEFONE_PRINCIPAL__C = 'CELULAR 3' THEN HC_CELULAR_3__C
    WHEN B.HC_TELEFONE_PRINCIPAL__C = 'CELULAR 3_3' THEN HC_CELULAR_3_3__C
    WHEN B.HC_TELEFONE_PRINCIPAL__C = 'CELULAR 4' THEN HC_CELULAR_4__C
    WHEN B.HC_STATUS_CELULAR_1__C = 'VÁLIDO' THEN HC_CELULAR_1__C
    WHEN B.HC_STATUS_CELULAR_2__C = 'VÁLIDO' THEN HC_CELULAR_2__C
    WHEN B.HC_STATUS_CELULAR_3__C = 'VÁLIDO' THEN HC_CELULAR_3__C
    WHEN B.HC_STATUS_CELULAR_3_3__C = 'VÁLIDO' THEN HC_CELULAR_3_3__C
    WHEN B.HC_STATUS_CELULAR_4__C = 'VÁLIDO' THEN HC_CELULAR_4__C
    ELSE NULL
  END AS CELULAR,
  CASE
    WHEN B.HC_STATUS_CELULAR_1__C = 'VÁLIDO' THEN 1
    WHEN B.HC_STATUS_CELULAR_2__C = 'VÁLIDO' THEN 1
    WHEN B.HC_STATUS_CELULAR_3__C = 'VÁLIDO' THEN 1
    WHEN B.HC_STATUS_CELULAR_3_3__C = 'VÁLIDO' THEN 1
    WHEN B.HC_STATUS_CELULAR_4__C = 'VÁLIDO' THEN 1
    ELSE 0
  END AS CELULAR_VALIDO,
  B.HC_NAO_DESEJA_RECEBER_SMS__C AS NAO_DESEJA_RECEBER_SMS,
  B.HC_NAO_DESEJA_RECEBER_EMAIL__C AS NAO_DESEJA_RECEBER_EMAIL,
  A.ID AS ID_CAMPANHA, 
  A.PARENTID AS ID_CAMPANHA_PAI,
  B.ID AS ID_CLIENTE_PARCEIRO,
  C.ID AS ID_CONTATO,
  PROD.PARCEIRO__C as NOME_PARCEIRO, 
  PROP.ID AS ID_PROPOSTA,
  PROP.CREATEDDATE,
  PROP.DATA_ORIGEM_VENDA_AGENDADA__C,
  PROP.ORIGEM_VENDA_AGENDADA__C,
  PROP.QUANTIDADE_VENDA_AGENDADA__C,
  PROP.NUMERO_VENDA_AGENDADA__C, 
  PROP.ID_VENDA_AGENDADA__C
FROM CAMPAIGN_SALESFORCE A
INNER JOIN HC_RELACAO_CLIENTE_PARCEIRO__C_SALESFORCE B ON A.HC_PARCEIRO__C = B.HC_PARCEIRO__C
INNER JOIN CONTACT_SALESFORCE C ON C.HC_CPF_CNPJ__C = B.HC_CPF_CNPJ__C
INNER JOIN HC_PROPOSTA__C_SALESFORCE PROP ON B.ID = PROP.HC_TITULAR__C
INNER JOIN HC_PRODUTO__C_SALESFORCE  PROD ON PROP.HC_Produto_Relacionado__c = PROD.ID
WHERE
    PROD.HC_FAMILIA_DO_PRODUTO__c = 'Doadin'
    AND PROP. CREATEDDATE > GETDATE() - 35