
SELECT DISTINCT
GmailD4S3.CPF,
GmailD4S3.NOME,
GmailD4S3.EMAIL,
GmailD4S3.EMAIL_VALIDO,
CASE

  WHEN CHARINDEX(' ', GmailD4S3.NOME) = 0 THEN GmailD4S3.NOME

  ELSE SUBSTRING( GmailD4S3.NOME , 1, CHARINDEX(' ', GmailD4S3.NOME) )

END AS PNOME
FROM Gmail_DIV04_SUB03 GmailD4S3
UNION
SELECT DISTINCT
MicrosodftD4S3.CPF,
MicrosodftD4S3.NOME,
MicrosodftD4S3.EMAIL,
MicrosodftD4S3.EMAIL_VALIDO,
CASE

  WHEN CHARINDEX(' ', MicrosodftD4S3.NOME) = 0 THEN MicrosodftD4S3.NOME

  ELSE SUBSTRING( MicrosodftD4S3.NOME , 1, CHARINDEX(' ', MicrosodftD4S3.NOME) )

END AS PNOME
FROM Microsoft_DIV04_SUB03 MicrosodftD4S3
UNION
SELECT DISTINCT
YahooD4S3.CPF,
YahooD4S3.NOME,
YahooD4S3.EMAIL,
YahooD4S3.EMAIL_VALIDO,
CASE

  WHEN CHARINDEX(' ', YahooD4S3.NOME) = 0 THEN YahooD4S3.NOME

  ELSE SUBSTRING( YahooD4S3.NOME , 1, CHARINDEX(' ', YahooD4S3.NOME) )

END AS PNOME
FROM Yahoo_DIV04_SUB03 YahooD4S3
UNION
SELECT DISTINCT
OutrosD4S3.CPF,
OutrosD4S3.NOME,
OutrosD4S3.EMAIL,
OutrosD4S3.EMAIL_VALIDO,
CASE

  WHEN CHARINDEX(' ', OutrosD4S3.NOME) = 0 THEN OutrosD4S3.NOME

  ELSE SUBSTRING( OutrosD4S3.NOME , 1, CHARINDEX(' ', OutrosD4S3.NOME) )

END AS PNOME
FROM Outros_DIV04_SUB03 OutrosD4S3
