SELECT
  A.CPF_CNPJ AS ID,
	CASE 
    WHEN Q.CPF_CNPJ IS NOT NULL 
      AND DATA_PARTICIPACAO_CAMPANHA > DATEADD(DD, -90, GETDATE()) THEN 1
  ELSE 0 END AS QUARENTENA
FROM
	TB_BASE_EX_CLIENTE_COMOTC_NEOBPO A
LEFT JOIN TB_BASE_QUARENTENA Q ON A.CPF_CNPJ = Q.CPF_CNPJ