SELECT DISTINCT
  'TCBB' AS COD_PARCEIRO,
  B.CPF_CNPJ AS CPF,
  '' AS CNPJ,
  CASE WHEN LEN(B.TEL_01) >= 9 THEN 'MÓVEL' ELSE 'FIXO' END AS TIPO,
  B.DDD_TEL_01 AS DDD,
  B.TEL_01 AS TELEFONE
FROM
  TB_BASE_EX_CLIENTE_OTC291_FILTRADA_ALGAR A
  INNER JOIN Tb_Base_Ex_Cliente_ComOTC_Algar_Filtrada B 
    ON A.CPF = B.CPF_CNPJ
WHERE
  LEN(NULLIF(TEL_01, '')) < 10
  AND NOT( LEN(TEL_01) = 8 AND TEL_01 LIKE '9%' )

UNION ALL

SELECT DISTINCT
  'TCBB' AS COD_PARCEIRO,
  B.CPF_CNPJ AS CPF,
  '' AS CNPJ,
  CASE WHEN LEN(B.TEL_02) >= 9 THEN 'MÓVEL' ELSE 'FIXO' END AS TIPO,
  B.DDD_TEL_02 AS DDD,
  B.TEL_02 AS TELEFONE
FROM
  TB_BASE_EX_CLIENTE_OTC291_FILTRADA_ALGAR A 
  INNER JOIN
    Tb_Base_Ex_Cliente_ComOTC_Algar_Filtrada B 
    ON A.CPF = B.CPF_CNPJ
WHERE
  LEN(NULLIF(TEL_02, '')) < 10
  AND NOT( LEN(TEL_02) = 8 AND TEL_02 LIKE '9%' )

UNION ALL

SELECT DISTINCT
  'TCBB' AS COD_PARCEIRO,
  B.CPF_CNPJ AS CPF,
  '' AS CNPJ,
  CASE WHEN LEN(B.TEL_03) >= 9 THEN 'MÓVEL' ELSE 'FIXO' END AS TIPO,
  B.DDD_TEL_03 AS DDD,
  B.TEL_03 AS TELEFONE
FROM
  TB_BASE_EX_CLIENTE_OTC291_FILTRADA_ALGAR A 
  INNER JOIN
    Tb_Base_Ex_Cliente_ComOTC_Algar_Filtrada B 
    ON A.CPF = B.CPF_CNPJ
WHERE
  LEN(NULLIF(TEL_03, '')) < 10
  AND NOT( LEN(TEL_03) = 8 AND TEL_03 LIKE '9%' )

UNION ALL

SELECT DISTINCT
  'TCBB' AS COD_PARCEIRO,
  B.CPF_CNPJ AS CPF,
  '' AS CNPJ,
  CASE WHEN LEN(B.TEL_04) >= 9 THEN 'MÓVEL' ELSE 'FIXO' END AS TIPO,
  B.DDD_TEL_04 AS DDD,
  B.TEL_04 AS TELEFONE
FROM
  TB_BASE_EX_CLIENTE_OTC291_FILTRADA_ALGAR A 
  INNER JOIN
    Tb_Base_Ex_Cliente_ComOTC_Algar_Filtrada B 
    ON A.CPF = B.CPF_CNPJ
WHERE
  LEN(NULLIF(TEL_04, '')) < 10
  AND NOT( LEN(TEL_04) = 8 AND TEL_04 LIKE '9%' )

UNION ALL

SELECT DISTINCT
  'TCBB' AS COD_PARCEIRO,
  B.CPF_CNPJ AS CPF,
  '' AS CNPJ,
  CASE WHEN LEN(B.TEL_05) >= 9 THEN 'MÓVEL' ELSE 'FIXO' END AS TIPO,
  B.DDD_TEL_05 AS DDD,
  B.TEL_05 AS TELEFONE
FROM
  TB_BASE_EX_CLIENTE_OTC291_FILTRADA_ALGAR A 
  INNER JOIN
    Tb_Base_Ex_Cliente_ComOTC_Algar_Filtrada B 
    ON A.CPF = B.CPF_CNPJ
WHERE
  LEN(NULLIF(TEL_05, '')) < 10
  AND NOT( LEN(TEL_05) = 8 AND TEL_05 LIKE '9%' )

UNION ALL

SELECT DISTINCT
  'TCBB' AS COD_PARCEIRO,
  B.CPF_CNPJ AS CPF,
  '' AS CNPJ,
  CASE WHEN LEN(B.TEL_06) >= 9 THEN 'MÓVEL' ELSE 'FIXO' END AS TIPO,
  B.DDD_TEL_06 AS DDD,
  B.TEL_06 AS TELEFONE
FROM
  TB_BASE_EX_CLIENTE_OTC291_FILTRADA_ALGAR A 
  INNER JOIN
    Tb_Base_Ex_Cliente_ComOTC_Algar_Filtrada B 
    ON A.CPF = B.CPF_CNPJ
WHERE
  LEN(NULLIF(TEL_06, '')) < 10
  AND NOT( LEN(TEL_06) = 8 AND TEL_06 LIKE '9%' )