SELECT 
  A.*,
  C.ID_CONTATO AS CONTACTID
FROM Tb_Recuperacao_Caducidade_OTC291_Tratada A
/* CHECAGEM SE TOODS OS CONTATOS TIVERAM O OTC TRATADO */
LEFT OUTER JOIN ( 
  SELECT
    COUNT(1) as CPFS_FALTANDO_NO_OTC
  FROM Tb_Recuperacao_Caducidade_Tratada ENV 
  LEFT JOIN TB_BASE_CLIENTE_OTC291_TRATADA_NEOBPO RET ON ENV.CPF_CNPJ = RET.CPF
  WHERE RET.CPF IS NULL 
) B ON 1 = 1
INNER JOIN Tb_Recuperacao_Caducidade_Tratada C ON C.CPF_CNPJ = A.CPF
WHERE 
/* SIGNIFICA QUE TODOS OS CONTATOS JÁ ESTÃO NO OTC291 */
  /*B.CPFS_FALTANDO_NO_OTC = 0*/
  /* VALIDAÇÕES POR CONTATO DO OTC */
   A.CODIGO_RNA = '000'
  AND A.ALTA_RENDA = 0
  /* AND A.Nivel_Relacionamento  IN ('2112',  '2202', '2602', '02112',  '02202', '02602') */