SELECT
 A.*
FROM TB_BASE_PROSPECT_COMOTC_TRATADA_TEO A
WHERE A.IDADE_VALIDA = 1
  AND A.CONTA_CORRENTE = 1
  AND A.CONSELHEIRO = 0 
  AND A.QUARENTENA = 0
  /* AND A.CLIENTE = 0 */
  /* AND A.VALIDA_RNA = 1 */
  AND A.CEP_VALIDO = 1
  AND A.NAO_IMPORTUNE = 0