SELECT
  ORIGEM.CPF_CNPJ,
  CMP.NAME AS CAMPANHA,
  PAR.HC_CODIGO_DO_PARCEIRO_CAP__C AS PARCEIRO,
  CONVERT(INTEGER, REL.HC_IDADE__C) AS  IDADE,
  /* ORIGEM.COMPRA_UTIMOS_30_DIAS AS COMPROU_ULTIMOS_30_DIAS, */
  ORIGEM.CONSELHEIRO,
  ORIGEM.CLIENTE_PEP,
  ORIGEM.DESEJA_CONTATO_TELEFONICO AS NAO_DESEJA_RECEBER_LIGACOES,
  ORIGEM.POSSUI_TELEFONE_ATIVO,
  ORIGEM.POSSUI_CONTA_ATIVA,
  ORIGEM.QUARENTENA,
  ORIGEM.COMPRA_RECENTE_OUROCAP,
  ORIGEM.NAO_IMPORTUNE,
  OTC291.CODIGO_RNA,
  OTC291.ALTA_RENDA,
  CASE
    WHEN OTC291.CODIGO_RNA IS NULL OR OTC291.CODIGO_RNA != '000' THEN 'EXCLUIDO RNA'
    WHEN OTC291.ALTA_RENDA IS NULL OR OTC291.ALTA_RENDA != 0 THEN 'ALTA RENDA'
    WHEN ORIGEM.QUARENTENA IS NULL OR ORIGEM.QUARENTENA != 0 THEN 'EM QUARENTENA'
  END AS RESULTADO
FROM 	Tb_Base_Revenda_Ourocap_OTC291_Tratada_TMKT OTC291
INNER JOIN TB_BASE_REVENDA_OUROCAP_COMOTC_TMKT ORIGEM ON ORIGEM.CPF_CNPJ = OTC291.CPF_CNPJ
LEFT JOIN CAMPAIGN_SALESFORCE CMP ON ORIGEM.ID_CAMPANHA = CMP.ID
LEFT JOIN HC_PARCEIRO__C_SALESFORCE PAR ON ORIGEM.PARCEIRO = PAR.ID
LEFT JOIN HC_RELACAO_CLIENTE_PARCEIRO__C_SALESFORCE REL ON ORIGEM.ID_CLIENTE_PARCEIRO = REL.ID
WHERE 
  (OTC291.CODIGO_RNA IS NULL OR OTC291.CODIGO_RNA != '000')
  OR (OTC291.ALTA_RENDA IS NULL OR OTC291.ALTA_RENDA != 0)
  OR (ORIGEM.QUARENTENA IS NULL OR ORIGEM.QUARENTENA != 0)