SELECT
  *
FROM
  TB_BASE_PROSPECT_SEMOTC_TRATADA_NEOBPO
WHERE
  IDADE_VALIDA = 1 
  AND CONTA_CORRENTE = 1 
  AND PROSPECT_QUARENTENA = 0 
  AND CONSELHEIRO = 0 
  AND PROSPECT_CADASTRADO_SF = 0 
  AND VALIDA_RNA = 0