SELECT 
	CPF_CNPJ,
	MAX(Nome) AS Nome,
	MAX(Id_Campanha) AS Id_Campanha,
	MAX(Id_Contato) AS Id_Contato,
	MAX(Id_Cliente_Parceiro) AS Id_Cliente_Parceiro,
	MAX(CONVERT(INTEGER, NAO_DESEJA_RECEBER_EMAIL)) AS NAO_DESEJA_RECEBER_EMAIL,
	MAX(EMAIL) AS EMAIL,
	MAX(convert(integer, EMAIL_VALIDO)) AS EMAIL_VALIDO,
	MAX(QUANTIDADE_TITULOS_ANTERIORES_ATIVOS) AS QUANTIDADE_TITULOS_ANTERIORES_ATIVOS,
	MAX(QUANTIDADE_TITULOS_ANTERIORES_INATIVOS) AS QUANTIDADE_TITULOS_ANTERIORES_INATIVOS,
	MAX(DATA_INICIO_VIGENCIA) AS DATA_INICIO_VIGENCIA
FROM Tb_Boas_Vindas_3_Meses_Clientes_E_Titulos
WHERE 
	ISNULL(NAO_DESEJA_RECEBER_EMAIL, 0) = 0 
	AND EMAIL IS NOT NULL
    AND EMAIL_VALIDO = 1
	AND QUARENTENA = 0
GROUP BY CPF_CNPJ