SELECT
    B.HC_CPF_CNPJ__C AS CPF_CNPJ,
	C.NAME AS NOME,
	HC_IDADE__C AS IDADE,
	HC_DATA_DE_NASCIMENTO__C AS DT_NASCIMENTO,
	HC_GENERO_DO_CLIENTE__C AS SEXO,
	B.HC_PARCEIRO__C AS PARCEIRO,
	HC_TIPO_DE_PESSOA__C AS TIPO_PESSOA,
    LEFT(REPLACE(REPLACE(REPLACE(REPLACE(HC_CELULAR_1__C, '(', ''), ')', ''), ' ', ''), '-', ''), 2) AS DDD_TEL_04,
	SUBSTRING(REPLACE(REPLACE(REPLACE(REPLACE(HC_CELULAR_1__C, '(', ''), ')', ''), ' ', ''), '-', ''), 3, 9) AS TEL_04,
	'MÓVEL' AS TIPO_TEL_04,
	LEFT(REPLACE(REPLACE(REPLACE(REPLACE(HC_CELULAR_2__C, '(', ''), ')', ''), ' ', ''), '-', ''), 2) AS DDD_TEL_05,
	SUBSTRING(REPLACE(REPLACE(REPLACE(REPLACE(HC_CELULAR_2__C, '(', ''), ')', ''), ' ', ''), '-', ''), 3, 9) AS TEL_05,
	'MÓVEL' AS TIPO_TEL_05,
	LEFT(REPLACE(REPLACE(REPLACE(REPLACE(HC_CELULAR_3__C, '(', ''), ')', ''), ' ', ''), '-', ''), 2) AS DDD_TEL_06,
	SUBSTRING(REPLACE(REPLACE(REPLACE(REPLACE(HC_CELULAR_3__C, '(', ''), ')', ''), ' ', ''), '-', ''), 3, 9) AS TEL_06,
	'MÓVEL' AS TIPO_TEL_06,
	HC_CLASSIFICACAO__C AS PUBLICO_ALVO,
	A.[TYPE] AS TIPO_CAMPANHA,
	A.STARTDATE AS DT_INICIO_MAILING,
	A.ENDDATE AS DT_FIM_MAILING,
	A.HC_PRODUTO__C AS ID_PRODUTO,
    A.HC_PRECO_DO_PRODUTO__C AS ID_PRODUTO_VALOR,
	B.HC_CPF_CNPJ__C AS ID,
	A.ID AS ID_CAMPANHA, 
	B.ID AS ID_CLIENTE_PARCEIRO,
	C.ID AS ID_CONTATO,
	B.HC_Cliente__c AS ID_CLIENTE,
	B.HC_CPF_CNPJ_CODIGO_DO_PARCEIRO__C AS CPF_CNPJ_CODIGO_DO_PARCEIRO,
	D.HC_Contratacao__c as DT_COMPRA,
	D.HC_Agendamento__c AS DT_LIMITE,
	A.HC_Data_de_Confirmacao_da_Compra__C AS DIAS_ANTECEDENCIA,
	A.HC_Ultima_Execucao__C AS Dt_Ult_Execucao,
	A.HC_FORMATO__C,
	A.HC_FORNECEDOR__C,
	HC_Origem_da_Venda__c
FROM CAMPAIGN_SALESFORCE A
INNER JOIN HC_RELACAO_CLIENTE_PARCEIRO__C_SALESFORCE B ON A.HC_PARCEIRO__C = B.HC_PARCEIRO__C
                                                      AND A.HC_TIPO_DE_CLIENTE__C = B.HC_TIPO_DE_PESSOA__C
INNER JOIN CONTACT_SALESFORCE C ON C.HC_CPF_CNPJ__C = B.HC_CPF_CNPJ__C
INNER JOIN HC_TITULO__C_SALESFORCE D ON D.HC_CLIENTE_X_PARCEIRO__C = B.ID
WHERE
    UPPER(A.[TYPE]) = 'CLIENTE'
AND UPPER(A.HC_FORNECEDOR__C) = 'NEOBPO'
AND UPPER(A.HC_FORMATO__C) = 'SMS'
/*AND CONVERT(VARCHAR, A.HC_DATA_DE_EXECUCAO__C, 112) = CONVERT(VARCHAR, GETDATE(), 112)*/
AND A.HC_CAMPANHA_EXECUTADA_NO_MKT__C = 0
AND UPPER(D.HC_Origem_da_Venda__c) LIKE '%PROMOTIVA%'
AND A.ISACTIVE = 1