SELECT
	A.CPF_CNPJ AS ID,
	1 AS NAO_IMPORTUNE
FROM Tb_Base_Cliente_ComOTC_NeoBpo A
INNER JOIN TB_BASE_NAO_IMPORTUNE N ON ISNULL(CONCAT(A.DDD_TEL_02, A.TEL_02), '00000000000') = LTRIM(RTRIM(N.TELEFONE))