SELECT
	A.ID,
	CASE
	  WHEN N.TELEFONE IS NOT NULL AND CMP.HC_VALIDA_NAO_IMPORTUNE__C = 1 THEN 1
	  ELSE 0
	END AS NAO_IMPORTUNE
FROM TB_SORTEIOPERIODICO A
LEFT JOIN TB_BASE_NAO_IMPORTUNE N ON ISNULL(CELULAR, '00000000000') = LTRIM(RTRIM(N.TELEFONE))
INNER JOIN CAMPAIGN_SALESFORCE CMP ON CMP.ID = A.ID_CAMPANHA