SELECT 
    Id_Contato,
    MAX(CPF_CNPJ) AS CPF_CNPJ,
    MAX(Nome) AS Nome,
    MAX(Id_Campanha) AS Id_Campanha,
    MAX(Id_Cliente_Parceiro) AS Id_Cliente_Parceiro,
    MAX(CONVERT(INT, NAO_DESEJA_RECEBER_EMAIL)) AS NAO_DESEJA_RECEBER_EMAIL,
    MAX(CONVERT(INT, NAO_DESEJA_RECEBER_SMS)) AS NAO_DESEJA_RECEBER_SMS,
    MAX(EMAIL) AS EMAIL,
    MAX(CONVERT(INT, EMAIL_VALIDO)) AS EMAIL_VALIDO,
    MAX(CELULAR) AS CELULAR,
    MAX(CONVERT(INT, CELULAR_VALIDO)) AS CELULAR_VALIDO,
    MAX(TITULOS_ANTERIORES_ATIVOS) AS TITULOS_ANTERIORES_ATIVOS,
    MAX(TITULOS_ANTERIORES_INATIVOS) AS TITULOS_ANTERIORES_INATIVOS,
    MAX(ID_PROPOSTA) AS ID_PROPOSTA,
    MAX(CREATEDDATE) AS CREATEDDATE,
    MAX(NOME_PARCEIRO) AS NOME_PARCEIRO, 
    MAX(DATA_ORIGEM_VENDA_AGENDADA__C) AS DATA_ORIGEM_VENDA_AGENDADA,
    MAX(ORIGEM_VENDA_AGENDADA__C) AS ORIGEM_VENDA_AGENDADA,
    MAX(QUANTIDADE_VENDA_AGENDADA__C) AS QUANTIDADE_VENDA_AGENDADA,
    MAX(NUMERO_VENDA_AGENDADA__C) AS NUMERO_VENDA_AGENDADA,
    MAX(ID_VENDA_AGENDADA__C) AS ID_VENDA_AGENDADA
FROM Tb_Boas_Vindas_Doadin_Prospostas
GROUP BY Id_Contato
