
SELECT DISTINCT
GmailD1S1.CPF,
GmailD1S1.NOME,
GmailD1S1.EMAIL,
GmailD1S1.EMAIL_VALIDO,
CASE

  WHEN CHARINDEX(' ', GmailD1S1.NOME) = 0 THEN GmailD1S1.NOME

  ELSE SUBSTRING( GmailD1S1.NOME , 1, CHARINDEX(' ', GmailD1S1.NOME) )

END AS PNOME
FROM Gmail_DIV01_SUB01 GmailD1S1
UNION
SELECT DISTINCT
MicrosodftD1S1.CPF,
MicrosodftD1S1.NOME,
MicrosodftD1S1.EMAIL,
MicrosodftD1S1.EMAIL_VALIDO,
CASE

  WHEN CHARINDEX(' ', MicrosodftD1S1.NOME) = 0 THEN MicrosodftD1S1.NOME

  ELSE SUBSTRING( MicrosodftD1S1.NOME , 1, CHARINDEX(' ', MicrosodftD1S1.NOME) )

END AS PNOME
FROM Microsoft_DIV01_SUB01 MicrosodftD1S1
UNION
SELECT DISTINCT
YahooD1S1.CPF,
YahooD1S1.NOME,
YahooD1S1.EMAIL,
YahooD1S1.EMAIL_VALIDO,
CASE

  WHEN CHARINDEX(' ', YahooD1S1.NOME) = 0 THEN YahooD1S1.NOME

  ELSE SUBSTRING( YahooD1S1.NOME , 1, CHARINDEX(' ', YahooD1S1.NOME) )

END AS PNOME
FROM Yahoo_DIV01_SUB01 YahooD1S1
UNION
SELECT DISTINCT
OutrosD1S1.CPF,
OutrosD1S1.NOME,
OutrosD1S1.EMAIL,
OutrosD1S1.EMAIL_VALIDO,
CASE

  WHEN CHARINDEX(' ', OutrosD1S1.NOME) = 0 THEN OutrosD1S1.NOME

  ELSE SUBSTRING( OutrosD1S1.NOME , 1, CHARINDEX(' ', OutrosD1S1.NOME) )

END AS PNOME
FROM Outros_DIV01_SUB01 OutrosD1S1
