SELECT
	A.CPF,
	A.ID_TITULO,
	1 AS NAO_IMPORTUNE
FROM TB_POS_SORTEIO A
INNER JOIN TB_BASE_NAO_IMPORTUNE N ON ISNULL(RIGHT(a.CELULAR, 11), '00000000000') = LTRIM(RTRIM(N.TELEFONE))
WHERE CELULAR != NULL