
SELECT DISTINCT
GmailD3S2.CPF,
GmailD3S2.NOME,
GmailD3S2.EMAIL,
GmailD3S2.EMAIL_VALIDO,
CASE

  WHEN CHARINDEX(' ', GmailD3S2.NOME) = 0 THEN GmailD3S2.NOME

  ELSE SUBSTRING( GmailD3S2.NOME , 1, CHARINDEX(' ', GmailD3S2.NOME) )

END AS PNOME
FROM Gmail_DIV03_SUB02 GmailD3S2
UNION
SELECT DISTINCT
MicrosodftD3S2.CPF,
MicrosodftD3S2.NOME,
MicrosodftD3S2.EMAIL,
MicrosodftD3S2.EMAIL_VALIDO,
CASE

  WHEN CHARINDEX(' ', MicrosodftD3S2.NOME) = 0 THEN MicrosodftD3S2.NOME

  ELSE SUBSTRING( MicrosodftD3S2.NOME , 1, CHARINDEX(' ', MicrosodftD3S2.NOME) )

END AS PNOME
FROM Microsoft_DIV03_SUB02 MicrosodftD3S2
UNION
SELECT DISTINCT
YahooD3S2.CPF,
YahooD3S2.NOME,
YahooD3S2.EMAIL,
YahooD3S2.EMAIL_VALIDO,
CASE

  WHEN CHARINDEX(' ', YahooD3S2.NOME) = 0 THEN YahooD3S2.NOME

  ELSE SUBSTRING( YahooD3S2.NOME , 1, CHARINDEX(' ', YahooD3S2.NOME) )

END AS PNOME
FROM Yahoo_DIV03_SUB02 YahooD3S2
UNION
SELECT DISTINCT
OutrosD3S2.CPF,
OutrosD3S2.NOME,
OutrosD3S2.EMAIL,
OutrosD3S2.EMAIL_VALIDO,
CASE

  WHEN CHARINDEX(' ', OutrosD3S2.NOME) = 0 THEN OutrosD3S2.NOME

  ELSE SUBSTRING( OutrosD3S2.NOME , 1, CHARINDEX(' ', OutrosD3S2.NOME) )

END AS PNOME
FROM Outros_DIV03_SUB02 OutrosD3S2
