SELECT
    A.CPF_CNPJ AS ID,
	1 AS QUARENTENA
FROM
	Tb_Base_Fim_Plano_Ourocap_PU_PP_ComOTC_NeoBpo A
INNER JOIN TB_BASE_QUARENTENA Q ON A.CPF_CNPJ = Q.CPF_CNPJ
WHERE DATEDIFF(MM, Q.DATA_PARTICIPACAO_CAMPANHA, GETDATE()) <= A.MESES_QUARENTENA_EXCLUSAO