SELECT 
  ID_PROPOSTA,
  CPF_CNPJ,
  ID_CONTATO,
  ID_CLIENTE_PARCEIRO,
  EMAIL_VALIDO,
  CELULAR_VALIDO,
  NAO_DESEJA_RECEBER_EMAIL,
  NAO_DESEJA_RECEBER_SMS,
  EMAIL,
  CELULAR,
  TITULOS_ANTERIORES_ATIVOS,
  TITULOS_ANTERIORES_INATIVOS,
  CREATEDDATE
FROM TB_BOAS_VINDAS_OUROCAP_PROSPOSTAS
WHERE NAO_IMPORTUNE = 0