SELECT
	B.ID,
	SUM(CASE WHEN T.HC_SITUACAO__C = 'Ativo' THEN 1 ELSE 0 END) AS QUANTIDADE_TITULOS_ANTERIORES_ATIVOS,
	SUM(CASE WHEN T.HC_SITUACAO__C IS NULL OR T.HC_SITUACAO__C != 'Ativo' THEN 1 ELSE 0 END) AS QUANTIDADE_TITULOS_ANTERIORES_INATIVOS
FROM (
	SELECT DISTINCT
		ID,
		ID_CLIENTE_PARCEIRO,
		ID_CAMPANHA
	FROM TB_BOAS_VINDAS_POSTALCAP_COMOTC_NEOBPO
) B
INNER JOIN CAMPAIGN_SALESFORCE CS ON CS.ID = B.ID_CAMPANHA
INNER JOIN HC_TITULO__C_SALESFORCE T ON T.HC_CLIENTE_X_PARCEIRO__C = B.ID_CLIENTE_PARCEIRO
WHERE 
	T.CREATEDDATE < CS.HC_DATA_INICIAL_DE_COMPRA__C
	/* PARCEIRO TCBV PARA POSTALCAP */
	AND T.HC_CODIGO_DO_PARCEIRO_NA_ORIGEM__C = 'TCBV'
GROUP BY B.ID