
SELECT DISTINCT
GmailD2S3.CPF,
GmailD2S3.NOME,
GmailD2S3.EMAIL,
GmailD2S3.EMAIL_VALIDO,
CASE

  WHEN CHARINDEX(' ', GmailD2S3.NOME) = 0 THEN GmailD2S3.NOME

  ELSE SUBSTRING( GmailD2S3.NOME , 1, CHARINDEX(' ', GmailD2S3.NOME) )

END AS PNOME
FROM Gmail_DIV02_SUB03 GmailD2S3
UNION
SELECT DISTINCT
MicrosodftD2S3.CPF,
MicrosodftD2S3.NOME,
MicrosodftD2S3.EMAIL,
MicrosodftD2S3.EMAIL_VALIDO,
CASE

  WHEN CHARINDEX(' ', MicrosodftD2S3.NOME) = 0 THEN MicrosodftD2S3.NOME

  ELSE SUBSTRING( MicrosodftD2S3.NOME , 1, CHARINDEX(' ', MicrosodftD2S3.NOME) )

END AS PNOME
FROM Microsoft_DIV02_SUB03 MicrosodftD2S3
UNION
SELECT DISTINCT
YahooD2S3.CPF,
YahooD2S3.NOME,
YahooD2S3.EMAIL,
YahooD2S3.EMAIL_VALIDO,
CASE

  WHEN CHARINDEX(' ', YahooD2S3.NOME) = 0 THEN YahooD2S3.NOME

  ELSE SUBSTRING( YahooD2S3.NOME , 1, CHARINDEX(' ', YahooD2S3.NOME) )

END AS PNOME
FROM Yahoo_DIV02_SUB03 YahooD2S3
UNION
SELECT DISTINCT
OutrosD2S3.CPF,
OutrosD2S3.NOME,
OutrosD2S3.EMAIL,
OutrosD2S3.EMAIL_VALIDO,
CASE

  WHEN CHARINDEX(' ', OutrosD2S3.NOME) = 0 THEN OutrosD2S3.NOME

  ELSE SUBSTRING( OutrosD2S3.NOME , 1, CHARINDEX(' ', OutrosD2S3.NOME) )

END AS PNOME
FROM Outros_DIV02_SUB03 OutrosD2S3
