SELECT DISTINCT
  'TCBB' AS COD_PARCEIRO,
  B.CPF,
  '' AS CNPJ,
  B.DDD_01,
  B.TEL_01,
  B.DDD_02,
  B.TEL_02,
  B.DDD_03,
  B.TEL_03 
FROM
  TB_BASE_PROSPECT_OTC291_FILTRADA_NEOBPO A 
  INNER JOIN
    TB_BASE_PROSPECT_COMOTC_TRATADA_NEOBPO B 
    ON A.CPF = B.CPF