SELECT 
    B.HC_CPF_CNPJ__C AS CPF_CNPJ,
	C.NAME AS NOME,
	HC_IDADE__C AS IDADE,
	HC_DATA_DE_NASCIMENTO__C AS DT_NASCIMENTO,
	HC_GENERO_DO_CLIENTE__C AS SEXO,
	CASE 
		WHEN UPPER(B.HC_ENDERECO_PRINCIPAL__C) = 'RESIDENCIAL' THEN HC_CEP_RES__C
		WHEN UPPER(B.HC_ENDERECO_PRINCIPAL__C) = 'COMERCIAL' THEN HC_CEP_COM__C
		WHEN UPPER(B.HC_ENDERECO_PRINCIPAL__C) = 'CORRESPONDÊNCIA' THEN HC_CEP_COR__C
	END AS CEP,
	HC_TIPO_DE_PESSOA__C AS TIPO_PESSOA,
	LEFT(REPLACE(REPLACE(REPLACE(REPLACE(HC_TELEFONE_RESIDENCIAL__C, '(', ''), ')', ''), ' ', ''), '-', ''), 2) AS DDD_TEL_01,
	SUBSTRING(REPLACE(REPLACE(REPLACE(REPLACE(HC_TELEFONE_RESIDENCIAL__C, '(', ''), ')', ''), ' ', ''), '-', ''), 3, 9) AS TEL_01,
	'FIXO' AS TIPO_TEL_01,
	LEFT(REPLACE(REPLACE(REPLACE(REPLACE(HC_TELEFONE_COMERCIAL__C, '(', ''), ')', ''), ' ', ''), '-', ''), 2) AS DDD_TEL_02,
	SUBSTRING(REPLACE(REPLACE(REPLACE(REPLACE(HC_TELEFONE_COMERCIAL__C, '(', ''), ')', ''), ' ', ''), '-', ''), 3, 9) AS TEL_02,
	'FIXO' AS TIPO_TEL_02,
	LEFT(REPLACE(REPLACE(REPLACE(REPLACE(HC_TELEFONE_OUTRO__C, '(', ''), ')', ''), ' ', ''), '-', ''), 2) AS DDD_TEL_03,
	SUBSTRING(REPLACE(REPLACE(REPLACE(REPLACE(HC_TELEFONE_OUTRO__C, '(', ''), ')', ''), ' ', ''), '-', ''), 3, 9) AS TEL_03,
	'FIXO' AS TIPO_TEL_03,
    LEFT(REPLACE(REPLACE(REPLACE(REPLACE(HC_CELULAR_1__C, '(', ''), ')', ''), ' ', ''), '-', ''), 2) AS DDD_TEL_04,
	SUBSTRING(REPLACE(REPLACE(REPLACE(REPLACE(HC_CELULAR_1__C, '(', ''), ')', ''), ' ', ''), '-', ''), 3, 9) AS TEL_04,
	'MÓVEL' AS TIPO_TEL_04,
	LEFT(REPLACE(REPLACE(REPLACE(REPLACE(HC_CELULAR_2__C, '(', ''), ')', ''), ' ', ''), '-', ''), 2) AS DDD_TEL_05,
	SUBSTRING(REPLACE(REPLACE(REPLACE(REPLACE(HC_CELULAR_2__C, '(', ''), ')', ''), ' ', ''), '-', ''), 3, 9) AS TEL_05,
	'MÓVEL' AS TIPO_TEL_05,
	LEFT(REPLACE(REPLACE(REPLACE(REPLACE(HC_CELULAR_3__C, '(', ''), ')', ''), ' ', ''), '-', ''), 2) AS DDD_TEL_06,
	SUBSTRING(REPLACE(REPLACE(REPLACE(REPLACE(HC_CELULAR_3__C, '(', ''), ')', ''), ' ', ''), '-', ''), 3, 9) AS TEL_06,
	'MÓVEL' AS TIPO_TEL_06,
	HC_TELEFONE_PRINCIPAL__C AS TEL_PRINCIPAL,
	HC_CLASSIFICACAO__C AS PUBLICO_ALVO,
	B.HC_CPF_CNPJ__C AS ID,
	B.ID AS ID_CLIENTE_PARCEIRO,
	C.ID AS ID_CONTATO,
	B.HC_CPF_CNPJ_CODIGO_DO_PARCEIRO__C AS CPF_CNPJ_CODIGO_DO_PARCEIRO
FROM HC_RELACAO_CLIENTE_PARCEIRO__C_SALESFORCE B
INNER JOIN Contact_Salesforce C ON C.HC_CPF_CNPJ__c = B.HC_CPF_CNPJ__c
INNER JOIN Opportunity_Salesforce P ON P.HC_CPF_CNPJ__c = c.HC_CPF_CNPJ__c
WHERE P.StageName = 'Queda' and P.Type = 'Renovação Automática'