SELECT
  B.ID_PROPOSTA,
  CASE WHEN B.ID_PROPOSTA IS NOT NULL THEN 1 ELSE 0 END AS QUARENTENA
FROM Tb_Base_Duplo_Sim_SemOTC_Tratada B
LEFT JOIN Tb_Base_Duplo_Sim_Propostas_Comunicadas Q ON B.ID_PROPOSTA = Q.ID_PROPOSTA