SELECT
A.CPF_CNPJ,
A.CAMPANHA,
A.RESULTADO,
A.DATA_REGISTRO
FROM
Tb_Log_Resultados_de_Avaliacao A
WHERE
A.CAMPANHA = 'Campanha Offline PROSPECT - TMKT - detalhe'
AND
CONVERT(date, A.DATA_REGISTRO) BETWEEN CONVERT(date, '2021-06-01') AND CONVERT(date, '2021-12-31')

