SELECT 
	CPF_CNPJ,
	NUMERO_DO_TITULO,
	SERIE_DO_TITULO,
	PLANO_DO_TITULO,
	ID_TITULO,
  ID_CONTATO,
  ID_CLIENTE_PARCEIRO,
  CREATEDDATE
FROM TB_BOAS_VINDAS_OUROCAP_CLIENTES_E_TITULOS
WHERE NAO_IMPORTUNE = 0
	AND (
	  ( ISNULL(NAO_DESEJA_RECEBER_EMAIL, 0) = 0 AND EMAIL_VALIDO = 1 )
	  OR ( ISNULL(NAO_DESEJA_RECEBER_SMS, 0) = 0 AND CELULAR_VALIDO = 1 )
	) AND QUARENTENA = 0