SELECT
  A.CPF
FROM TEST_BASE_OTC291_TRATADA A
LEFT OUTER JOIN (
  SELECT
    COUNT(1) as CPFS_FALTANDO_NO_OTC
  FROM TEST_BASE_OTC290_ENVIADO ENV
  LEFT JOIN TEST_BASE_OTC291_TRATADA RET ON ENV.CPF = RET.CPF
  WHERE RET.CPF IS NULL
) B ON 1 = 1
WHERE B.CPFS_FALTANDO_NO_OTC = 0
  
  AND A.CODIGO_RNA = '000'
  AND A.ALTA_RENDA = 0