SELECT 
	B.CPF_CNPJ,
	B.ID_TITULO,
	T.HC_Serie__c AS SERIE_DO_TITULO,
	T.HC_Inicio__c AS INICIO,
	T.HC_PLANO__C AS PLANO_DO_TITULO,
	T.HC_VALOR_DA_PARCELA__C AS VALOR_PARCELA,
	T.NAME,
	T.HC_FIM_PREVISTO__C AS FIM_PREVISTO,
	T.HC_NUMERO_DA_SORTE__C AS NUMERO_DA_SORTE/*,
	A.NOME_PRODUTO AS NOME_PRODUTO*/
FROM Tb_Boas_Vindas_3_Meses_Clientes_E_Titulos_Filtro A
INNER JOIN Tb_Boas_Vindas_3_Meses_Clientes_E_Titulos B ON A.CPF_CNPJ = B.CPF_CNPJ
INNER JOIN HC_TITULO__C_SALESFORCE T WITH (NOLOCK) ON B.ID_TITULO = T.ID