SELECT
  CPF,
  FORMAT(DT_NASCIMENTO,'dd/MM/yyyy') AS DT_NASCIMENTO,
  TEL_CELULAR,
  CAMPANHA_JORNADA,
  [SUBJECT],
  FORMAT(DT_ENVIO, 'dd/MM/yyyy hh:mm:ss') AS DT_ENVIO,
  FORMAT(DT_ENTREGA, 'dd/MM/yyyy hh:mm:ss') AS DT_ENTREGA,
  CONVERT(INTEGER, ENTREGUE) AS ENTREGUE,
  CONVERT(INTEGER, BOUNCE) AS BOUNCE,
  CONVERT(INTEGER, OPTOUT) AS OPTOUT,
  CASE WHEN CAMPANHA_JORNADA IN ('BOAS VINDAS CARACTERISITCAS NOVO',
    'BOAS VINDAS CARACTERISITCAS RECORRENTE', 
    'BOAS VINDAS CARACTERISITCAS RECUPERADO',
    'BOAS VINDAS CARACTERISTICAS NOVO',
    'BOAS VINDAS CARACTERISTICAS RECORRENTE', 
    'BOAS VINDAS CARACTERISTICAS RECUPERADO',
    'EMAIL CAMPANHA ANIVERSARIO - 20212212',
    'JB_CAMPANHAS_ANIVERSARIANTES',
    'EMAIL FINAL DE ANO - 20212212',
    'CAMPANHA_FIMDEANO2021',
    'PERIODICO DE SORTEIO',
    'JB_CAMPANHA_SORTEIO_PERIODICO',
    'JB_CAMPANHA_SORTEIO_PERIODICO_SMS',
    'CAMPANHA_AUTOMATICA_SORTEIO_PERIODICO') THEN	'RELACIONAMENTO'
  WHEN CAMPANHA_JORNADA IN  ('BOAS VINDAS NOVO',
    'BOAS VINDAS RECORRENTE',
    'JB_CAMPANHA_BOAS_VINDAS_OUROCAP_CLIENTE',
    'BOAS VINDAS RECUPERADO') THEN 'BOAS VINDAS'
  WHEN CAMPANHA_JORNADA IN  ('FIM DE PLANO PM - COM RENOVAÇÃO',
    'FIM DE PLANO PM - SEM RENOVAÇÃO',
    'FIM DE PLANO PM SEM OTC - SEM RENOVAÇÃO', 
    'JB_CAMPANHA_FIM_PLANO_OUROCAP_PU_PP_COMOTC_NEOBPO',
    'FIM DE PLANO PM SEM OTC - COM RENOVAÇÃO') THEN 'FIM DE PLANO/ RENOVAÇÃO'
  ELSE NULL END AS JORNADA
FROM SMS_INFOS_REPORT_CUMULATIVO
WHERE
  MONTH(DT_ENVIO) = MONTH(GETDATE())
  AND DATEPART(YYYY, DT_ENVIO) = DATEPART(YYYY, GETDATE())
ORDER BY DT_ENVIO 
OFFSET 0 ROWS