SELECT   
  ACC.MOBILEMESSAGETRACKINGID AS MOBILEMESSAGETRACKINGID,
  SFAC.HC_DATA_NASCIMENTO__C AS DT_NASCIMENTO,
  CON.HC_CPF_CNPJ__C AS CPF
FROM SMS_INFOS_REPORT_CUMULATIVO ACC
INNER JOIN CONTACT_SALESFORCE CON ON CON.HC_CPF_CNPJ__C = ACC.SUBSCRIBERKEY
INNER JOIN ACCOUNT_SALESFORCE SFAC ON CON.ACCOUNTID = SFAC.ID
WHERE DT_NASCIMENTO IS NULL
  AND SUBSCRIBERKEY IS NOT NULL