
SELECT DISTINCT
GmailD5S3.CPF,
GmailD5S3.NOME,
GmailD5S3.EMAIL,
GmailD5S3.EMAIL_VALIDO,
CASE

  WHEN CHARINDEX(' ', GmailD5S3.NOME) = 0 THEN GmailD5S3.NOME

  ELSE SUBSTRING( GmailD5S3.NOME , 1, CHARINDEX(' ', GmailD5S3.NOME) )

END AS PNOME
FROM Gmail_DIV05_SUB03 GmailD5S3
UNION
SELECT DISTINCT
MicrosodftD5S3.CPF,
MicrosodftD5S3.NOME,
MicrosodftD5S3.EMAIL,
MicrosodftD5S3.EMAIL_VALIDO,
CASE

  WHEN CHARINDEX(' ', MicrosodftD5S3.NOME) = 0 THEN MicrosodftD5S3.NOME

  ELSE SUBSTRING( MicrosodftD5S3.NOME , 1, CHARINDEX(' ', MicrosodftD5S3.NOME) )

END AS PNOME
FROM Microsoft_DIV05_SUB03 MicrosodftD5S3
UNION
SELECT DISTINCT
YahooD5S3.CPF,
YahooD5S3.NOME,
YahooD5S3.EMAIL,
YahooD5S3.EMAIL_VALIDO,
CASE

  WHEN CHARINDEX(' ', YahooD5S3.NOME) = 0 THEN YahooD5S3.NOME

  ELSE SUBSTRING( YahooD5S3.NOME , 1, CHARINDEX(' ', YahooD5S3.NOME) )

END AS PNOME
FROM Yahoo_DIV05_SUB03 YahooD5S3
UNION
SELECT DISTINCT
OutrosD5S3.CPF,
OutrosD5S3.NOME,
OutrosD5S3.EMAIL,
OutrosD5S3.EMAIL_VALIDO,
CASE

  WHEN CHARINDEX(' ', OutrosD5S3.NOME) = 0 THEN OutrosD5S3.NOME

  ELSE SUBSTRING( OutrosD5S3.NOME , 1, CHARINDEX(' ', OutrosD5S3.NOME) )

END AS PNOME
FROM Outros_DIV05_SUB03 OutrosD5S3
