SELECT
  B.CPF_CNPJ,
  CMP.NAME AS CAMPANHA,
  CASE
    WHEN (B.NAO_ACEITOU IS NULL OR B.NAO_ACEITOU = 0) THEN 'REALIZOU O ACEITE'
    WHEN NOT( LEN(CONCAT(B.DDD_TEL_04, B.TEL_04)) = 11
        OR LEN(CONCAT(B.DDD_TEL_05, B.TEL_05)) = 11
        OR LEN(CONCAT(B.DDD_TEL_06, B.TEL_06)) = 11
    ) THEN 'CELULAR INVÁLIDO'
  END AS RESULTADO
FROM
  Tb_Base_Duplo_Sim_SemOTC_Tratada B
LEFT JOIN CAMPAIGN_SALESFORCE CMP ON B.ID_CAMPANHA = CMP.ID
LEFT JOIN HC_PARCEIRO__C_SALESFORCE PAR ON B.PARCEIRO = PAR.ID
LEFT JOIN HC_RELACAO_CLIENTE_PARCEIRO__C_SALESFORCE REL ON B.ID_CLIENTE_PARCEIRO = REL.ID
WHERE
  B.CPF_CNPJ IS NOT NULL
  AND (
    (B.NAO_ACEITOU IS NULL OR B.NAO_ACEITOU = 0)
    /* Todos os telefones inválidos */
    OR NOT( LEN(CONCAT(B.DDD_TEL_04, B.TEL_04)) = 11
        OR LEN(CONCAT(B.DDD_TEL_05, B.TEL_05)) = 11
        OR LEN(CONCAT(B.DDD_TEL_06, B.TEL_06)) = 11
    )
  )