SELECT
  A.CODIGO_PARCEIRO,
  A.ID_CLIENTE,
  A.CODIGO_MCI,
  A.TIPO_PESSOA,
  A.CODIGO_CIC,
  A.DT_NASCIMENTO,
  A.NOME,
  left(B.SEXO, 1) as SEXO,
  left(B.UF, 2) as UF_RESIDENCIAL,
  left(B.Ddd_Tel_01, 4) as Ddd1,
  left(B.Tel_01, 10) as Telefone1,
  left(B.Tipo_Tel_01, 10) as Tipo_Tel_01,
  left(B.Ddd_Tel_02, 4) as Ddd2,
  left(B.Tel_02, 10) as Telefone2,
  left(B.Tipo_Tel_02, 10) as Tipo_Tel_02,
  left(B.Ddd_Tel_03, 4) as Ddd3,
  left(B.Tel_03, 10) as Telefone3,
  left(B.Tipo_Tel_03, 10) as Tipo_Tel_03,
  left(B.Ddd_Tel_04, 4) as Ddd4,
  left(B.Tel_04, 10) as Telefone4,
  left(B.Tipo_Tel_04, 10) as Tipo_Tel_04,
  left(B.Ddd_Tel_05, 4) as Ddd5,
  left(B.Tel_05, 10) as Telefone5,
  left(B.Tipo_Tel_05, 10) as Tipo_Tel_05,
  left(B.Ddd_Tel_06, 4) as Ddd6,
  left(B.Tel_06, 10) as Telefone6,
  left(B.Tipo_Tel_06, 10) as Tipo_Tel_06,
  A.CODIGO_PLANO,
  A.ORIGEM_SOLICITACAO,
  A.FILLER,
  A.CODIGO_RNA,
  A.VALOR_RENDIMENTOS,
  A.TIPO_CARTEIRA,
  A.NIVEL_RELACIONAMENTO,
  A.DATA_INFORMACAO,
  A.FILLER2,
  A.CPF,
  left(UPPER(SUBSTRING(B.NOME, 1, CHARINDEX(' ', B.NOME) - 1)), 50) AS PRIMEIRO_NOME,
  left(UPPER(SUBSTRING(B.NOME, CHARINDEX(' ', B.NOME) + 1, LEN(B.NOME))), 50) AS SOBRENOME,
  A.DT_NASCIMENTO_SF,
  /*CONCAT(CONVERT(INT, SUBSTRING(RETORNO, 234, 13)),'.',RIGHT(SUBSTRING(RETORNO, 234, 15), 2)) AS FAIXA_RENDA_MENSAL,*/
  A.ALTA_RENDA,
  B.Tipo_Campanha,
  B.Id_Campanha,
  B.Id_Cliente_Parceiro,
  B.Id_Contato
FROM
  Tb_Base_OTC291_Tratada A
INNER JOIN TB_BASE_FIM_PLANO_OUROCAP_PU_PP_COMOTC_NEOBPO_FILTRADA B ON A.CPF = B.CPF_CNPJ