SELECT
	A.CPF_CNPJ AS ID,
	1 AS NAO_IMPORTUNE
FROM Tb_Base_Cliente_Renovacao_TMKT A
INNER JOIN TB_BASE_NAO_IMPORTUNE N ON ISNULL(CONCAT(A.DDD_TEL_03, A.TEL_03), '00000000000') = LTRIM(RTRIM(N.TELEFONE))