SELECT
  B.CPF_CNPJ,
  CMP.NAME AS CAMPANHA,
  PAR.HC_CODIGO_DO_PARCEIRO_CAP__C AS PARCEIRO,
  CONVERT(INTEGER, REL.HC_IDADE__C) AS  IDADE,
  /* ORIGEM.COMPRA_UTIMOS_30_DIAS AS COMPROU_ULTIMOS_30_DIAS, */
  B.CONSELHEIRO,
  B.CLIENTE_PEP,
  B.DESEJA_CONTATO_TELEFONICO AS NAO_DESEJA_RECEBER_LIGACOES,
  B.POSSUI_TELEFONE_ATIVO,
  B.POSSUI_CONTA_ATIVA,
  B.QUARENTENA,
  B.COMPRA_RECENTE_OUROCAP,
  B.NAO_IMPORTUNE,
  CASE
    WHEN B.IDADE_VALIDA IS NULL OR B.IDADE_VALIDA = 0 THEN 'IDADE INVALIDA'
    WHEN B.CONSELHEIRO IS NULL OR B.CONSELHEIRO = 1 THEN 'CONSELHEIRO'
    WHEN B.CLIENTE_PEP IS NULL OR B.CLIENTE_PEP = 1 THEN 'PEP'
    WHEN B.DESEJA_CONTATO_TELEFONICO IS NULL OR B.DESEJA_CONTATO_TELEFONICO = 1 THEN 'NÃO DESEJA CONTATO TELEFONICO'
    WHEN B.COMPRA_RECENTE_OUROCAP IS NULL OR B.COMPRA_RECENTE_OUROCAP = 1 THEN 'COMPRA RECENTE OUROCAP'
    /* WHEN B.POSSUI_CONTA_ATIVA IS NULL OR B.POSSUI_CONTA_ATIVA = 0 THEN 'NÃO POSSUI CONTA ATIVA' */
    WHEN B.POSSUI_TELEFONE_ATIVO IS NULL OR B.POSSUI_TELEFONE_ATIVO = 0 THEN 'NÃO POSSUI TELEFONE ATIVO'
    WHEN B.QUARENTENA IS NULL OR B.QUARENTENA = 1 THEN 'EM QUARENTENA'
    WHEN B.NAO_IMPORTUNE IS NULL OR B.NAO_IMPORTUNE = 1 THEN 'NÃO IMPORTUNE'
  END AS RESULTADO
FROM
  TB_BASE_REVENDA_OUROCAP_COMOTC_TMKT B
LEFT JOIN CAMPAIGN_SALESFORCE CMP ON B.ID_CAMPANHA = CMP.ID
LEFT JOIN HC_PARCEIRO__C_SALESFORCE PAR ON B.PARCEIRO = PAR.ID
LEFT JOIN HC_RELACAO_CLIENTE_PARCEIRO__C_SALESFORCE REL ON B.ID_CLIENTE_PARCEIRO = REL.ID
WHERE
  (
    (B.IDADE_VALIDA IS NULL OR B.IDADE_VALIDA = 0) 
    OR (B.CONSELHEIRO IS NULL OR B.CONSELHEIRO = 1) 
    OR (B.CLIENTE_PEP IS NULL OR B.CLIENTE_PEP = 1) 
    OR (B.DESEJA_CONTATO_TELEFONICO IS NULL OR B.DESEJA_CONTATO_TELEFONICO = 1) 
    OR (B.COMPRA_RECENTE_OUROCAP IS NULL OR B.COMPRA_RECENTE_OUROCAP = 1) 
    /* OR (B.POSSUI_CONTA_ATIVA IS NULL OR B.POSSUI_CONTA_ATIVA = 0) */
    OR (B.POSSUI_TELEFONE_ATIVO IS NULL OR B.POSSUI_TELEFONE_ATIVO = 0)
    OR (B.QUARENTENA IS NULL OR B.QUARENTENA = 1)
    OR (B.NAO_IMPORTUNE IS NULL OR B.NAO_IMPORTUNE = 1)
  )
  AND B.CPF_CNPJ IS NOT NULL