SELECT
  CON.CPF,
  CMEM.ID AS ID_MEMBRO_CAMPANHA
FROM [Tb_Base_Prospect_OTC291_Filtrada_TMKT] CON
LEFT JOIN CAMPAIGNMEMBER_SALESFORCE CMEM ON CMEM.CAMPAIGNID = CON.ID_CAMPANHA 
  AND CMEM.CONTACTID = CON.ID_CONTATO
WHERE
  CMEM.ID IS NOT NULL