SELECT DISTINCT
	CASE
	  WHEN NULLIF(B.Tel_01, '') IS NULL THEN NULL
	  WHEN LEN(B.Tel_01) > 9 OR ( LEN(B.Tel_01) = 8 AND B.Tel_01 LIKE '9%' ) THEN NULL
	  ELSE B.Ddd_Tel_01
	END AS DDD1,
	CASE
	  WHEN NULLIF(B.Tel_01, '') IS NULL THEN NULL
	  WHEN LEN(B.Tel_01) > 9 OR ( LEN(B.Tel_01) = 8 AND B.Tel_01 LIKE '9%' ) THEN NULL
	  ELSE B.Tel_01
	END AS TELEFONE1,
	CASE
	  WHEN NULLIF(B.Tel_01, '') IS NULL THEN NULL
	  WHEN LEN(B.Tel_01) > 9 OR ( LEN(B.Tel_01) = 8 AND B.Tel_01 LIKE '9%' ) THEN NULL
	  ELSE B.Tipo_Tel_01
	END AS TIPO1,
	CASE
	  WHEN NULLIF(B.Tel_02, '') IS NULL THEN NULL
	  WHEN LEN(B.Tel_02) > 9 OR ( LEN(B.Tel_02) = 8 AND B.Tel_02 LIKE '9%' ) THEN NULL
	  ELSE B.Ddd_Tel_02
	END AS DDD2,
	CASE
	  WHEN NULLIF(B.Tel_02, '') IS NULL THEN NULL
	  WHEN LEN(B.Tel_02) > 9 OR ( LEN(B.Tel_02) = 8 AND B.Tel_02 LIKE '9%' ) THEN NULL
	  ELSE B.Tel_02
	END AS TELEFONE2,
	CASE
	  WHEN NULLIF(B.Tel_02, '') IS NULL THEN NULL
	  WHEN LEN(B.Tel_02) > 9 OR ( LEN(B.Tel_02) = 8 AND B.Tel_02 LIKE '9%' ) THEN NULL
	  ELSE B.Tipo_Tel_02
	END AS TIPO2,
	CASE
	  WHEN NULLIF(B.Tel_03, '') IS NULL THEN NULL
	  WHEN LEN(B.Tel_03) > 9 OR ( LEN(B.Tel_03) = 8 AND B.Tel_03 LIKE '9%' ) THEN NULL
	  ELSE B.Ddd_Tel_03
	END AS DDD3,
	CASE
	  WHEN NULLIF(B.Tel_03, '') IS NULL THEN NULL
	  WHEN LEN(B.Tel_03) > 9 OR ( LEN(B.Tel_03) = 8 AND B.Tel_03 LIKE '9%' ) THEN NULL
	  ELSE B.Tel_03
	END AS TELEFONE3,
	CASE
	  WHEN NULLIF(B.Tel_03, '') IS NULL THEN NULL
	  WHEN LEN(B.Tel_03) > 9 OR ( LEN(B.Tel_03) = 8 AND B.Tel_03 LIKE '9%' ) THEN NULL
	  ELSE B.Tipo_Tel_03
	END AS TIPO3,
	CASE
	  WHEN NULLIF(B.Tel_04, '') IS NULL THEN NULL
	  WHEN LEN(B.Tel_04) > 9 OR ( LEN(B.Tel_04) = 8 AND B.Tel_04 LIKE '9%' ) THEN NULL
	  ELSE B.Ddd_Tel_04
	END AS DDD4,
	CASE
	  WHEN NULLIF(B.Tel_04, '') IS NULL THEN NULL
	  WHEN LEN(B.Tel_04) > 9 OR ( LEN(B.Tel_04) = 8 AND B.Tel_04 LIKE '9%' ) THEN NULL
	  ELSE B.Tel_04
	END AS TELEFONE4,
	CASE
	  WHEN NULLIF(B.Tel_04, '') IS NULL THEN NULL
	  WHEN LEN(B.Tel_04) > 9 OR ( LEN(B.Tel_04) = 8 AND B.Tel_04 LIKE '9%' ) THEN NULL
	  ELSE B.Tipo_Tel_04
	END AS TIPO4,
	CASE
	  WHEN NULLIF(B.Tel_05, '') IS NULL THEN NULL
	  WHEN LEN(B.Tel_05) > 9 OR ( LEN(B.Tel_05) = 8 AND B.Tel_05 LIKE '9%' ) THEN NULL
	  ELSE B.Ddd_Tel_05
	END AS DDD5,
	CASE
	  WHEN NULLIF(B.Tel_05, '') IS NULL THEN NULL
	  WHEN LEN(B.Tel_05) > 9 OR ( LEN(B.Tel_05) = 8 AND B.Tel_05 LIKE '9%' ) THEN NULL
	  ELSE B.Tel_05
	END AS TELEFONE5,
	CASE
	  WHEN NULLIF(B.Tel_05, '') IS NULL THEN NULL
	  WHEN LEN(B.Tel_05) > 9 OR ( LEN(B.Tel_05) = 8 AND B.Tel_05 LIKE '9%' ) THEN NULL
	  ELSE B.Tipo_Tel_05
	END AS TIPO5,
  B.Tel_Principal AS PREFERENCIAL,
  B.IDADE,
  CONVERT(VARCHAR(10), B.DT_NASCIMENTO, 103) AS DATA_NASCIMENTO,
  B.NOME AS NOME_CLIENTE,
  B.CEP,
  B.UF,
  B.TIPO_PESSOA AS TIPO_DE_PESSOA,
  B.CPF_CNPJ,
  B.SEXO,
  B.TIPO_CAMPANHA,
  CONVERT(VARCHAR(10), B.DT_CRIACAO_MAILING, 103) AS DATA_CRIACAO,
  CONVERT(VARCHAR(10), B.DT_INICIO_MAILING, 103) AS DATA_UTILIZACAO,
  CONVERT(VARCHAR(10), B.DT_FIM_MAILING, 103) AS DATA_TERMINO, 
  B.ID_CAMPANHA AS IDCAMPANHA,
  B.ID_CONTATO AS IDCONTATOS,
  B.ID_CLIENTE_PARCEIRO AS IDCP,
  B.Publico_Alvo as CLASSIFICACAO
FROM
  TB_BASE_FIM_PLANO_OUROCAP_PU_PP_OTC291_FILTRADA_NEOBPO A
INNER JOIN Tb_Base_Fim_Plano_Ourocap_PU_PP_ComOTC_NeoBpo_Filtrada B on A.CPF_CNPJ = B.CPF_CNPJ

WHERE 
 (LEN(NULLIF(B.Tel_01, '')) < 10 AND NOT( LEN(B.Tel_01) = 8 AND B.Tel_01 LIKE '9%' ))
 OR (LEN(NULLIF(B.Tel_02, '')) < 10 AND NOT( LEN(B.Tel_02) = 8 AND B.Tel_02 LIKE '9%' ))
 OR (LEN(NULLIF(B.Tel_03, '')) < 10 AND NOT( LEN(B.Tel_03) = 8 AND B.Tel_03 LIKE '9%' ))
 OR (LEN(NULLIF(B.Tel_04, '')) < 10 AND NOT( LEN(B.Tel_04) = 8 AND B.Tel_04 LIKE '9%' ))
 OR (LEN(NULLIF(B.Tel_05, '')) < 10 AND NOT( LEN(B.Tel_05) = 8 AND B.Tel_05 LIKE '9%' ))