SELECT 
  left(S.SUBSCRIBERKEY, 50) AS SUBSCRIBERKEY,
  convert(varchar, MobileMessageTrackingID) as MobileMessageTrackingID,
  S.MOBILE AS TEL_CELULAR,
  left(JOURNEYNAME, 50) AS CAMPANHA_JORNADA,
  left(S.NAME, 50) AS SUBJECT,
  S.CREATEDATETIME AS DT_ENVIO,
  S.ACTIONDATETIME AS DT_ENTREGA,
  S.DELIVERED AS ENTREGUE,
  S.UNDELIVERED AS BOUNCE,
  IIF(s.OptOut IS NULL,0,1) AS OPTOUT,
  left(S.JBACTIVITYID, 50) as JBACTIVITYID
FROM _SMSMESSAGETRACKING S
LEFT JOIN _JOURNEYACTIVITY JA ON S.JBACTIVITYID=JA.ACTIVITYID
LEFT JOIN _JOURNEY J ON JA.VERSIONID=J.VERSIONID
WHERE 
  CREATEDATETIME BETWEEN DATEADD(DD, DATEDIFF(DD, 0, GETDATE()) - 1, 0)
    AND DATEADD(DD, DATEDIFF(DD, 0, GETDATE()), 0)
ORDER BY S.CREATEDATETIME 
OFFSET 0 ROWS