select
  b.ID_CAMPANHA,
  count(1) as QUANTIDADE_OBTIDA_ULTIMA_EXEC_OTC290
from Tb_Base_Ex_Cliente_ComOTC_TMKT_ONLINE a
inner join CONTROLE_AUTOMACOES_CAMPANHAS b on b.ID_CAMPANHA = '7016g000000NhD1AAK'
group by  b.ID_CAMPANHA