SELECT
  '001'+
  REPLICATE (' ' , 9)+
  REPLICATE ('0' , 9)+
  '1'+
  RIGHT(REPLICATE ('0' , 15)+CONVERT(VARCHAR, CPF_CNPJ), 15)+
  CONVERT(VARCHAR(10), CONVERT(DATE, DT_NASCIMENTO, 103), 112)+
  LEFT(CONVERT(VARCHAR(60), NOME) + REPLICATE(' ', 60), 60)+
  REPLICATE (' ' , 1)+
  REPLICATE (' ' , 2)+
  REPLICATE (' ' , 4)+
  REPLICATE (' ' , 10)+
  REPLICATE (' ' , 4)+
  REPLICATE (' ' , 10)+
  REPLICATE (' ' , 4)+
  REPLICATE (' ' , 10)+
  REPLICATE (' ' , 5)+
  REPLICATE (' ' , 2)+
  REPLICATE (' ' , 73)+
  REPLICATE (' ' , 70) AS BASE
FROM
  Teste_TB_BASE_REVENDA_OUROCAP_COMOTC_NEOBPO 
WHERE
  IDADE_VALIDA = 1 
  AND CONSELHEIRO = 0 
  AND CLIENTE_PEP = 0 
  AND DESEJA_CONTATO_TELEFONICO = 0 
  AND COMPRA_RECENTE_OUROCAP = 0 
  AND POSSUI_CONTA_ATIVA = 1
  AND POSSUI_TELEFONE_ATIVO = 1
  /*AND QUARENTENA = 0*/
  AND NAO_IMPORTUNE = 0