SELECT
  SELECTED.*
FROM (
  SELECT
		B.HC_CPF_CNPJ__C AS CPF_CNPJ,
		C.NAME AS NOME,
		CASE
			WHEN B.HC_EMAIL_BRASILCAP__C IS NOT NULL THEN HC_EMAIL_BRASILCAP__C
			WHEN B.HC_EMAIL_COMERCIAL__C IS NOT NULL THEN HC_EMAIL_COMERCIAL__C
			WHEN B.HC_EMAIL_PESSOAL__C IS NOT NULL THEN HC_EMAIL_PESSOAL__C
			ELSE NULL
		END AS EMAIL,
		CASE
			WHEN B.HC_EMAIL_BRASILCAP__C IS NOT NULL THEN 1
			WHEN B.HC_EMAIL_COMERCIAL__C IS NOT NULL THEN 1
			WHEN B.HC_EMAIL_PESSOAL__C IS NOT NULL THEN 1
			ELSE 0
		END AS EMAIL_VALIDO,
		CASE
      WHEN B.HC_STATUS_CELULAR_1__C = 'VÁLIDO' THEN HC_CELULAR_1__C
      WHEN B.HC_STATUS_CELULAR_2__C = 'VÁLIDO' THEN HC_CELULAR_2__C
      WHEN B.HC_STATUS_CELULAR_3__C = 'VÁLIDO' THEN HC_CELULAR_3__C
      WHEN B.HC_STATUS_CELULAR_3_3__C = 'VÁLIDO' THEN HC_CELULAR_3_3__C
      WHEN B.HC_STATUS_CELULAR_4__C = 'VÁLIDO' THEN HC_CELULAR_4__C
      ELSE NULL
		END AS CELULAR,
    CASE
      WHEN B.HC_STATUS_CELULAR_1__C = 'VÁLIDO' THEN 1
      WHEN B.HC_STATUS_CELULAR_2__C = 'VÁLIDO' THEN 1
      WHEN B.HC_STATUS_CELULAR_3__C = 'VÁLIDO' THEN 1
      WHEN B.HC_STATUS_CELULAR_3_3__C = 'VÁLIDO' THEN 1
      WHEN B.HC_STATUS_CELULAR_4__C = 'VÁLIDO' THEN 1
      ELSE 0
    END AS CELULAR_VALIDO,
		B.HC_TELEFONE_PRINCIPAL__C AS TEL_PRINCIPAL,
		B.HC_CPF_CNPJ__C AS ID,
		A.ID AS ID_CAMPANHA, 
		B.ID AS ID_CLIENTE_PARCEIRO,
		C.ID AS ID_CONTATO,
    AC.HC_DATA_NASCIMENTO__C,
    B.HC_NAO_DESEJA_RECEBER_EMAIL__C AS NAO_DESEJA_RECEBER_EMAIL,
    B.HC_NAO_DESEJA_RECEBER_SMS__C AS NAO_DESEJA_RECEBER_SMS,
    GETDATE()+1 AS DATA_EXECUCAO,
    ROW_NUMBER() OVER (PARTITION BY AC.ID ORDER BY AC.ID) AS ROW
	FROM CAMPAIGN_SALESFORCE A
	INNER JOIN HC_RELACAO_CLIENTE_PARCEIRO__C_SALESFORCE B ON 1 = 1
	INNER JOIN ACCOUNT_SALESFORCE AC ON AC.ID = B.HC_CLIENTE__C
	INNER JOIN CONTACT_SALESFORCE C ON C.ACCOUNTID = AC.ID
	WHERE A.ID = '7016g000000744GAAQ'
    AND A.ISACTIVE = 1
    /* Data de Execução 
    AND CONVERT(VARCHAR(10), A.HC_DATA_DE_EXECUCAO__C, 101) = CONVERT(VARCHAR(10), GETDATE(), 101)
    AND DATEPART(HH, A.HC_DATA_DE_EXECUCAO__C) = DATEPART(HH, GETDATE())
    Tipo de cliente controlado pela campanha */
    AND (B.HC_TIPO_DE_PESSOA__C = A.HC_TIPO_DE_CLIENTE__C OR (A.HC_TIPO_DE_CLIENTE__C = 'PF E PJ' ))
    AND (A.HC_PARCEIRO__C = B.HC_PARCEIRO__C OR A.HC_PARCEIRO__C IS NULL)
    AND B.HC_CLASSIFICACAO__C = 'CLIENTE'
    AND B.HC_NAO_DESEJA_RECEBER_TODOS_MEIOS__C = 0
    AND (ISNULL(B.HC_NAO_IMPORTUNE__C, 0) = 0 OR A.HC_VALIDA_NAO_IMPORTUNE__C = 0)
    AND (
        /* Pode receber e-mail */
        ( ISNULL(B.HC_NAO_DESEJA_RECEBER_EMAIL__C, 0) = 0 AND ( B.HC_EMAIL_BRASILCAP__C IS NOT NULL OR B.HC_EMAIL_COMERCIAL__C IS NOT NULL OR B.HC_EMAIL_PESSOAL__C IS NOT NULL ) )
        /* ou pode receber sms */
        OR ( ISNULL(B.HC_NAO_DESEJA_RECEBER_SMS__C, 0) = 0 AND (B.HC_STATUS_CELULAR_1__C = 'VÁLIDO' OR B.HC_STATUS_CELULAR_2__C = 'VÁLIDO' OR B.HC_STATUS_CELULAR_3__C = 'VÁLIDO' 
          OR B.HC_STATUS_CELULAR_3_3__C = 'VÁLIDO' OR B.HC_STATUS_CELULAR_4__C = 'VÁLIDO') )
      )
    AND RIGHT(CONVERT(CHAR(10),AC.HC_DATA_NASCIMENTO__C,23), 5) = RIGHT(CONVERT(CHAR(10),GETDATE(),23), 5)
) SELECTED
INNER JOIN CAMPAIGN_SALESFORCE A ON SELECTED.ID_CAMPANHA = A.ID
INNER JOIN HC_RELACAO_CLIENTE_PARCEIRO__C_SALESFORCE B ON SELECTED.ID_CLIENTE_PARCEIRO = B.ID
INNER JOIN CONTACT_SALESFORCE C ON SELECTED.ID_CONTATO = C.ID
WHERE SELECTED.ROW = 1