SELECT Ddd_Tel_01 AS DDD1,
       Tel_01 TELEFONE1,
       B.Tipo_Tel_01 TIPO1,
       Ddd_Tel_02 AS DDD2,
       Tel_02 TELEFONE2,
       B.Tipo_Tel_02 TIPO2,
       Ddd_Tel_04 DDD3,
       Tel_04 TELEFONE3,
       B.Tipo_Tel_04 TIPO3,
       Ddd_Tel_05 DDD4,
       Tel_05 TELEFONE4,
       B.Tipo_Tel_05 TIPO4,
       Ddd_Tel_03 DDD5,
       Tel_03 TELEFONE5,
       B.Tipo_Tel_03 TIPO5,
       B.Tel_Principal PREFERENCIAL,
       B.IDADE,
       CONVERT(VARCHAR(10), B.Dt_Nascimento, 103) AS DATA_NASCIMENTO,
    B.Nome AS NOME_CLIENTE,
    B.CEP,
    '' as UF,
    B.Tipo_Pessoa TIPO_DE_PESSOA,
    B.CPF_CNPJ,
    B.Sexo,
    B.Publico_Alvo CLASSIFICAÇAO,
    B.Tipo_Campanha,
    CONVERT(VARCHAR(10), B.Dt_Criacao_Mailing, 103) AS DATA_CRIAÇÃO,
    CONVERT(VARCHAR(10), B.Dt_Inicio_Mailing, 103) AS DATA_UTILIZAÇÃO,
    CONVERT(VARCHAR(10), B.Dt_Fim_Mailing, 103) AS DATA_TERMINO,
    B.Id_Campanha IDCAMPANHA,
    B.Id_Contato IDCONTATOS,
    B.Id_Cliente_Parceiro AS IDCP
FROM Tb_Base_Ex_Cliente_OTC291_Filtrada_TMKT_ONLINE A
INNER JOIN Tb_Base_Ex_Cliente_ComOTC_TMKT_ONLINE B ON A.CPF = B.CPF_CNPJ