SELECT DISTINCT
  'TCBB' AS COD_PARCEIRO,
  B.CPF_CNPJ AS CPF,
  '' AS CNPJ,
  B.DDD_TEL_01 AS DDD,
  B.TEL_01 AS TELEFONE,
  B.TIPO_TEL_01 AS TIPO
FROM
  TB_BASE_EX_CLIENTE_OTC291_FILTRADA_TMKT A
  INNER JOIN Tb_Base_Ex_Cliente_ComOTC_Filtrada_TMKT B 
    ON A.CPF = B.CPF_CNPJ
WHERE
  LEN(NULLIF(TEL_01, '')) < 10
  AND NOT( LEN(TEL_01) = 8 AND TEL_01 LIKE '9%' )

UNION ALL

SELECT DISTINCT
  'TCBB' AS COD_PARCEIRO,
  B.CPF_CNPJ AS CPF,
  '' AS CNPJ,
  B.DDD_TEL_02 AS DDD,
  B.TEL_02 AS TELEFONE,
  B.TIPO_TEL_02 AS TIPO
FROM
  TB_BASE_EX_CLIENTE_OTC291_FILTRADA_TMKT A 
  INNER JOIN
    Tb_Base_Ex_Cliente_ComOTC_Filtrada_TMKT B 
    ON A.CPF = B.CPF_CNPJ
WHERE
  LEN(NULLIF(TEL_02, '')) < 10
  AND NOT( LEN(TEL_02) = 8 AND TEL_02 LIKE '9%' )

UNION ALL

SELECT DISTINCT
  'TCBB' AS COD_PARCEIRO,
  B.CPF_CNPJ AS CPF,
  '' AS CNPJ,
  B.DDD_TEL_03 AS DDD,
  B.TEL_03 AS TELEFONE,
  B.TIPO_TEL_03 AS TIPO
FROM
  TB_BASE_EX_CLIENTE_OTC291_FILTRADA_TMKT A 
  INNER JOIN
    Tb_Base_Ex_Cliente_ComOTC_Filtrada_TMKT B 
    ON A.CPF = B.CPF_CNPJ
WHERE
  LEN(NULLIF(TEL_03, '')) < 10
  AND NOT( LEN(TEL_03) = 8 AND TEL_03 LIKE '9%' )

UNION ALL

SELECT DISTINCT
  'TCBB' AS COD_PARCEIRO,
  B.CPF_CNPJ AS CPF,
  '' AS CNPJ,
  B.DDD_TEL_04 AS DDD,
  B.TEL_04 AS TELEFONE,
  B.TIPO_TEL_04 AS TIPO
FROM
  TB_BASE_EX_CLIENTE_OTC291_FILTRADA_TMKT A 
  INNER JOIN
    Tb_Base_Ex_Cliente_ComOTC_Filtrada_TMKT B 
    ON A.CPF = B.CPF_CNPJ
WHERE
  LEN(NULLIF(TEL_04, '')) < 10
  AND NOT( LEN(TEL_04) = 8 AND TEL_04 LIKE '9%' )

UNION ALL

SELECT DISTINCT
  'TCBB' AS COD_PARCEIRO,
  B.CPF_CNPJ AS CPF,
  '' AS CNPJ,
  B.DDD_TEL_05 AS DDD,
  B.TEL_05 AS TELEFONE,
  B.TIPO_TEL_05 AS TIPO
FROM
  TB_BASE_EX_CLIENTE_OTC291_FILTRADA_TMKT A 
  INNER JOIN
    Tb_Base_Ex_Cliente_ComOTC_Filtrada_TMKT B 
    ON A.CPF = B.CPF_CNPJ
WHERE
  LEN(NULLIF(TEL_05, '')) < 10
  AND NOT( LEN(TEL_05) = 8 AND TEL_05 LIKE '9%' )

  UNION ALL

SELECT DISTINCT
  'TCBB' AS COD_PARCEIRO,
  B.CPF_CNPJ AS CPF,
  '' AS CNPJ,
  B.DDD_TEL_06 AS DDD,
  B.TEL_06 AS TELEFONE,
  B.TIPO_TEL_06 AS TIPO
FROM
  TB_BASE_EX_CLIENTE_OTC291_FILTRADA_TMKT A 
  INNER JOIN
    Tb_Base_Ex_Cliente_ComOTC_Filtrada_TMKT B 
    ON A.CPF = B.CPF_CNPJ
WHERE
  LEN(NULLIF(TEL_06, '')) < 10
  AND NOT( LEN(TEL_06) = 8 AND TEL_06 LIKE '9%' )