SELECT CPF,
  COD_PARCEIRO,
  CNPJ,
  PARCEIRO_ORGANIZACAO,
  PARCEIRO_LOCALIZACAO,
  COD_CLIENTE_MC,
  NOME_COMPLETO,
  TIPO_PESSOA,
  DATA_NASCIMENTO,
  SEXO,
  CLIENTE_ORGANIZACAO,
  CLIENTE_CHAVE_MIGRACAO,
  CLIENTE_CHAGE_GERAL_INTERNA,
  CLIENTE_TIPO_INTERNO
FROM (SELECT DISTINCT
  A.CPF,
  'TCBB' AS COD_PARCEIRO,
  '' AS CNPJ,
  'Brasilcap' AS PARCEIRO_ORGANIZACAO,
  'Brazil' AS PARCEIRO_LOCALIZACAO,
  C.ID AS COD_CLIENTE_MC,
  B.NOME AS NOME_COMPLETO,
  'PF' AS TIPO_PESSOA,
  CONVERT(VARCHAR, CAST(B.Dt_Nascimento AS DATE), 112) AS DATA_NASCIMENTO,
  B.SEXO,
  'Brasilcap' AS CLIENTE_ORGANIZACAO,
  CONCAT(A.CPF, 'TCBB') AS CLIENTE_CHAVE_MIGRACAO,
  CONCAT(A.CPF, 'TCBB') AS CLIENTE_CHAGE_GERAL_INTERNA,
  'Person' AS CLIENTE_TIPO_INTERNO,
  row_number() over (partition by A.CPF order by C.ID desc) AS ROW_ID
FROM
  TB_BASE_PROSPECT_OTC291_FILTRADA_TEO A 
    INNER JOIN Tb_Base_Prospect_OTC291_Tratada_TEO B ON A.CPF = B.CPF
    INNER JOIN HC_Relacao_Cliente_Parceiro__c_Salesforce C ON A.CPF = C.CPF_CNPJ_Cliente__c) BASE
WHERE ROW_ID = 1