SELECT
  A.ID,
  A.NOME,
  A.CPF_CNPJ,
  A.HC_MES_INICIO__C,
  A.HC_MES_FIM__C,
  A.HC_QUANTIDADE_DE_CLIENTES_SORTEADOS__C,
  CASE
    WHEN A.HC_MES_INICIO__C = 1 THEN 'JANEIRO'
    WHEN A.HC_MES_INICIO__C = 2 THEN 'FEVEREIRO'
    WHEN A.HC_MES_INICIO__C = 3 THEN 'MARÇO'
    WHEN A.HC_MES_INICIO__C = 4 THEN 'ABRIL'
    WHEN A.HC_MES_INICIO__C = 5 THEN 'MAIO'
    WHEN A.HC_MES_INICIO__C = 6 THEN 'JUNHO'
    WHEN A.HC_MES_INICIO__C = 7 THEN 'JULHO'
    WHEN A.HC_MES_INICIO__C = 8 THEN 'AGOSTO'
    WHEN A.HC_MES_INICIO__C = 9 THEN 'SETEMBRO'
    WHEN A.HC_MES_INICIO__C = 10 THEN 'OUTRUBRO'
    WHEN A.HC_MES_INICIO__C = 11 THEN 'NOVEMBRO'
    WHEN A.HC_MES_INICIO__C = 12 THEN 'DEZEMBRO'
    ELSE NULL
  END AS MES_INICIAL,
  CASE
    WHEN A.HC_MES_FIM__C = 1 THEN 'JANEIRO'
    WHEN A.HC_MES_FIM__C = 2 THEN 'FEVEREIRO'
    WHEN A.HC_MES_FIM__C = 3 THEN 'MARÇO'
    WHEN A.HC_MES_FIM__C = 4 THEN 'ABRIL'
    WHEN A.HC_MES_FIM__C = 5 THEN 'MAIO'
    WHEN A.HC_MES_FIM__C = 6 THEN 'JUNHO'
    WHEN A.HC_MES_FIM__C = 7 THEN 'JULHO'
    WHEN A.HC_MES_FIM__C = 8 THEN 'AGOSTO'
    WHEN A.HC_MES_FIM__C = 9 THEN 'SETEMBRO'
    WHEN A.HC_MES_FIM__C = 10 THEN 'OUTRUBRO'
    WHEN A.HC_MES_FIM__C = 11 THEN 'NOVEMBRO'
    WHEN A.HC_MES_FIM__C = 12 THEN 'DEZEMBRO'
    ELSE NULL
  END AS MES_FINAL,
  'BR' AS LOCALE,
  CONCAT('55', CELULAR) AS CELULAR,
  A.EMAIL,
  A.HC_VALOR_DO_PREMIO__C,
  A.EMAIL_VALIDO,
  A.CELULAR_VALIDO,
  NAO_DESEJA_RECEBER_EMAIL,
  NAO_DESEJA_RECEBER_SMS,
  ID_CONTATO,
  ID_CAMPANHA,
  ID_CLIENTE_PARCEIRO,
  ROW_NUMBER() OVER (ORDER BY CPF_CNPJ) AS [ROW]
FROM TB_CAMPEONATOSKATE A