
SELECT DISTINCT
GmailD3S4.CPF,
GmailD3S4.NOME,
GmailD3S4.EMAIL,
GmailD3S4.EMAIL_VALIDO,
CASE

  WHEN CHARINDEX(' ', GmailD3S4.NOME) = 0 THEN GmailD3S4.NOME

  ELSE SUBSTRING( GmailD3S4.NOME , 1, CHARINDEX(' ', GmailD3S4.NOME) )

END AS PNOME
FROM Gmail_DIV03_SUB04 GmailD3S4
UNION
SELECT DISTINCT
MicrosodftD3S4.CPF,
MicrosodftD3S4.NOME,
MicrosodftD3S4.EMAIL,
MicrosodftD3S4.EMAIL_VALIDO,
CASE

  WHEN CHARINDEX(' ', MicrosodftD3S4.NOME) = 0 THEN MicrosodftD3S4.NOME

  ELSE SUBSTRING( MicrosodftD3S4.NOME , 1, CHARINDEX(' ', MicrosodftD3S4.NOME) )

END AS PNOME
FROM Microsoft_DIV03_SUB04 MicrosodftD3S4
UNION
SELECT DISTINCT
YahooD3S4.CPF,
YahooD3S4.NOME,
YahooD3S4.EMAIL,
YahooD3S4.EMAIL_VALIDO,
CASE

  WHEN CHARINDEX(' ', YahooD3S4.NOME) = 0 THEN YahooD3S4.NOME

  ELSE SUBSTRING( YahooD3S4.NOME , 1, CHARINDEX(' ', YahooD3S4.NOME) )

END AS PNOME
FROM Yahoo_DIV03_SUB04 YahooD3S4
UNION
SELECT DISTINCT
OutrosD3S4.CPF,
OutrosD3S4.NOME,
OutrosD3S4.EMAIL,
OutrosD3S4.EMAIL_VALIDO,
CASE

  WHEN CHARINDEX(' ', OutrosD3S4.NOME) = 0 THEN OutrosD3S4.NOME

  ELSE SUBSTRING( OutrosD3S4.NOME , 1, CHARINDEX(' ', OutrosD3S4.NOME) )

END AS PNOME
FROM Outros_DIV03_SUB04 OutrosD3S4
