
SELECT DISTINCT
GmailD4S2.CPF,
GmailD4S2.NOME,
GmailD4S2.EMAIL,
GmailD4S2.EMAIL_VALIDO,
CASE

  WHEN CHARINDEX(' ', GmailD4S2.NOME) = 0 THEN GmailD4S2.NOME

  ELSE SUBSTRING( GmailD4S2.NOME , 1, CHARINDEX(' ', GmailD4S2.NOME) )

END AS PNOME
FROM Gmail_DIV04_SUB02 GmailD4S2
UNION
SELECT DISTINCT
MicrosodftD4S2.CPF,
MicrosodftD4S2.NOME,
MicrosodftD4S2.EMAIL,
MicrosodftD4S2.EMAIL_VALIDO,
CASE

  WHEN CHARINDEX(' ', MicrosodftD4S2.NOME) = 0 THEN MicrosodftD4S2.NOME

  ELSE SUBSTRING( MicrosodftD4S2.NOME , 1, CHARINDEX(' ', MicrosodftD4S2.NOME) )

END AS PNOME
FROM Microsoft_DIV04_SUB02 MicrosodftD4S2
UNION
SELECT DISTINCT
YahooD4S2.CPF,
YahooD4S2.NOME,
YahooD4S2.EMAIL,
YahooD4S2.EMAIL_VALIDO,
CASE

  WHEN CHARINDEX(' ', YahooD4S2.NOME) = 0 THEN YahooD4S2.NOME

  ELSE SUBSTRING( YahooD4S2.NOME , 1, CHARINDEX(' ', YahooD4S2.NOME) )

END AS PNOME
FROM Yahoo_DIV04_SUB02 YahooD4S2
UNION
SELECT DISTINCT
OutrosD4S2.CPF,
OutrosD4S2.NOME,
OutrosD4S2.EMAIL,
OutrosD4S2.EMAIL_VALIDO,
CASE

  WHEN CHARINDEX(' ', OutrosD4S2.NOME) = 0 THEN OutrosD4S2.NOME

  ELSE SUBSTRING( OutrosD4S2.NOME , 1, CHARINDEX(' ', OutrosD4S2.NOME) )

END AS PNOME
FROM Outros_DIV04_SUB02 OutrosD4S2
