SELECT trim(Ddd_Tel_01) AS DDD1,
       trim(Tel_01) TELEFONE1,
       trim(B.Tipo_Tel_01) TIPO1,
       trim(Ddd_Tel_02) AS DDD2,
       trim(Tel_02) TELEFONE2,
       trim(B.Tipo_Tel_02) TIPO2,
       trim(Ddd_Tel_04) DDD3,
       trim(Tel_04) TELEFONE3,
       trim(B.Tipo_Tel_04) TIPO3,
       trim(Ddd_Tel_05) DDD4,
       trim(Tel_05) TELEFONE4,
       trim(B.Tipo_Tel_05) TIPO4,
       trim(Ddd_Tel_03) DDD5,
       trim(Tel_03) TELEFONE5,
       trim(B.Tipo_Tel_03) TIPO5,
       trim(B.Tel_Principal) PREFERENCIAL,
       B.IDADE,
       CONVERT(VARCHAR(10), B.Dt_Nascimento, 103) AS DATA_NASCIMENTO,
    trim(B.Nome) AS NOME_CLIENTE,
    trim(B.CEP) as CEP,
    '' as UF,
    trim(B.Tipo_Pessoa) TIPO_DE_PESSOA,
    trim(B.CPF_CNPJ) CPF_CNPJ,
    trim(B.Sexo) Sexo,
    trim(B.Publico_Alvo) CLASSIFICAÇAO,
    trim(B.Tipo_Campanha) AS Tipo_Campanha,
    CONVERT(VARCHAR(10), B.Dt_Criacao_Mailing, 103) AS DATA_CRIAÇÃO,
    CONVERT(VARCHAR(10), B.Dt_Inicio_Mailing, 103) AS DATA_UTILIZAÇÃO,
    CONVERT(VARCHAR(10), B.Dt_Fim_Mailing, 103) AS DATA_TERMINO,
    B.Id_Campanha IDCAMPANHA,
    B.Id_Contato IDCONTATO,
    B.Id_Cliente_Parceiro AS IDCP
FROM Tb_Recuperacao_Caducidade_OTC291_Filtrada A
INNER JOIN Tb_Recuperacao_Caducidade_Publico_Inicial B ON A.CPF = B.CPF_CNPJ