SELECT 
    B.ID,
    CASE WHEN DATEDIFF(DD,MAX(C.HC_CONTRATACAO__C), GETDATE()) <= B.MESES_COMPRA_EXCLUSAO /*AND UPPER(D.HC_FAMILIA_DO_PRODUTO__C) = 'OUROCAP'*/ THEN 1 ELSE 0 END AS COMPRA_RECENTE_OUROCAP
FROM Tb_Base_Fim_Plano_Ourocap_PM_ComOTC_NeoBpo B
INNER JOIN HC_TITULO__C_SALESFORCE C ON B.ID_CLIENTE_PARCEIRO = C.HC_CLIENTE_X_PARCEIRO__C
LEFT JOIN HC_PRODUTO__C_SALESFORCE D ON C.HC_PRODUTORELACIONADO__C = D.ID
GROUP BY B.ID,
        MESES_COMPRA_EXCLUSAO