SELECT DISTINCT
    'TCBB' AS COD_PARCEIRO,
    A.HC_CODIGO_DO_PRODUTO__C AS CODIGO,
    A.HC_PRECO__C AS VALOR,
	HC_REGRA_DE_COMERCIALIZACAO__C AS COD_TIPO_PLANO
FROM HC_PRECO_DO_PRODUTO__C_SALESFORCE A
INNER JOIN Tb_Base_Ex_Cliente_OTC291_Tratada_Algar B ON A.ID = B.ID_PRODUTO_VALOR