SELECT 
    B.ID,
    CASE WHEN DATEDIFF(DD,C.HC_CONTRATACAO__C, GETDATE()) <= B.MESES_COMPRA_EXCLUSAO AND UPPER(D.HC_FAMILIA_DO_PRODUTO__C) = 'OUROCAP' THEN 1 ELSE 0 END AS COMPRA_RECENTE_OUROCAP
FROM Revenda_Ourocap_PublicoInicial B
INNER JOIN HC_TITULO__C_SALESFORCE C ON B.CPF_CNPJ = C.HC_CPF_CNPJ_Titular__c
LEFT JOIN HC_PRODUTO__C_SALESFORCE D ON C.HC_PRODUTORELACIONADO__C = D.ID