SELECT
  *
FROM
  TB_BASE_PROSPECT_SEMOTC_TRATADA_TEO
WHERE
  IDADE_VALIDA = 1 
  AND CONTA_CORRENTE = 1 
  AND Quarentena = 0 
  AND CONSELHEIRO = 0 
  AND Cliente = 0 
  AND VALIDA_RNA = 0
  AND NAO_IMPORTUNE = 0