SELECT DISTINCT
  'TCBB' AS COD_PARCEIRO,
  A.CPF,
  '' AS CNPJ,
  '001' AS BANCO,
  B.AGENCIA,
  '' AS DIGITO_VERIFICADOR_AGENCIA,
  B.CONTA AS CONTA_CORRENTE,
  '' AS DIGITO_VERIFICADOR_CONTA,
  '' AS AGENCIA_CONTA_DIGITO_VERIFICADOR,
  'CC' AS TIPO_CONTA
FROM
  TB_BASE_PROSPECT_OTC291_FILTRADA_TMKT A 
  INNER JOIN
    TB_BASE_PROSPECT_COMOTC_TRATADA_TMKT B 
    ON A.CPF = RIGHT(REPLICATE ('0' , 15)+CONVERT(VARCHAR, B.CPF), 11)
    INNER JOIN HC_Relacao_Cliente_Parceiro__c_Salesforce REL ON A.CPF = REL.CPF_CNPJ_Cliente__c
    INNER JOIN Contact_Salesforce C on RIGHT(REPLICATE ('0' , 15)+CONVERT(VARCHAR, C.HC_CPF_CNPJ__c), 11) = B.CPF
    INNER JOIN ACCOUNT_SALESFORCE D on C.AccountId = D.ID