SELECT
	A.CPF_CNPJ,
	A.Numero_do_Titulo,
	A.Serie_do_Titulo,
	A.Plano_do_Titulo,
	A.ID_TITULO,
	1 AS NAO_IMPORTUNE
FROM Tb_Boas_Vindas_3_Meses_Clientes_E_Titulos A
INNER JOIN TB_BASE_NAO_IMPORTUNE N ON ISNULL(RIGHT(A.CELULAR, 11), '00000000000') = LTRIM(RTRIM(N.TELEFONE))
INNER JOIN CAMPAIGN_SALESFORCE CMP ON CMP.ID = A.ID_CAMPANHA
WHERE CELULAR IS NOT NULL AND CMP.HC_VALIDA_NAO_IMPORTUNE__C = 1