SELECT
  A.*
FROM Tb_Base_Ex_Cliente_OTC291_Tratada_Algar A
/* CHECAGEM SE TOODS OS CONTATOS TIVERAM O OTC TRATADO */
LEFT OUTER JOIN ( 
  SELECT
    COUNT(1) as CPFS_FALTANDO_NO_OTC
  FROM Tb_Base_Ex_Cliente_ComOTC_Algar_Filtrada ENV
  LEFT JOIN TB_BASE_Ex_CLIENTE_OTC291_TRATADA_Algar RET ON ENV.CPF_CNPJ = RET.CPF
  WHERE RET.CPF IS NULL
) B ON 1 = 1
WHERE B.CPFS_FALTANDO_NO_OTC <= 2
/* SIGNIFICA QUE TODOS OS CONTATOS JÁ ESTÃO NO OTC291 */
  /* VALIDAÇÕES POR CONTATO DO OTC */
  AND A.CODIGO_RNA = '000'
  AND A.ALTA_RENDA = 0