
SELECT DISTINCT
GmailD3S3.CPF,
GmailD3S3.NOME,
GmailD3S3.EMAIL,
GmailD3S3.EMAIL_VALIDO,
CASE

  WHEN CHARINDEX(' ', GmailD3S3.NOME) = 0 THEN GmailD3S3.NOME

  ELSE SUBSTRING( GmailD3S3.NOME , 1, CHARINDEX(' ', GmailD3S3.NOME) )

END AS PNOME
FROM Gmail_DIV03_SUB03 GmailD3S3
UNION
SELECT DISTINCT
MicrosodftD3S3.CPF,
MicrosodftD3S3.NOME,
MicrosodftD3S3.EMAIL,
MicrosodftD3S3.EMAIL_VALIDO,
CASE

  WHEN CHARINDEX(' ', MicrosodftD3S3.NOME) = 0 THEN MicrosodftD3S3.NOME

  ELSE SUBSTRING( MicrosodftD3S3.NOME , 1, CHARINDEX(' ', MicrosodftD3S3.NOME) )

END AS PNOME
FROM Microsoft_DIV03_SUB03 MicrosodftD3S3
UNION
SELECT DISTINCT
YahooD3S3.CPF,
YahooD3S3.NOME,
YahooD3S3.EMAIL,
YahooD3S3.EMAIL_VALIDO,
CASE

  WHEN CHARINDEX(' ', YahooD3S3.NOME) = 0 THEN YahooD3S3.NOME

  ELSE SUBSTRING( YahooD3S3.NOME , 1, CHARINDEX(' ', YahooD3S3.NOME) )

END AS PNOME
FROM Yahoo_DIV03_SUB03 YahooD3S3
UNION
SELECT DISTINCT
OutrosD3S3.CPF,
OutrosD3S3.NOME,
OutrosD3S3.EMAIL,
OutrosD3S3.EMAIL_VALIDO,
CASE

  WHEN CHARINDEX(' ', OutrosD3S3.NOME) = 0 THEN OutrosD3S3.NOME

  ELSE SUBSTRING( OutrosD3S3.NOME , 1, CHARINDEX(' ', OutrosD3S3.NOME) )

END AS PNOME
FROM Outros_DIV03_SUB03 OutrosD3S3
