SELECT
  A.*
FROM Tb_Base_Fim_Plano_Ourocap_PM_OTC291_Tratada_NeoBpo A
LEFT OUTER JOIN ( 
  SELECT
    COUNT(1) as CPFS_FALTANDO_NO_OTC
  FROM Tb_Base_Fim_Plano_Ourocap_PM_ComOTC_Filtrada ENV
  LEFT JOIN Tb_Base_Fim_Plano_Ourocap_PM_OTC291_Tratada_NeoBpo RET ON ENV.CPF_CNPJ = RET.CPF
  WHERE RET.CPF IS NULL
) B ON 1 = 1
WHERE B.CPFS_FALTANDO_NO_OTC = 0 /* SIGNIFICA QUE TODOS OS CONTATOS JÁ ESTÃO NO OTC291 */
  /* VALIDAÇÕES POR CONTATO DO OTC */
  AND A.CODIGO_RNA = '000'
  AND A.ALTA_RENDA = 0