SELECT
  B.CPF_CNPJ,
    /* CASE WHEN A.HC_CONSELHEIRO__C = 1 THEN 1 ELSE 0 END AS CONSELHEIRO, */
    /* CASE WHEN A.HC_PEP__C = 1 THEN 1 ELSE 0 END AS CLIENTE_PEP, */
    /* CASE WHEN A.HC_NAO_DESEJA_RECEBER_LIGACOES__C = 1 THEN 1 ELSE 0 END AS DESEJA_CONTATO_TELEFONICO, */
    CASE WHEN A.HC_NAO_DESEJA_RECEBER_TODOS_MEIOS__C = 1 THEN 1 ELSE 0 END AS NAO_DESEJA_RECEBER_TODOS_MEIOS,
    CASE WHEN A.HC_NAO_DESEJA_RECEBER_EMAIL__C = 1 THEN 1 ELSE 0 END AS NAO_DESEJA_RECEBER_EMAIL,
    CASE WHEN A.HC_NAO_DESEJA_RECEBER_SMS__C = 1 THEN 1 ELSE 0 END AS NAO_DESEJA_RECEBER_SMS
    /* CASE WHEN A.HC_IDADE__C BETWEEN 18 AND 70 THEN 1 ELSE 0 END AS IDADE_VALIDA, */
    /* CASE WHEN (LEN(CONCAT(B.DDD_TEL_01,B.TEL_01)) = 10 OR LEN(CONCAT(B.DDD_TEL_02,B.TEL_02)) = 10 OR LEN(CONCAT(B.DDD_TEL_03,B.TEL_03)) = 10
     OR LEN(CONCAT(B.DDD_TEL_04,B.TEL_04)) = 11 OR LEN(CONCAT(B.DDD_TEL_05,B.TEL_05)) = 11 OR LEN(CONCAT(B.DDD_TEL_06,B.TEL_06)) = 11) THEN 1 ELSE 0 END AS POSSUI_TELEFONE_ATIVO, */
FROM
  HC_RELACAO_CLIENTE_PARCEIRO__C_SALESFORCE A
INNER JOIN Tb_Campanha_Aniversariantes_Base B ON A.HC_CPF_CNPJ__C = B.CPF_CNPJ