SELECT
  B.CPF_CNPJ,
  CMP.NAME AS CAMPANHA,
  /* B.COMPRA_UTIMOS_30_DIAS AS COMPROU_ULTIMOS_30_DIAS, */
  /* B.CONSELHEIRO, */
  /* B.CLIENTE_PEP, */
  /* B.DESEJA_CONTATO_TELEFONICO AS NAO_DESEJA_RECEBER_LIGACOES, */
  /* B.POSSUI_TELEFONE_ATIVO, */
  /* B.COMPRA_RECENTE_OUROCAP, */
  /* B.POSSUI_CONTA_CORRENTE, */
  B.POSSUI_CONTA_ATIVA,
  /* B.POSSUI_TITULO_ATIVO, */
  B.QUARENTENA,
  B.NAO_IMPORTUNE,
  CASE
    WHEN B.IDADE_VALIDA IS NULL OR B.IDADE_VALIDA = 0 THEN 'IDADE INVALIDA'
    WHEN B.CONSELHEIRO IS NULL OR B.CONSELHEIRO = 1 THEN 'CONSELHEIRO'
    WHEN B.CLIENTE_PEP IS NULL OR B.CLIENTE_PEP = 1 THEN 'PEP'
    WHEN B.DESEJA_CONTATO_TELEFONICO IS NULL OR B.DESEJA_CONTATO_TELEFONICO = 1 THEN 'NÃO DESEJA CONTATO TELEFONICO'
    WHEN B.COMPRA_RECENTE_OUROCAP IS NULL OR B.COMPRA_RECENTE_OUROCAP = 1 THEN 'COMPRA RECENTE OUROCAP'
    /* WHEN B.POSSUI_CONTA_CORRENTE IS NULL OR B.POSSUI_CONTA_CORRENTE = 0 THEN 'NÃO POSSUI CONTA CORRENTE' */
    WHEN B.POSSUI_CONTA_ATIVA IS NULL OR B.POSSUI_CONTA_ATIVA = 0 THEN 'NÃO POSSUI CONTA ATIVA'
    WHEN B.POSSUI_TELEFONE_ATIVO IS NULL OR B.POSSUI_TELEFONE_ATIVO = 0 THEN 'NÃO POSSUI TELEFONE ATIVO'
    WHEN B.NAO_IMPORTUNE IS NULL OR B.NAO_IMPORTUNE = 1 THEN 'NÃO IMPORTUNE'
    WHEN B.QUARENTENA IS NULL OR B.QUARENTENA = 1 THEN 'EM QUARENTENA'
    /* WHEN B.NOME_VALIDA IS NULL OR B.NOME_VALIDA = 0 THEN 'NOME VALIDA' */
  END AS RESULTADO,
  CASE
    WHEN B.IDADE_VALIDA IS NULL OR B.IDADE_VALIDA = 0 THEN NULL
    WHEN B.CONSELHEIRO IS NULL OR B.CONSELHEIRO = 1 THEN NULL
    WHEN B.CLIENTE_PEP IS NULL OR B.CLIENTE_PEP = 1 THEN NULL
    WHEN B.DESEJA_CONTATO_TELEFONICO IS NULL OR B.DESEJA_CONTATO_TELEFONICO = 1 THEN NULL
    WHEN B.COMPRA_RECENTE_OUROCAP IS NULL OR B.COMPRA_RECENTE_OUROCAP = 1 THEN NULL
    WHEN B.POSSUI_CONTA_ATIVA IS NULL OR B.POSSUI_CONTA_ATIVA = 0 THEN NULL
    WHEN B.POSSUI_TELEFONE_ATIVO IS NULL OR B.POSSUI_TELEFONE_ATIVO = 0 THEN NULL
    WHEN B.NAO_IMPORTUNE IS NULL OR B.NAO_IMPORTUNE = 1 THEN NULL
    WHEN B.QUARENTENA IS NULL OR B.QUARENTENA = 1 THEN CONCAT(
      RIGHT( CONCAT('0', DATEPART(DD, DATA_PARTICIPACAO_CAMPANHA)) , 2),
      '/',
      RIGHT( CONCAT('0', DATEPART(MM, DATA_PARTICIPACAO_CAMPANHA)) , 2),
      '/',
      DATEPART(YYYY, DATA_PARTICIPACAO_CAMPANHA)
    )
  END AS DATA_QUARENTENA
  /* B.NOME_VALIDA */

FROM Tb_Base_Inicial_Fim_Plano_Ourocap_PU_PP_ComOTC_TMKT  B
LEFT JOIN CAMPAIGN_SALESFORCE CMP ON B.ID_CAMPANHA = CMP.ID
LEFT JOIN TB_BASE_QUARENTENA Q ON Q.CPF_CNPJ = B.CPF_CNPJ
WHERE
  B.CPF_CNPJ IS NOT NULL
  AND (
  (B.IDADE_VALIDA IS NULL OR B.IDADE_VALIDA = 0)
  OR (B.CONSELHEIRO IS NULL OR B.CONSELHEIRO = 1)
  OR (B.CLIENTE_PEP IS NULL OR B.CLIENTE_PEP = 1)
  OR (B.DESEJA_CONTATO_TELEFONICO IS NULL OR B.DESEJA_CONTATO_TELEFONICO = 1)
  OR (B.COMPRA_RECENTE_OUROCAP IS NULL OR B.COMPRA_RECENTE_OUROCAP = 1)
  OR (B.POSSUI_CONTA_ATIVA IS NULL OR B.POSSUI_CONTA_ATIVA = 0)
  OR (B.POSSUI_TELEFONE_ATIVO IS NULL OR B.POSSUI_TELEFONE_ATIVO = 0)
  OR (B.QUARENTENA IS NULL OR B.QUARENTENA = 1)
  OR (B.NAO_IMPORTUNE IS NULL OR B.NAO_IMPORTUNE = 1)
  )