SELECT
  B.CPF_CNPJ,
  CMP.NAME AS CAMPANHA,
  /* PAR.HC_CODIGO_DO_PARCEIRO_CAP__C AS PARCEIRO, */
  /* CONVERT(INTEGER, REL.HC_IDADE__C) AS  IDADE, */
  DATEDIFF(YY,
  CAST(B.DT_NASCIMENTO AS DATE),
  GETDATE()) AS  IDADE,
  /* B.COMPRA_UTIMOS_30_DIAS AS COMPROU_ULTIMOS_30_DIAS, */
  B.CONSELHEIRO,
  B.CLIENTE_PEP,
  /* B.CLIENTE, */
  B.DESEJA_CONTATO_TELEFONICO AS NAO_DESEJA_RECEBER_LIGACOES,
  B.POSSUI_TELEFONE_ATIVO,
  /* B.POSSUI_CONTA_CORRENTE, */
  B.POSSUI_CONTA_ATIVA AS POSSUI_CONTA_CORRENTE,
  /* B.POSSUI_TITULO_ATIVO, */
  B.QUARENTENA,
  B.NAO_IMPORTUNE,
  /* B.CEP_VALIDO, */
  CASE
    WHEN (B.IDADE_VALIDA IS NULL OR B.IDADE_VALIDA = 0) THEN 'IDADE INVALIDA'
    WHEN (B.CONSELHEIRO IS NULL OR B.CONSELHEIRO = 1) THEN 'CONSELHEIRO'
    
    WHEN (B.CLIENTE_PEP IS NULL OR B.CLIENTE_PEP = 1) THEN 'PEP'
    
    WHEN (B.QUARENTENA IS NULL OR B.QUARENTENA = 1) THEN 'QUARENTENA'
    WHEN (B.NAO_IMPORTUNE = 1) THEN 'NÃO IMPORTUNE'
    /* WHEN (B.CEP_VALIDO IS NULL OR B.CEP_VALIDO = 0) THEN 'CEP INVALIDO' */
    WHEN (B.COMPRA_RECENTE_OUROCAP IS NULL OR B.COMPRA_RECENTE_OUROCAP = 1) THEN 'COMPRA RECENTE OUROCAP'
    WHEN 
      ( ISNULL(CELULAR_VALIDO, 0 ) = 0 OR ISNULL(NAO_DESEJA_RECEBER_SMS, 1) = 1)
      AND ( ISNULL(EMAIL_VALIDO, 0 ) = 0 OR ISNULL(NAO_DESEJA_RECEBER_EMAIL, 1) = 1)
      THEN 'NÃO CONTACTAVEL'
  END AS RESULTADO
  /* B.NOME_VALIDA */
FROM
  Tb_Base_Fim_Plano_Ourocap_PM_ComOTC_NeoBpo B
LEFT JOIN CAMPAIGN_SALESFORCE CMP ON B.ID_CAMPANHA = CMP.ID
/* LEFT JOIN HC_PARCEIRO__C_SALESFORCE PAR ON B.PARCEIRO = PAR.ID */
/* LEFT JOIN HC_RELACAO_CLIENTE_PARCEIRO__C_SALESFORCE REL ON B.ID_CLIENTE_PARCEIRO = REL.ID */
WHERE
  B.CPF_CNPJ IS NOT NULL
  AND (
  (B.IDADE_VALIDA IS NULL OR B.IDADE_VALIDA = 0)
  OR (B.CONSELHEIRO IS NULL OR B.CONSELHEIRO = 1)
  OR (B.CLIENTE_PEP IS NULL OR B.CLIENTE_PEP = 1)
  OR (B.COMPRA_RECENTE_OUROCAP IS NULL OR B.COMPRA_RECENTE_OUROCAP = 1)
  OR (B.QUARENTENA IS NULL OR B.QUARENTENA = 1)
  OR (B.NAO_IMPORTUNE = 1)
  /* OR (B.CEP_VALIDO IS NULL OR B.CEP_VALIDO = 0) */
  /* OR B.ULTIMO_RESGATE = 1 */
  /* OR B.SITUACAO_RESGATE = 1 */
  /* OR (B.NOME_VALIDA IS NULL OR B.NOME_VALIDA = 0) */
  OR (
      ( ISNULL(CELULAR_VALIDO, 0 ) = 0 OR ISNULL(NAO_DESEJA_RECEBER_SMS, 1) = 1)
      AND ( ISNULL(EMAIL_VALIDO, 0 ) = 0 OR ISNULL(NAO_DESEJA_RECEBER_EMAIL, 1) = 1)
    )
  )
  /* AND DESEJA_CONTATO_TELEFONICO = 0  */
  /* AND POSSUI_CONTA_ATIVA = 1 */
  /* AND POSSUI_TELEFONE_ATIVO = 1 */