SELECT
	A.CPF_CNPJ AS ID,
	CASE WHEN Q.CPF_CNPJ IS NOT NULL THEN 1 ELSE 0 END AS QUARENTENA
FROM
	TB_BOAS_VINDAS_POSTALCAP_COMOTC_NEOBPO A
LEFT JOIN TB_BOAS_VINDAS_POSTALCAP_QUARENTENA Q ON A.CPF_CNPJ = Q.CPF_CNPJ
	AND A.NUMERO_DO_TITULO = Q.NUMERO_DO_TITULO
	AND A.SERIE_DO_TITULO = Q.SERIE_DO_TITULO
	AND A.PLANO_DO_TITULO = Q.PLANO_DO_TITULO