SELECT  
  rtrim(left(coalesce(CAST(B.HC_CPF_CNPJ__C as char(255)),'<null>'), 255)) as cpf_cnpj, rtrim(left(coalesce(CAST(C.NAME as char(255)),'<null>'), 255)) as nome, rtrim(left(coalesce(CAST(CASE WHEN B.HC_EMAIL_PRINCIPAL__C = 'Brasilcap' THEN HC_EMAIL_BRASILCAP__C
    WHEN B.HC_EMAIL_PRINCIPAL__C = 'Comercial' THEN HC_EMAIL_COMERCIAL__C
    WHEN B.HC_EMAIL_PRINCIPAL__C = 'Pessoal' THEN HC_EMAIL_PESSOAL__C
    WHEN B.HC_EMAIL_BRASILCAP__C IS NOT NULL THEN HC_EMAIL_BRASILCAP__C
    WHEN B.HC_EMAIL_COMERCIAL__C IS NOT NULL THEN HC_EMAIL_COMERCIAL__C
    WHEN B.HC_EMAIL_PESSOAL__C IS NOT NULL THEN HC_EMAIL_PESSOAL__C
    ELSE NULL END as char(255)),'<null>'), 255)) as email, rtrim(left(coalesce(CAST(CASE WHEN B.HC_EMAIL_PRINCIPAL__C IN ('Brasilcap', 'Comercial', 'Pessoal') THEN 1
    WHEN B.HC_EMAIL_BRASILCAP__C IS NOT NULL THEN 1
    WHEN B.HC_EMAIL_COMERCIAL__C IS NOT NULL THEN 1
    WHEN B.HC_EMAIL_PESSOAL__C IS NOT NULL THEN 1
    ELSE 0 END as char(255)),'<null>'), 255)) as email_valido, rtrim(left(coalesce(CAST(CASE WHEN B.HC_TELEFONE_PRINCIPAL__C = 'CELULAR 1' THEN HC_CELULAR_1__C
    WHEN B.HC_TELEFONE_PRINCIPAL__C = 'CELULAR 2' THEN HC_CELULAR_2__C
    WHEN B.HC_TELEFONE_PRINCIPAL__C = 'CELULAR 3' THEN HC_CELULAR_3__C
    WHEN B.HC_TELEFONE_PRINCIPAL__C = 'CELULAR 3_3' THEN HC_CELULAR_3_3__C
    WHEN B.HC_TELEFONE_PRINCIPAL__C = 'CELULAR 4' THEN HC_CELULAR_4__C
    WHEN B.HC_STATUS_CELULAR_1__C = 'VÁLIDO' THEN HC_CELULAR_1__C
    WHEN B.HC_STATUS_CELULAR_2__C = 'VÁLIDO' THEN HC_CELULAR_2__C
    WHEN B.HC_STATUS_CELULAR_3__C = 'VÁLIDO' THEN HC_CELULAR_3__C
    WHEN B.HC_STATUS_CELULAR_3_3__C = 'VÁLIDO' THEN HC_CELULAR_3_3__C
    WHEN B.HC_STATUS_CELULAR_4__C = 'VÁLIDO' THEN HC_CELULAR_4__C
    ELSE NULL END as char(255)),'<null>'), 255)) as celular, rtrim(left(coalesce(CAST(CASE WHEN B.HC_STATUS_CELULAR_1__C = 'VÁLIDO' THEN 1
    WHEN B.HC_STATUS_CELULAR_2__C = 'VÁLIDO' THEN 1
    WHEN B.HC_STATUS_CELULAR_3__C = 'VÁLIDO' THEN 1
    WHEN B.HC_STATUS_CELULAR_3_3__C = 'VÁLIDO' THEN 1
    WHEN B.HC_STATUS_CELULAR_4__C = 'VÁLIDO' THEN 1
    ELSE 0 END as char(255)),'<null>'), 255)) as celular_valido, rtrim(left(coalesce(CAST(B.HC_NAO_DESEJA_RECEBER_SMS__C as char(255)),'<null>'), 255)) as nao_deseja_receber_sms, rtrim(left(coalesce(CAST(B.HC_NAO_DESEJA_RECEBER_EMAIL__C as char(255)),'<null>'), 255)) as nao_deseja_receber_email, rtrim(left(coalesce(CAST(A.ID as char(255)),'<null>'), 255)) as id_campanha, rtrim(left(coalesce(CAST(B.ID as char(255)),'<null>'), 255)) as id_cliente_parceiro, rtrim(left(coalesce(CAST(C.ID as char(255)),'<null>'), 255)) as id_contato, rtrim(left(coalesce(CAST(PROP.ID as char(255)),'<null>'), 255)) as id_proposta, rtrim(left(coalesce(CAST(PROP.CREATEDDATE as char(255)),'<null>'), 255)) as CREATEDDATE from CAMPAIGN_SALESFORCE A
INNER JOIN HC_RELACAO_CLIENTE_PARCEIRO__C_SALESFORCE B ON A.HC_PARCEIRO__C = B.HC_PARCEIRO__C
INNER JOIN CONTACT_SALESFORCE C ON C.HC_CPF_CNPJ__C = B.HC_CPF_CNPJ__C
INNER JOIN HC_PROPOSTA__C_SALESFORCE PROP ON B.ID = PROP.HC_TITULAR__C
LEFT JOIN AeM_Boas_Vindas_Historico_Propostas HIST ON HIST.ID_PROPOSTA = PROP.ID
WHERE
  (B.HC_TIPO_DE_PESSOA__C = A.HC_TIPO_DE_CLIENTE__C OR A.HC_TIPO_DE_CLIENTE__C = 'PF E PJ')

  
  AND A.ISACTIVE = 1

  AND A.PARENTID = '7016g000000NVrXAAW'

  AND HIST.ID_PROPOSTA IS NULL

  AND A.HC_PARCEIRO__C = B.HC_PARCEIRO__C
  AND ISNULL(B.HC_NAO_DESEJA_RECEBER_TODOS_MEIOS__C, 0) = 0
  AND PROP.CREATEDDATE BETWEEN A.HC_DATA_INICIAL_DE_COMPRA__C AND A.HC_DATA_FINAL_DE_COMPRA__C
  AND (

    (A.HC_VALOR_MINIMO_DE_PARCELA__C IS NULL OR PROP.HC_VALOR__C > A.HC_VALOR_MINIMO_DE_PARCELA__C)
    AND (A.HC_VALOR_MAXIMO_DA_PARCELA__C IS NULL OR PROP.HC_VALOR__C < A.HC_VALOR_MAXIMO_DA_PARCELA__C)
  )

  AND (

    (( B.HC_EMAIL_BRASILCAP__C IS NOT NULL OR B.HC_EMAIL_COMERCIAL__C IS NOT NULL OR B.HC_EMAIL_PESSOAL__C IS NOT NULL ) AND ISNULL(B.HC_NAO_DESEJA_RECEBER_EMAIL__C, 0) = 0 )

    OR (
        ( B.HC_STATUS_CELULAR_1__C = 'VÁLIDO' OR B.HC_STATUS_CELULAR_2__C = 'VÁLIDO' OR B.HC_STATUS_CELULAR_3__C = 'VÁLIDO' 
        OR B.HC_STATUS_CELULAR_3_3__C = 'VÁLIDO' OR B.HC_STATUS_CELULAR_4__C = 'VÁLIDO' ) 
      AND ISNULL(B.HC_NAO_DESEJA_RECEBER_SMS__C, 0) = 0 )
  )