SELECT
	BASE.*
FROM (
	SELECT DISTINCT
		B.HC_CPF_CNPJ__C AS CPF_CNPJ,
		ACC.NAME AS NOME,
		ACC.HC_IDADE__C AS IDADE,
		HC_DATA_DE_NASCIMENTO__C AS DT_NASCIMENTO,
		HC_GENERO_DO_CLIENTE__C AS SEXO,
		CASE 
			WHEN UPPER(B.HC_ENDERECO_PRINCIPAL__C) = 'RESIDENCIAL' THEN HC_CEP_RES__C
			WHEN UPPER(B.HC_ENDERECO_PRINCIPAL__C) = 'COMERCIAL' THEN HC_CEP_COM__C
			WHEN UPPER(B.HC_ENDERECO_PRINCIPAL__C) = 'CORRESPONDÊNCIA' THEN HC_CEP_COR__C
		END AS CEP,
		ACC.HC_TIPO_DE_PESSOA__C AS TIPO_PESSOA,
		LEFT(REPLACE(REPLACE(REPLACE(REPLACE(HC_TELEFONE_RESIDENCIAL__C, '(', ''), ')', ''), ' ', ''), '-', ''), 2) AS DDD_TEL_01,
		SUBSTRING(REPLACE(REPLACE(REPLACE(REPLACE(HC_TELEFONE_RESIDENCIAL__C, '(', ''), ')', ''), ' ', ''), '-', ''), 3, 9) AS TEL_01,
		'FIXO' AS TIPO_TEL_01,
		LEFT(REPLACE(REPLACE(REPLACE(REPLACE(HC_TELEFONE_COMERCIAL__C, '(', ''), ')', ''), ' ', ''), '-', ''), 2) AS DDD_TEL_02,
		SUBSTRING(REPLACE(REPLACE(REPLACE(REPLACE(HC_TELEFONE_COMERCIAL__C, '(', ''), ')', ''), ' ', ''), '-', ''), 3, 9) AS TEL_02,
		'FIXO' AS TIPO_TEL_02,
		LEFT(REPLACE(REPLACE(REPLACE(REPLACE(HC_TELEFONE_OUTRO__C, '(', ''), ')', ''), ' ', ''), '-', ''), 2) AS DDD_TEL_03,
		SUBSTRING(REPLACE(REPLACE(REPLACE(REPLACE(HC_TELEFONE_OUTRO__C, '(', ''), ')', ''), ' ', ''), '-', ''), 3, 9) AS TEL_03,
		'FIXO' AS TIPO_TEL_03,
		LEFT(REPLACE(REPLACE(REPLACE(REPLACE(HC_CELULAR_1__C, '(', ''), ')', ''), ' ', ''), '-', ''), 2) AS DDD_TEL_04,
		SUBSTRING(REPLACE(REPLACE(REPLACE(REPLACE(HC_CELULAR_1__C, '(', ''), ')', ''), ' ', ''), '-', ''), 3, 9) AS TEL_04,
		'MÓVEL' AS TIPO_TEL_04,
		LEFT(REPLACE(REPLACE(REPLACE(REPLACE(HC_CELULAR_2__C, '(', ''), ')', ''), ' ', ''), '-', ''), 2) AS DDD_TEL_05,
		SUBSTRING(REPLACE(REPLACE(REPLACE(REPLACE(HC_CELULAR_2__C, '(', ''), ')', ''), ' ', ''), '-', ''), 3, 9) AS TEL_05,
		'MÓVEL' AS TIPO_TEL_05,
		LEFT(REPLACE(REPLACE(REPLACE(REPLACE(HC_CELULAR_3__C, '(', ''), ')', ''), ' ', ''), '-', ''), 2) AS DDD_TEL_06,
		SUBSTRING(REPLACE(REPLACE(REPLACE(REPLACE(HC_CELULAR_3__C, '(', ''), ')', ''), ' ', ''), '-', ''), 3, 9) AS TEL_06,
		'MÓVEL' AS TIPO_TEL_06,
		HC_TELEFONE_PRINCIPAL__C AS TEL_PRINCIPAL,
		B.HC_CLASSIFICACAO__C AS PUBLICO_ALVO,
		A.[TYPE] AS TIPO_CAMPANHA,
		A.STARTDATE AS DT_INICIO_MAILING,
		A.ENDDATE AS DT_FIM_MAILING,
		A.HC_VALIDA_ALTA_RENDA__C AS CAMPANHA_VALIDA_ENCARTEIRAMENTO,
		A.HC_VALIDA_NAO_IMPORTUNE__C AS CAMPANHA_NAO_IMPORTUNE,
		A.HC_VALIDA_RNA__C AS CAMPANHA_VALIDA_RNA,
		A.HC_PRODUTO__C AS ID_PRODUTO,
		A.HC_PRECO_DO_PRODUTO__C AS ID_PRODUTO_VALOR,
		B.HC_CPF_CNPJ__C AS ID,
		A.ID AS ID_CAMPANHA, 
		B.ID AS ID_CLIENTE_PARCEIRO,
		C.ID AS ID_CONTATO,
		B.HC_CPF_CNPJ_CODIGO_PARCEIRO_UNICO__C AS CPF_CNPJ_CODIGO_DO_PARCEIRO,
		CASE WHEN HC_Conta_Principal__c = 'CONTA 1' AND HC_Tipo_da_Conta_1__c = 'Conta Corrente' THEN 'CONTA 1'
			 WHEN HC_Conta_Principal__c = 'CONTA 2' AND HC_Tipo_da_Conta_2__c = 'Conta Corrente' THEN 'CONTA 2'
			 WHEN HC_Tipo_da_Conta_1__c = 'Conta Corrente' AND HC_Tipo_da_Conta_2__c = 'Conta Poupança' THEN 'CONTA 1'
			 WHEN HC_Tipo_da_Conta_2__c = 'Conta Corrente' AND HC_Tipo_da_Conta_1__c = 'Conta Poupança' THEN 'CONTA 2'
			 ELSE 'ERRO' END AS CONTA_BANCARIA,
		CASE WHEN CHARINDEX('&', C.NAME, 0) = 0 THEN 1 ELSE 0 END AS NOME_VALIDA,
		ROW_NUMBER() OVER(ORDER BY B.ID ASC) AS ROWNO
  FROM (
    SELECT
      A.ID AS CAMPAIGN_ID,
      B.ID AS RELACAO_CLIENTE_PARCEIRO_ID,
      C.ID AS CONTACT_ID,
      T.ID AS TITULO_ID,
      ACC.ID AS ACCOUNT_ID,
      ROW_NUMBER() OVER(PARTITION BY B.ID ORDER BY B.ID ASC) AS NUMBER_OF_CPF_REPETITION
    FROM CAMPAIGN_SALESFORCE A
    INNER JOIN HC_RELACAO_CLIENTE_PARCEIRO__C_SALESFORCE B ON A.HC_PARCEIRO__C = B.HC_PARCEIRO__C
                                AND A.[TYPE] = B.HC_CLASSIFICACAO__C
                                AND B.HC_TIPO_DE_PESSOA__C = 'PF'
    INNER JOIN Contact_Salesforce C ON C.HC_CPF_CNPJ__c = B.HC_CPF_CNPJ__c
    INNER JOIN HC_Titulo__c_Salesforce T ON B.HC_CPF_CNPJ__c = T.HC_CPF_CNPJ_Titular__c
    INNER JOIN Account_Salesforce ACC ON C.AccountId = ACC.Id
    LEFT JOIN HC_PROPOSTA__C_SALESFORCE P ON P.HC_CPF_CNPJ_TITULAR__C = B.HC_CPF_CNPJ__C 
      AND DATEDIFF(DAY, CONVERT(CHAR(10), P.CREATEDDATE, 112), CONVERT(CHAR(10), GETDATE(), 112)) <= A.HC_COMPRA_RECENTE__C 
    WHERE
      A.[TYPE] = 'Ex-Cliente'
    AND P.HC_CPF_CNPJ_TITULAR__C IS NULL
    AND A.HC_FORMATO__C = 'Offline'
    AND A.HC_FORNECEDOR__C = 'Algar'
		AND B.HC_CONSELHEIRO__C = 0
		AND B.HC_PEP__C = 0
		AND B.HC_NAO_DESEJA_RECEBER_LIGACOES__C = 0
		AND B.HC_NAO_DESEJA_RECEBER_TODOS_MEIOS__C = 0
		AND B.HC_IDADE__C BETWEEN 18 AND 70
		AND ACC.HC_TIPO_DE_PESSOA__C = 'PF'
		AND (
			(HC_Conta_Principal__c = 'CONTA 1' AND HC_Tipo_da_Conta_1__c = 'Conta Corrente')
			OR (HC_Conta_Principal__c = 'CONTA 2' AND HC_Tipo_da_Conta_2__c = 'Conta Corrente')
			OR (HC_Tipo_da_Conta_1__c = 'Conta Corrente' AND HC_Tipo_da_Conta_2__c = 'Conta Poupança')
			OR (HC_Tipo_da_Conta_2__c = 'Conta Corrente' AND HC_Tipo_da_Conta_1__c = 'Conta Poupança')
		)			 
  ) FILTERED
  INNER JOIN CAMPAIGN_SALESFORCE A ON A.ID = FILTERED.CAMPAIGN_ID
  INNER JOIN HC_RELACAO_CLIENTE_PARCEIRO__C_SALESFORCE B ON B.ID = FILTERED.RELACAO_CLIENTE_PARCEIRO_ID
  INNER JOIN Contact_Salesforce C ON C.ID = FILTERED.CONTACT_ID
  INNER JOIN HC_Titulo__c_Salesforce T ON T.ID = FILTERED.TITULO_ID
  INNER JOIN Account_Salesforce ACC ON ACC.ID = FILTERED.ACCOUNT_ID
  WHERE FILTERED.NUMBER_OF_CPF_REPETITION = 1
) BASE
INNER JOIN
  CAMPAIGN_SALESFORCE CAMP 
  ON BASE.ID_CAMPANHA = CAMP.ID
WHERE
	CAMP.HC_QUANTIDADE_DE_CONTATOS_NO_MAILING__C IS NULL
	OR BASE.ROWNO <= CAMP.HC_QUANTIDADE_DE_CONTATOS_NO_MAILING__C