SELECT
	A.CPF_CNPJ AS ID,
	CASE WHEN (A.CAMPANHA_NAO_IMPORTUNE = 1 AND N1.TELEFONE IS NOT NULL) THEN 1 ELSE 0 END AS NAO_IMPORTUNE
FROM Tb_Base_Prop_Ourocap_N_Pag A
LEFT JOIN TB_BASE_NAO_IMPORTUNE N1 ON ISNULL(CONCAT(A.DDD_TEL_01, A.TEL_01), '00000000000') = LTRIM(RTRIM(N1.TELEFONE))