SELECT
	BASE.*
FROM (
	SELECT DISTINCT
		B.HC_CPF_CNPJ__C AS CPF_CNPJ,
		replace( replace( replace( replace( replace( replace( replace (replace (replace (replace (replace (replace (replace (replace (replace (replace (replace (replace (replace (replace (replace (replace (replace (replace (replace (replace (replace (replace (replace (replace (C.NAME, 'á', 'a'),'é', 'e'),'í', 'i'),'ó', 'o'),'ú', 'u'),'Á', 'A'),'É', 'E'),'Í', 'I'),'Ó', 'O'),'Ú', 'U'),'à', 'a'),'À', 'A'),'ã', 'a'),'õ', 'o'),'Ã', 'A'),  'Õ', 'O'),'â', 'a'),'ê', 'e'),'ô', 'o'),'Â', 'A'),'Ê', 'E'),'Ô', 'O'),'ç', 'c'),'Ç', 'c') , '-', '') , '+', '') , '|', '') , '$', '') , '%', '') , '&', '') AS NOME,
		CASE
      WHEN B.HC_TELEFONE_PRINCIPAL__C = 'CELULAR 1' THEN HC_CELULAR_1__C
      WHEN B.HC_TELEFONE_PRINCIPAL__C = 'CELULAR 2' THEN HC_CELULAR_2__C
      WHEN B.HC_TELEFONE_PRINCIPAL__C = 'CELULAR 3' THEN HC_CELULAR_3__C
      WHEN B.HC_TELEFONE_PRINCIPAL__C = 'CELULAR 3_3' THEN HC_CELULAR_3_3__C
      WHEN B.HC_TELEFONE_PRINCIPAL__C = 'CELULAR 4' THEN HC_CELULAR_4__C
      WHEN B.HC_STATUS_CELULAR_1__C = 'VÁLIDO' THEN HC_CELULAR_1__C
      WHEN B.HC_STATUS_CELULAR_2__C = 'VÁLIDO' THEN HC_CELULAR_2__C
      WHEN B.HC_STATUS_CELULAR_3__C = 'VÁLIDO' THEN HC_CELULAR_3__C
      WHEN B.HC_STATUS_CELULAR_3_3__C = 'VÁLIDO' THEN HC_CELULAR_3_3__C
      WHEN B.HC_STATUS_CELULAR_4__C = 'VÁLIDO' THEN HC_CELULAR_4__C
      ELSE NULL
    END AS CELULAR,
		A.ID AS ID_CAMPANHA, 
		B.ID AS ID_CLIENTE_PARCEIRO,
		C.ID AS ID_CONTATO,
        P.ID AS ID_PROPOSTA,
		P.HC_SITUACAO__C,
		P.HC_DATA_DA_VENDA__C AS DATA_PROPOSTA,
		P.HC_AGENDAMENTO__C AS DATA_AGENDAMENTO,
        format(P.HC_AGENDAMENTO__C ,'dd/MM/yyyy') AS DATA_AGENDAMENTO_FORMATADA,
        GETDATE()+1 AS DATA_PROXIMA_EXECUCAO,
		ROW_NUMBER() OVER(ORDER BY B.ID ASC) AS ROWNO
	FROM (
		SELECT
		  A.ID AS CAMPAIGN_ID,
		  B.ID AS RELACAO_CLIENTE_PARCEIRO_ID,
		  C.ID AS CONTACT_ID,
		  P.ID AS PROPOSTA_ID,
		  ROW_NUMBER() OVER(PARTITION BY B.ID ORDER BY B.ID ASC) AS NUMBER_OF_CPF_REPETITION
		FROM CAMPAIGN_SALESFORCE A
		INNER JOIN HC_RELACAO_CLIENTE_PARCEIRO__C_SALESFORCE B ON 1 = 1
		INNER JOIN CONTACT_SALESFORCE C ON C.HC_CPF_CNPJ__c = B.HC_CPF_CNPJ__c
		INNER JOIN HC_PROPOSTA__C_SALESFORCE P ON P.HC_CPF_CNPJ_TITULAR__C = B.HC_CPF_CNPJ__C 
		WHERE
      A.ID = '7016g000000ThNpAAK'
      /* Momento de execução da campanha */
      /*AND CONVERT(VARCHAR(10), A.HC_DATA_DE_EXECUCAO__C, 101) = CONVERT(VARCHAR(10), GETDATE(), 101)
      AND DATEPART(HH, A.HC_DATA_DE_EXECUCAO__C) = DATEPART(HH, GETDATE())*/
      AND (A.HC_PARCEIRO__C = B.HC_PARCEIRO__C OR A.HC_PARCEIRO__C IS NULL)
      AND A.ISACTIVE = 1
      AND P.HC_SITUACAO__C IN ('AGUARDANDO PAGAMENTO', 'AGENDADA')
      AND (B.HC_TIPO_DE_PESSOA__C = A.HC_TIPO_DE_CLIENTE__C OR A.HC_TIPO_DE_CLIENTE__C = 'PF E PJ')
      AND B.HC_CLASSIFICACAO__C != 'Falecido'
      AND HC_CONSELHEIRO__C = 0
      AND HC_PEP__C = 0
      AND B.HC_IDADE__C BETWEEN 18 AND 70
      AND ISNULL(B.HC_NAO_DESEJA_RECEBER_TODOS_MEIOS__C, 0) = 0
      AND (ISNULL(B.HC_NAO_IMPORTUNE__C, 0) = 0 OR A.HC_VALIDA_NAO_IMPORTUNE__C = 0)
      AND P.HC_TIPO_DE_PAGAMENTO__C = 'PM'
      /* Celular valido e deseja receber sms */
      AND (
        ( B.HC_STATUS_CELULAR_1__C = 'VÁLIDO' OR B.HC_STATUS_CELULAR_2__C = 'VÁLIDO' OR B.HC_STATUS_CELULAR_3__C = 'VÁLIDO' 
        OR B.HC_STATUS_CELULAR_3_3__C = 'VÁLIDO' OR B.HC_STATUS_CELULAR_4__C = 'VÁLIDO' ) 
        AND ISNULL(B.HC_NAO_DESEJA_RECEBER_SMS__C, 0) = 0 
      )
      AND CONVERT(VARCHAR, P.HC_AGENDAMENTO__C, 101) = CONVERT(VARCHAR, DATEADD(DD, A.DIAS_PARA_AGENDAMENTO_DA_PROPOSTA__C, GETDATE()), 101)
  ) FILTERED
  INNER JOIN CAMPAIGN_SALESFORCE A ON A.ID = FILTERED.CAMPAIGN_ID
  INNER JOIN HC_RELACAO_CLIENTE_PARCEIRO__C_SALESFORCE B ON B.ID = FILTERED.RELACAO_CLIENTE_PARCEIRO_ID
  INNER JOIN CONTACT_SALESFORCE C ON C.ID = FILTERED.CONTACT_ID
  INNER JOIN HC_PROPOSTA__C_SALESFORCE P ON P.ID = FILTERED.PROPOSTA_ID
  WHERE FILTERED.NUMBER_OF_CPF_REPETITION = 1
) BASE
INNER JOIN
  CAMPAIGN_SALESFORCE CAMP 
  ON BASE.ID_CAMPANHA = CAMP.ID
WHERE
	CAMP.HC_QUANTIDADE_DE_CONTATOS_NO_MAILING__C IS NULL
	OR BASE.ROWNO <= CAMP.HC_QUANTIDADE_DE_CONTATOS_NO_MAILING__C