SELECT DISTINCT
  'TCBB' AS COD_PARCEIRO,
  B.CPF,
  '' AS CNPJ,
  B.CEP,
  '99999999999' AS INICIO_TRAILLER 
FROM
  TB_BASE_PROSPECT_OTC291_FILTRADA_NEOBPO A 
  INNER JOIN
    TB_BASE_PROSPECT_COMOTC_TRATADA_NEOBPO B 
    ON A.CPF = B.CPF