
SELECT DISTINCT
GmailD5S1.CPF,
GmailD5S1.NOME,
GmailD5S1.EMAIL,
GmailD5S1.EMAIL_VALIDO,
CASE

  WHEN CHARINDEX(' ', GmailD5S1.NOME) = 0 THEN GmailD5S1.NOME

  ELSE SUBSTRING( GmailD5S1.NOME , 1, CHARINDEX(' ', GmailD5S1.NOME) )

END AS PNOME
FROM Gmail_DIV05_SUB01 GmailD5S1
UNION
SELECT DISTINCT
MicrosodftD5S1.CPF,
MicrosodftD5S1.NOME,
MicrosodftD5S1.EMAIL,
MicrosodftD5S1.EMAIL_VALIDO,
CASE

  WHEN CHARINDEX(' ', MicrosodftD5S1.NOME) = 0 THEN MicrosodftD5S1.NOME

  ELSE SUBSTRING( MicrosodftD5S1.NOME , 1, CHARINDEX(' ', MicrosodftD5S1.NOME) )

END AS PNOME
FROM Microsoft_DIV05_SUB01 MicrosodftD5S1
UNION
SELECT DISTINCT
YahooD5S1.CPF,
YahooD5S1.NOME,
YahooD5S1.EMAIL,
YahooD5S1.EMAIL_VALIDO,
CASE

  WHEN CHARINDEX(' ', YahooD5S1.NOME) = 0 THEN YahooD5S1.NOME

  ELSE SUBSTRING( YahooD5S1.NOME , 1, CHARINDEX(' ', YahooD5S1.NOME) )

END AS PNOME
FROM Yahoo_DIV05_SUB01 YahooD5S1
UNION
SELECT DISTINCT
OutrosD5S1.CPF,
OutrosD5S1.NOME,
OutrosD5S1.EMAIL,
OutrosD5S1.EMAIL_VALIDO,
CASE

  WHEN CHARINDEX(' ', OutrosD5S1.NOME) = 0 THEN OutrosD5S1.NOME

  ELSE SUBSTRING( OutrosD5S1.NOME , 1, CHARINDEX(' ', OutrosD5S1.NOME) )

END AS PNOME
FROM Outros_DIV05_SUB01 OutrosD5S1
