SELECT DISTINCT
    UPPER(A.NOME) AS NOME,
	LTRIM(RTRIM(A.CPF)) AS CPF,
	A.AGENCIA,
	A.CONTA,
	A.TIPO_CONTA,
	A.DATA_NASCIMENTO,
	A.SEXO,
	A.CEP,
	A.DDD_01,
	A.TEL_01,
	A.DDD_02,
	A.TEL_02,
	A.DDD_03,
	A.TEL_03,
	A.DDD_04,
	A.TEL_04,
	A.DDD_05,
	A.TEL_05,
    CA.ID AS ID_CAMPANHA,
    CA.HC_PRODUTO__C AS NOME_PRODUTO,
    CA.HC_PRECO_DO_PRODUTO__C AS NOME_PRODUTO_VALOR,
    CA.HC_VALIDA_ALTA_RENDA__C AS VALIDA_ENCARTEIRAMENTO,
    CA.HC_VALIDA_NAO_IMPORTUNE__C AS VALIDA_NAO_IMPORTUNE,
    CA.HC_VALIDA_RNA__C AS VALIDA_RNA,
    CASE WHEN DATEDIFF(YY, CONVERT(VARCHAR, CONVERT(DATE, A.DATA_NASCIMENTO, 103), 112), CONVERT(VARCHAR, GETDATE(), 112)) BETWEEN 18 AND 70 THEN 1 ELSE 0 END AS IDADE_VALIDA,
    CASE WHEN (UPPER(A.TIPO_CONTA) = 'CC' OR UPPER(A.TIPO_CONTA) = 'CONTA CORRENTE') THEN 1 ELSE 0 END AS CONTA_CORRENTE,
    CASE WHEN Q.CPF_CNPJ IS NOT NULL THEN 1 ELSE 0 END AS QUARENTENA,
    CASE WHEN CL.HC_CPF_CNPJ__C IS NOT NULL AND CL.HC_CLASSIFICACAO__C != 'Cliente Potencial' THEN 1 ELSE 0 END AS CLIENTE,
    CASE WHEN CL.HC_CPF_CNPJ__C IS NOT NULL AND CL.HC_CONSELHEIRO__C = 1 THEN 1 ELSE 0 END AS CONSELHEIRO,
	CASE WHEN ISNULL(A.CEP, '') = '' OR A.CEP = ' ' THEN 0 ELSE 1 END AS CEP_VALIDO
FROM TB_BASE_PROSPECT_SEMOTC_NEOBPO A
INNER JOIN CAMPAIGN_SALESFORCE CA ON A.FORNECEDOR = CA.HC_FORNECEDOR__C
LEFT JOIN HC_RELACAO_CLIENTE_PARCEIRO__C_SALESFORCE CL ON LTRIM(RTRIM(A.CPF)) = CL.HC_CPF_CNPJ__C
LEFT JOIN TB_BASE_QUARENTENA Q ON LTRIM(RTRIM(A.CPF)) = Q.CPF_CNPJ
WHERE
    CA.HC_FORNECEDOR__C = 'NeoBpo'
AND CONVERT(VARCHAR, CA.CREATEDDATE, 112) = CONVERT(VARCHAR, GETDATE(), 112)
AND CA.[TYPE] = 'Prospect'
AND CA.HC_VALIDA_RNA__C = 0