SELECT 
	CPF_CNPJ,
	MAX(Nome) AS Nome,
	MAX(Id_Campanha) AS Id_Campanha,
	MAX(Id) AS Id,
	MAX(Id_Contato) AS Id_Contato,
	MAX(Id_Cliente) AS Id_Cliente,
	MAX(CONVERT(INTEGER, NAO_DESEJA_RECEBER_EMAIL)) AS NAO_DESEJA_RECEBER_EMAIL,
	MAX(CONVERT(INTEGER, NAO_DESEJA_RECEBER_SMS)) AS NAO_DESEJA_RECEBER_SMS,
	MAX(EMAIL) AS EMAIL,
	MAX(convert(integer, EMAIL_VALIDO)) AS EMAIL_VALIDO,
	MAX(CELULAR) AS CELULAR,
	MAX(convert(integer, CELULAR_VALIDO)) AS CELULAR_VALIDO,
	MAX(QUANTIDADE_TITULOS_ANTERIORES_ATIVOS) AS QUANTIDADE_TITULOS_ANTERIORES_ATIVOS,
	MAX(QUANTIDADE_TITULOS_ANTERIORES_INATIVOS) AS QUANTIDADE_TITULOS_ANTERIORES_INATIVOS,
	MAX(CREATEDDATE) AS CREATEDDATE
FROM TB_BOAS_VINDAS_OUROCAP_CLIENTES_E_TITULOS
WHERE NAO_IMPORTUNE = 0
	AND (
	  ( ISNULL(NAO_DESEJA_RECEBER_EMAIL, 0) = 0 AND EMAIL_VALIDO = 1 )
	  OR ( ISNULL(NAO_DESEJA_RECEBER_SMS, 0) = 0 AND CELULAR_VALIDO = 1 )
	)
	AND QUARENTENA = 0
GROUP BY CPF_CNPJ