SELECT
  B.CPF_CNPJ,
  CMP.NAME AS CAMPANHA,
  PAR.HC_CODIGO_DO_PARCEIRO_CAP__C AS PARCEIRO,
  CONVERT(INTEGER, REL.HC_IDADE__C) AS  IDADE,
  B.COMPRA_UTIMOS_30_DIAS AS COMPROU_ULTIMOS_30_DIAS,
  B.CONSELHEIRO,
  B.CLIENTE_PEP,
  B.DESEJA_CONTATO_TELEFONICO AS NAO_DESEJA_RECEBER_LIGACOES,
  B.POSSUI_TELEFONE_ATIVO,
  B.POSSUI_CONTA_CORRENTE,
  B.POSSUI_TITULO_ATIVO,
  B.QUARENTENA,
  'NÃO IMPORTUNE' AS RESULTADO,
  B.NAO_IMPORTUNE
FROM
  TB_BASE_CLIENTE_FILTRADA_COMOTC_NEOBPO B
LEFT JOIN TB_BASE_CLIENTE_COMOTC_NEOBPO EXC ON EXC.ID = B.ID
LEFT JOIN CAMPAIGN_SALESFORCE CMP ON B.ID_CAMPANHA = CMP.ID
LEFT JOIN HC_PARCEIRO__C_SALESFORCE PAR ON B.PARCEIRO = PAR.ID
LEFT JOIN HC_RELACAO_CLIENTE_PARCEIRO__C_SALESFORCE REL ON B.ID_CLIENTE_PARCEIRO = REL.ID
WHERE
  EXC.ID IS NOT NULL
  AND 
  (B.NAO_IMPORTUNE IS NULL OR B.NAO_IMPORTUNE = 0)
  AND B.CPF_CNPJ IS NOT NULL