
SELECT DISTINCT
GmailD2S4.CPF,
GmailD2S4.NOME,
GmailD2S4.EMAIL,
GmailD2S4.EMAIL_VALIDO,
CASE

  WHEN CHARINDEX(' ', GmailD2S4.NOME) = 0 THEN GmailD2S4.NOME

  ELSE SUBSTRING( GmailD2S4.NOME , 1, CHARINDEX(' ', GmailD2S4.NOME) )

END AS PNOME
FROM Gmail_DIV02_SUB04 GmailD2S4
UNION
SELECT DISTINCT
MicrosodftD2S4.CPF,
MicrosodftD2S4.NOME,
MicrosodftD2S4.EMAIL,
MicrosodftD2S4.EMAIL_VALIDO,
CASE

  WHEN CHARINDEX(' ', MicrosodftD2S4.NOME) = 0 THEN MicrosodftD2S4.NOME

  ELSE SUBSTRING( MicrosodftD2S4.NOME , 1, CHARINDEX(' ', MicrosodftD2S4.NOME) )

END AS PNOME
FROM Microsoft_DIV02_SUB04 MicrosodftD2S4
UNION
SELECT DISTINCT
YahooD2S4.CPF,
YahooD2S4.NOME,
YahooD2S4.EMAIL,
YahooD2S4.EMAIL_VALIDO,
CASE

  WHEN CHARINDEX(' ', YahooD2S4.NOME) = 0 THEN YahooD2S4.NOME

  ELSE SUBSTRING( YahooD2S4.NOME , 1, CHARINDEX(' ', YahooD2S4.NOME) )

END AS PNOME
FROM Yahoo_DIV02_SUB04 YahooD2S4
UNION
SELECT DISTINCT
OutrosD2S4.CPF,
OutrosD2S4.NOME,
OutrosD2S4.EMAIL,
OutrosD2S4.EMAIL_VALIDO,
CASE

  WHEN CHARINDEX(' ', OutrosD2S4.NOME) = 0 THEN OutrosD2S4.NOME

  ELSE SUBSTRING( OutrosD2S4.NOME , 1, CHARINDEX(' ', OutrosD2S4.NOME) )

END AS PNOME
FROM Outros_DIV02_SUB04 OutrosD2S4
