SELECT
	A.CPF_CNPJ,
	A.ID_PROPOSTA,
	1 AS NAO_IMPORTUNE
FROM TB_BOAS_VINDAS_PESQUISA_SMS A
INNER JOIN TB_BASE_NAO_IMPORTUNE N ON ISNULL(RIGHT(A.CELULAR, 11), '00000000000') = LTRIM(RTRIM(N.TELEFONE))
INNER JOIN CAMPAIGN_SALESFORCE CMP ON CMP.ID = A.ID_CAMPANHA
WHERE CELULAR IS NOT NULL AND CMP.HC_VALIDA_NAO_IMPORTUNE__C = 1